import type {
  CasaMiaPackage,
  ConditionalRule,
  ConfiguratorPricing,
  PackageId,
  WizardQuestion,
} from '../types/configurator.ts'

export const casaMiaPackages: CasaMiaPackage[] = [
  {
    id: 'entrance-safe',
    name: 'CasaMia Entrance Safe',
    shortName: 'Entrance',
    outcome: 'Make arrivals safer with lighting, access support and secure entry.',
    salesUnit: 'Per entrance',
    quantityKey: 'entrances',
    standardComponents: [
      { id: 'video-doorbell', label: 'Smart video doorbell', type: 'standard' },
      { id: 'smart-lock', label: 'Smart or keypad door lock', type: 'standard' },
      { id: 'entrance-lighting', label: 'Motion-activated entrance lighting', type: 'standard' },
      { id: 'threshold-treatment', label: 'Non-slip step or threshold treatment', type: 'standard' },
      { id: 'entry-voice-control', label: 'Voice-control integration', type: 'standard' },
      { id: 'entry-handrail', label: 'Entry handrail where steps exist', type: 'standard' },
    ],
    conditionalComponents: [
      { id: 'small-threshold-ramp', label: 'Small threshold ramp', type: 'conditional' },
    ],
    quotationOnlyComponents: [
      {
        id: 'modular-access-ramp',
        label: 'Modular access ramp',
        type: 'quotation-only',
        customerNote: 'Requires measurement before final pricing.',
      },
    ],
  },
  {
    id: 'home-movement-safe',
    name: 'CasaMia Home Movement Safe',
    shortName: 'Movement',
    outcome: 'Reduce daily trip risks across halls, living areas and stairs.',
    salesUnit: 'Per household',
    standardComponents: [
      { id: 'hall-motion-lighting', label: 'Motion-activated hallway lighting', type: 'standard' },
      { id: 'voice-lighting', label: 'Voice-controlled lights', type: 'standard' },
      { id: 'voice-devices', label: 'Voice control for selected devices', type: 'standard' },
      { id: 'smart-plugs', label: 'Selected smart plugs', type: 'standard' },
      { id: 'rug-securing', label: 'Loose-rug securing or removal', type: 'standard' },
      { id: 'cable-management', label: 'Cable management', type: 'standard' },
      { id: 'level-contrast', label: 'High-contrast step or level-change markings', type: 'standard' },
      { id: 'stand-assist', label: 'Stand-assist handle for an existing sofa or chair', type: 'standard' },
      { id: 'hallway-rail', label: 'Hallway support rail where required', type: 'standard' },
    ],
    conditionalComponents: [
      { id: 'stair-treads', label: 'Non-slip stair treads', type: 'conditional' },
      { id: 'stair-handrails', label: 'Staircase handrails', type: 'conditional' },
      { id: 'stair-edge-markings', label: 'High-contrast stair-edge markings', type: 'conditional' },
      { id: 'stair-lighting', label: 'Motion-activated stair lighting', type: 'conditional' },
    ],
    quotationOnlyComponents: [],
  },
  {
    id: 'kitchen-independence',
    name: 'CasaMia Kitchen Independence',
    shortName: 'Kitchen',
    outcome: 'Make cooking and preparation easier, safer and less tiring.',
    salesUnit: 'Per kitchen',
    quantityKey: 'kitchens',
    standardComponents: [
      { id: 'prep-mats', label: 'Non-slip preparation mats', type: 'standard' },
      { id: 'easy-grip-tools', label: 'Ergonomic easy-grip utensils', type: 'standard' },
      { id: 'openers', label: 'Jar, bottle and automatic can openers', type: 'standard' },
      { id: 'lightweight-cookware', label: 'Lightweight cookware', type: 'standard' },
      { id: 'anti-fatigue-mat', label: 'Anti-fatigue non-slip floor mat', type: 'standard' },
      { id: 'worktop-lighting', label: 'Improved worktop lighting', type: 'standard' },
      { id: 'kitchen-voice-lighting', label: 'Voice-controlled lighting and timers', type: 'standard' },
      { id: 'kitchen-smart-plugs', label: 'Selected smart plugs', type: 'standard' },
      { id: 'water-leak-sensor', label: 'Water-leak sensor', type: 'standard' },
      { id: 'gas-co-sensor', label: 'Gas or carbon-monoxide sensor where applicable', type: 'standard' },
    ],
    conditionalComponents: [
      { id: 'pull-down-shelf', label: 'Pull-down upper-cabinet shelf', type: 'conditional' },
      { id: 'stove-shutoff', label: 'Automatic stove shut-off', type: 'conditional' },
      { id: 'touchless-faucet', label: 'Touchless faucet', type: 'conditional' },
    ],
    quotationOnlyComponents: [],
  },
  {
    id: 'bedroom-night-safe',
    name: 'CasaMia Bedroom & Night Safe',
    shortName: 'Bedroom',
    outcome: 'Support safer nights, easier bed transfers and calmer routines.',
    salesUnit: 'Per bedroom',
    quantityKey: 'bedrooms',
    standardComponents: [
      { id: 'bed-handle', label: 'Bed support handle', type: 'standard' },
      { id: 'under-bed-lighting', label: 'Under-bed motion lighting', type: 'standard' },
      { id: 'nightlights', label: 'Plug-in nightlights', type: 'standard' },
      { id: 'bedside-lamp', label: 'Easy-control bedside lamp', type: 'standard' },
      { id: 'bedroom-cable-management', label: 'Cable management', type: 'standard' },
      { id: 'bedroom-rug-securing', label: 'Rug securing or removal', type: 'standard' },
      { id: 'large-clock', label: 'Large-display clock', type: 'standard' },
      { id: 'bedroom-voice-lighting', label: 'Voice-controlled lighting', type: 'standard' },
      { id: 'bedroom-smart-plugs', label: 'Selected voice-controlled smart plugs', type: 'standard' },
    ],
    conditionalComponents: [
      { id: 'bed-exit-sensor', label: 'Bed-exit sensor', type: 'conditional' },
    ],
    quotationOnlyComponents: [
      { id: 'adjustable-bed', label: 'Adjustable bed', type: 'quotation-only' },
      { id: 'pressure-mattress', label: 'Pressure-relief mattress', type: 'quotation-only' },
    ],
  },
  {
    id: 'bathroom-safe',
    name: 'CasaMia Bathroom Safe',
    shortName: 'Bathroom',
    outcome: 'Improve shower, toilet and wet-floor safety without guesswork.',
    salesUnit: 'Per bathroom',
    quantityKey: 'bathrooms',
    standardComponents: [
      { id: 'fixed-grab-bars', label: 'Structurally anchored grab bars', type: 'standard' },
      { id: 'shower-chair', label: 'Height-adjustable shower chair', type: 'standard' },
      { id: 'raised-toilet-seat', label: 'Raised toilet seat', type: 'standard' },
      { id: 'toilet-support', label: 'Toilet support frame or rail', type: 'standard' },
      { id: 'anti-slip-bathroom', label: 'Anti-slip shower or bath treatment', type: 'standard' },
      { id: 'bathroom-mat', label: 'Low-profile non-slip bathroom mat', type: 'standard' },
      { id: 'bathroom-nightlight', label: 'Motion-activated nightlight', type: 'standard' },
      { id: 'bathroom-leak-sensor', label: 'Water-leak sensor', type: 'standard' },
      { id: 'temperature-monitor', label: 'Water-temperature monitor', type: 'standard' },
      { id: 'tap-adaptations', label: 'Easy-turn tap adaptations', type: 'standard' },
    ],
    conditionalComponents: [],
    quotationOnlyComponents: [
      { id: 'shower-conversion', label: 'Major shower conversion or walk-in bath', type: 'quotation-only' },
    ],
  },
  {
    id: 'connected-safety-vyva',
    name: 'CasaMia Connected Safety + VYVA',
    shortName: 'Connected Safety',
    outcome: 'Add family alerts, emergency support and simple connected routines.',
    salesUnit: 'Per household',
    standardComponents: [
      { id: 'vyva-app', label: 'VYVA app', type: 'standard' },
      { id: 'voice-hub', label: 'Smart speaker or voice hub', type: 'standard' },
      { id: 'emergency-button', label: 'Waterproof wearable emergency call button', type: 'standard' },
      { id: 'communication-hub', label: 'Two-way communication hub', type: 'standard' },
      { id: 'fall-detection', label: 'Automatic fall detection', type: 'standard' },
      { id: 'family-alert-setup', label: 'Family alert setup', type: 'standard' },
      { id: 'escalation-config', label: 'Emergency escalation configuration', type: 'standard' },
      { id: 'onboarding', label: 'Resident and family onboarding', type: 'standard' },
    ],
    conditionalComponents: [
      { id: 'monitoring-plan', label: 'Professional response-centre monitoring', type: 'monthly' },
      { id: 'gps-protection', label: 'Mobile or GPS protection outside the home', type: 'monthly' },
    ],
    quotationOnlyComponents: [],
  },
]

export const configuratorPricing: ConfiguratorPricing = {
  currency: 'EUR',
  vatRate: 0.21,
  depositAmount: 99,
  packagePrices: {
    'entrance-safe': 890,
    'home-movement-safe': 1290,
    'kitchen-independence': 980,
    'bedroom-night-safe': 760,
    'bathroom-safe': 1190,
    'connected-safety-vyva': 690,
  },
  staircaseModulePrice: 540,
  componentPrices: {
    'small-threshold-ramp': 180,
    'pull-down-shelf': 420,
    'stove-shutoff': 360,
    'touchless-faucet': 260,
    'bed-exit-sensor': 180,
  },
  recurringPrices: {
    'monitoring-plan': 29,
    'gps-protection': 19,
  },
}

export const configuratorQuestions: WizardQuestion[] = [
  {
    id: 'voice-control-scope',
    packageId: 'home-movement-safe',
    label: 'What should voice control help with?',
    type: 'single',
    options: [
      { value: 'lighting', label: 'Lighting only' },
      { value: 'lighting-tv-devices', label: 'Lighting, TV and selected devices' },
    ],
  },
  {
    id: 'connected-alerts',
    packageId: 'connected-safety-vyva',
    label: 'Who should receive alerts?',
    type: 'multi',
    options: [
      { value: 'family', label: 'Family' },
      { value: 'caregiver', label: 'Caregiver' },
      { value: 'monitoring', label: 'Professional response centre' },
    ],
  },
]

export const conditionalRules: ConditionalRule[] = [
  {
    id: 'staircase-module',
    packageId: 'home-movement-safe',
    answerKey: 'property.hasInternalStairs',
    matches: 'yes',
    addComponentIds: ['stair-treads', 'stair-handrails', 'stair-edge-markings', 'stair-lighting'],
    priceKey: 'staircaseModulePrice',
  },
  {
    id: 'entrance-small-ramp',
    packageId: 'entrance-safe',
    answerKey: 'entrance.ramp',
    matches: 'small-threshold-ramp',
    addComponentIds: ['small-threshold-ramp'],
    priceKey: 'small-threshold-ramp',
  },
  {
    id: 'entrance-modular-ramp',
    packageId: 'entrance-safe',
    answerKey: 'entrance.ramp',
    matches: ['modular-access-ramp', 'unsure'],
    quoteOnlyComponentIds: ['modular-access-ramp'],
    siteConfirmation: 'Ramp length and gradient must be measured before final pricing.',
  },
  {
    id: 'kitchen-upper-cabinet',
    packageId: 'kitchen-independence',
    answerKey: 'kitchen.upperCabinets',
    matches: 'yes',
    addComponentIds: ['pull-down-shelf'],
    priceKey: 'pull-down-shelf',
    siteConfirmation: 'Cabinet hardware requires compatibility confirmation.',
  },
  {
    id: 'kitchen-stove-shutoff',
    packageId: 'kitchen-independence',
    answerKey: 'kitchen.stoveShutoff',
    matches: 'yes',
    addComponentIds: ['stove-shutoff'],
    priceKey: 'stove-shutoff',
  },
  {
    id: 'kitchen-touchless-faucet',
    packageId: 'kitchen-independence',
    answerKey: 'kitchen.touchlessFaucet',
    matches: 'yes',
    addComponentIds: ['touchless-faucet'],
    priceKey: 'touchless-faucet',
    siteConfirmation: 'Tap compatibility must be checked before installation.',
  },
  {
    id: 'bedroom-caregiver-alert',
    packageId: 'bedroom-night-safe',
    answerKey: 'bedroom.caregiverAlerts',
    matches: 'yes',
    addComponentIds: ['bed-exit-sensor'],
    priceKey: 'bed-exit-sensor',
  },
  {
    id: 'bedroom-adjustable-bed',
    packageId: 'bedroom-night-safe',
    answerKey: 'bedroom.adjustableBed',
    matches: 'yes',
    quoteOnlyComponentIds: ['adjustable-bed'],
  },
  {
    id: 'bedroom-pressure-mattress',
    packageId: 'bedroom-night-safe',
    answerKey: 'bedroom.pressureMattress',
    matches: 'yes',
    quoteOnlyComponentIds: ['pressure-mattress'],
  },
  {
    id: 'bathroom-wall-confirmation',
    packageId: 'bathroom-safe',
    answerKey: 'bathroom.wallType',
    matches: ['unsure', 'lightweight'],
    siteConfirmation: 'Wall structure must be confirmed before grab bars are fixed.',
  },
  {
    id: 'connected-monitoring',
    packageId: 'connected-safety-vyva',
    answerKey: 'connected-alerts',
    matches: 'monitoring',
    addComponentIds: ['monitoring-plan'],
    recurringPriceKey: 'monitoring-plan',
  },
  {
    id: 'connected-gps',
    packageId: 'connected-safety-vyva',
    answerKey: 'connected.outsideProtection',
    matches: 'yes',
    addComponentIds: ['gps-protection'],
    recurringPriceKey: 'gps-protection',
  },
]

export const editablePricingNotice =
  'Placeholder pricing for configuration only. Final commercial prices, VAT treatment and grant handling require CasaMia confirmation.'

export function getPackageById(packageId: PackageId) {
  return casaMiaPackages.find((item) => item.id === packageId)
}
