import type { MasterServiceCatalogue } from '../types/serviceCatalogue.ts'

const now = '2026-07-23T00:00:00.000Z'

export const masterServiceCatalogue: MasterServiceCatalogue = {
  version: '1.0.0',
  updatedAt: now,
  rooms: [
    { id: 'bathroom', slug: 'bathroom', name: { en: 'Bathroom', es: 'Baño' }, active: true, sortOrder: 10 },
    { id: 'bedroom', slug: 'bedroom', name: { en: 'Bedroom', es: 'Dormitorio' }, active: true, sortOrder: 20 },
    { id: 'kitchen', slug: 'kitchen', name: { en: 'Kitchen', es: 'Cocina' }, active: true, sortOrder: 30 },
  ],
  sections: [
    {
      id: 'home-safety-package',
      slug: 'home-safety-package',
      name: { en: 'Home Safety Package', es: 'Paquete de seguridad del hogar' },
      description: {
        en: 'Physical improvements that make daily routines safer and easier.',
        es: 'Mejoras físicas para que las rutinas diarias sean más seguras y sencillas.',
      },
      active: true,
      sortOrder: 10,
    },
    {
      id: 'connected-room',
      slug: 'connected-room',
      name: { en: 'Connected Room', es: 'Estancia conectada' },
      description: {
        en: 'Configured technology experiences, not loose devices.',
        es: 'Experiencias tecnológicas configuradas, no dispositivos sueltos.',
      },
      active: true,
      sortOrder: 20,
    },
    {
      id: 'optional-adaptations',
      slug: 'optional-adaptations',
      name: { en: 'Optional Adaptations', es: 'Adaptaciones opcionales' },
      description: {
        en: 'Bespoke works requiring assessment, measurements, or quotation.',
        es: 'Trabajos a medida que requieren evaluación, medición o presupuesto.',
      },
      active: true,
      sortOrder: 30,
    },
  ],
  packages: [
    packageRecord('bathroom-home-safety-package', 'bathroom', 'home-safety-package', {
      en: 'Bathroom Home Safety Package',
      es: 'Paquete de seguridad para baño',
    }, 'Bathroom Home Safety Package', 10, false, {
      shortDescription: {
        en: 'Thoughtful improvements that make bathing, toilet use, and movement around the bathroom safer and easier, while preserving the look and feel of the home.',
        es: 'Mejoras cuidadas que hacen que bañarse, usar el inodoro y moverse por el baño sea más seguro y sencillo, conservando el aspecto y la sensación del hogar.',
      },
      customerBenefit: {
        en: 'A safer bathroom plan without making the home feel clinical.',
        es: 'Un plan de baño más seguro sin que la vivienda parezca clínica.',
      },
    }),
    packageRecord('bathroom-connected-room', 'bathroom', 'connected-room', {
      en: 'Casamia Connected Bathroom',
      es: 'Baño conectado Casamia',
    }, 'Casamia Connected Bathroom', 20),
    packageRecord('bathroom-optional-adaptations', 'bathroom', 'optional-adaptations', {
      en: 'Bathroom Optional Adaptations',
      es: 'Adaptaciones opcionales de baño',
    }, 'Bathroom Optional Adaptations', 30, true),
    packageRecord('bedroom-home-safety-package', 'bedroom', 'home-safety-package', {
      en: 'Bedroom Home Safety Package',
      es: 'Paquete de seguridad para dormitorio',
    }, 'Bedroom Home Safety Package', 40, false, {
      shortDescription: {
        en: 'Thoughtful improvements that make getting in and out of bed, moving around the bedroom, and maintaining independence safer and more comfortable.',
        es: 'Mejoras cuidadas que hacen que entrar y salir de la cama, moverse por el dormitorio y mantener la independencia sea más seguro y cómodo.',
      },
      customerBenefit: {
        en: 'A calmer, safer bedroom for night-time movement, transfers and daily independence.',
        es: 'Un dormitorio más tranquilo y seguro para moverse de noche, hacer transferencias y mantener la independencia diaria.',
      },
    }),
    packageRecord('bedroom-connected-room', 'bedroom', 'connected-room', {
      en: 'Casamia Connected Bedroom',
      es: 'Dormitorio conectado Casamia',
    }, 'Casamia Connected Bedroom', 50, false, {
      shortDescription: {
        en: 'A tailored smart-home setup centred around a configured smart speaker and compatible devices.',
        es: 'Una configuración smart-home a medida centrada en un altavoz inteligente configurado y dispositivos compatibles.',
      },
      customerBenefit: {
        en: 'Simple voice, reminder and reassurance experiences without turning the bedroom into a device showroom.',
        es: 'Experiencias sencillas de voz, recordatorios y tranquilidad sin convertir el dormitorio en un escaparate de dispositivos.',
      },
    }),
    packageRecord('bedroom-optional-adaptations', 'bedroom', 'optional-adaptations', {
      en: 'Bedroom Optional Adaptations',
      es: 'Adaptaciones opcionales de dormitorio',
    }, 'Bedroom Optional Adaptations', 60, true),
    packageRecord('kitchen-home-safety-package', 'kitchen', 'home-safety-package', {
      en: 'Kitchen Home Safety Package',
      es: 'Paquete de seguridad para cocina',
    }, 'Kitchen Home Safety Package', 70, false, {
      shortDescription: {
        en: 'Thoughtful improvements that make cooking, preparing meals, and moving around the kitchen safer and easier.',
        es: 'Mejoras cuidadas que hacen que cocinar, preparar comidas y moverse por la cocina sea más seguro y sencillo.',
      },
      customerBenefit: {
        en: 'A safer, easier kitchen plan that supports independence without turning the room into a product showroom.',
        es: 'Un plan de cocina más seguro y sencillo que apoya la independencia sin convertir la estancia en un escaparate de productos.',
      },
    }),
    packageRecord('kitchen-connected-room', 'kitchen', 'connected-room', {
      en: 'Casamia Connected Kitchen',
      es: 'Cocina conectada Casamia',
    }, 'Casamia Connected Kitchen', 80, false, {
      shortDescription: {
        en: 'A smart kitchen setup centred around a configured smart speaker and compatible devices.',
        es: 'Una cocina inteligente centrada en un altavoz configurado y dispositivos compatibles.',
      },
      customerBenefit: {
        en: 'Voice, reminders and family reassurance configured around real kitchen routines.',
        es: 'Voz, recordatorios y tranquilidad familiar configurados alrededor de rutinas reales de cocina.',
      },
    }),
    packageRecord('kitchen-optional-adaptations', 'kitchen', 'optional-adaptations', {
      en: 'Kitchen Optional Adaptations',
      es: 'Adaptaciones opcionales de cocina',
    }, 'Kitchen Optional Adaptations', 90, true),
  ],
  outcomes: [
    outcome('bathroom-safer-bathing', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Safer Bathing', 'Baño y ducha más seguros', 'Bathing safety', 'Making bathing easier, safer, and more comfortable.', 'Hace que bañarse sea más fácil, seguro y cómodo.', 'Improve support, seating, grip and lower-entry access where suitable.', 'Mejora el apoyo, el asiento, el agarre y el acceso bajo cuando sea adecuado.', 'essential', ['bathroom'], 10, { legacyId: 'bathroom-folding-shower-seat', grantEligible: true }),
    outcome('bathroom-safer-toilet-transfers', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Safer Toilet Transfers', 'Transferencias al inodoro más seguras', 'Toilet transfers', 'Helping residents sit down and stand up with greater stability.', 'Ayuda a sentarse y levantarse del inodoro con mayor estabilidad.', 'Add the right support around the toilet for safer daily use.', 'Añade el apoyo adecuado alrededor del inodoro para un uso diario más seguro.', 'essential', ['bathroom'], 20, { legacyId: 'bathroom-raised-toilet-seat', grantEligible: true }),
    outcome('bathroom-slip-prevention', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Slip Prevention', 'Prevención de resbalones', 'Wet-floor safety', 'Reducing common slipping and tripping hazards.', 'Reduce riesgos habituales de resbalones y tropiezos.', 'Improve grip and transitions where wet floors create risk.', 'Mejora el agarre y las transiciones donde los suelos mojados crean riesgo.', 'essential', ['bathroom'], 30, { legacyId: 'bathroom-anti-slip-floor-treatment', grantEligible: true }),
    outcome('bathroom-improved-visibility', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Improved Bathroom Visibility', 'Mejor visibilidad en el baño', 'Bathroom lighting', 'Making the bathroom easier to navigate during the day and at night.', 'Hace que el baño sea más fácil de recorrer durante el día y por la noche.', 'Make switches, edges, water and support points easier to see.', 'Hace más visibles interruptores, bordes, agua y puntos de apoyo.', 'essential', ['bathroom', 'lighting'], 40, { legacyId: 'bathroom-improved-lighting', grantEligible: true }),
    outcome('bathroom-easier-tap-control', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Easier Water Controls', 'Controles de agua más fáciles', 'Water control', 'Making taps and shower controls easier to use with reduced grip strength or dexterity.', 'Hace que grifos y controles de ducha sean más fáciles de usar con menos fuerza o destreza.', 'Simplify washing and showering with controls that are easier to reach and operate.', 'Simplifica el aseo y la ducha con controles más fáciles de alcanzar y usar.', 'essential', ['bathroom'], 50, { legacyId: 'bathroom-lever-mixer-tap' }),
    outcome('bathroom-temperature-safety', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Temperature Safety', 'Seguridad de temperatura', 'Water safety', 'Helping reduce the risk of accidental scalding.', 'Ayuda a reducir el riesgo de quemaduras accidentales.', 'Keep hot water use within a safer range where suitable.', 'Ayuda a mantener el agua caliente en un rango más seguro cuando sea adecuado.', 'essential', ['bathroom'], 60, { legacyId: 'bathroom-thermostatic-valve' }),
    outcome('bathroom-safer-access', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Safer Bathroom Access', 'Acceso al baño más seguro', 'Access', 'Making it easier and safer to enter, exit, and use the bathroom door.', 'Hace que sea más fácil y seguro entrar, salir y usar la puerta del baño.', 'Reduce friction around the bathroom entrance, handle and privacy lock.', 'Reduce dificultades en la entrada del baño, el tirador y el cierre de privacidad.', 'essential', ['bathroom', 'entrance'], 70, { legacyId: 'bathroom-threshold-removal', grantEligible: true }),
    outcome('bathroom-safety-monitoring', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Bathroom Safety Monitoring', 'Monitorización de seguridad del baño', 'Bathroom risk alerts', 'Providing early warning of selected bathroom risks.', 'Proporciona aviso temprano de determinados riesgos del baño.', 'Send selected alerts to the resident, family member or carer where compatible.', 'Envía avisos seleccionados al residente, familiar o cuidador cuando sea compatible.', 'recommended', ['bathroom', 'smart-safety'], 80, { legacyId: 'bathroom-safety-monitoring', technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('bathroom-connected-guidance', 'bathroom', 'connected-room', 'bathroom-connected-room', 'Automatic Bathroom Guidance', 'Guía automática en el baño', 'Connected bathroom', 'Motion-triggered guidance for safer low-light bathroom routines.', 'Guía activada por movimiento para rutinas de baño con poca luz.', 'Help the bathroom respond quietly when someone enters at night.', 'Ayuda a que el baño responda discretamente por la noche.', 'recommended', ['bathroom', 'lighting', 'smart-safety'], 85, { legacyId: 'bathroom-motion-lighting', technologyEnabled: true }),
    outcome('bathroom-bathtub-step-through', 'bathroom', 'optional-adaptations', 'bathroom-optional-adaptations', 'Bathtub Step-through Conversion', 'Conversión de bañera con acceso bajo', 'Bath adaptation', 'A specialist conversion to reduce the step over the bath edge.', 'Conversión especializada para reducir el paso sobre el borde de la bañera.', 'Make bath access easier without replacing the whole room.', 'Facilita el acceso a la bañera sin sustituir todo el baño.', 'optional', ['bathroom'], 90, { legacyId: 'bathroom-tub-cutout', quoteOnly: true, grantEligible: true }),
    outcome('bathroom-wider-doorway', 'bathroom', 'optional-adaptations', 'bathroom-optional-adaptations', 'Wider Bathroom Doorway', 'Puerta de baño más ancha', 'Door access', 'A measured doorway adaptation where walking aids or wheelchairs need more clearance.', 'Adaptación medida de puerta cuando ayudas de movilidad o sillas necesitan más espacio.', 'Improve access when the current doorway is too tight.', 'Mejora el acceso cuando la puerta actual resulta estrecha.', 'optional', ['bathroom', 'entrance'], 100, { legacyId: 'bathroom-wider-doorway', quoteOnly: true, grantEligible: true }),
    outcome('bathroom-vertical-support', 'bathroom', 'optional-adaptations', 'bathroom-optional-adaptations', 'Vertical Support Rail', 'Barra de apoyo vertical', 'Transfer support', 'Additional vertical support where transfers need a stronger plan.', 'Apoyo vertical adicional cuando las transferencias requieren una solución más robusta.', 'Add support where standard rails are not enough.', 'Añade apoyo donde las barras estándar no bastan.', 'optional', ['bathroom'], 110, { legacyId: 'bathroom-vertical-support-rail', quoteOnly: true, grantEligible: true }),
    outcome('bedroom-safer-lighting', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Safer Bedroom Lighting', 'Iluminación de dormitorio más segura', 'Bedroom lighting', 'Improving visibility throughout the bedroom, particularly during the night.', 'Mejora la visibilidad en todo el dormitorio, especialmente durante la noche.', 'Make it easier to see before getting out of bed and moving around at night.', 'Facilita ver antes de levantarse y moverse por la noche.', 'essential', ['bedroom', 'lighting'], 120, { legacyId: 'bedroom-underbed-lighting', grantEligible: true }),
    outcome('bedroom-easier-bed-transfers', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Easier Bed Transfers', 'Transferencias de cama más fáciles', 'Bed transfers', 'Making it easier and safer to get into and out of bed.', 'Hace que entrar y salir de la cama sea más fácil y seguro.', 'Improve support, bed height and positioning around one of the most important daily transfer points.', 'Mejora el apoyo, la altura y la posición de la cama en una transferencia diaria clave.', 'essential', ['bedroom'], 130, { legacyId: 'bedroom-bed-support', grantEligible: true }),
    outcome('bedroom-safer-walking-routes', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Safer Walking Routes', 'Rutas de paso más seguras', 'Bedroom routes', 'Reducing common trip hazards throughout the bedroom.', 'Reduce riesgos habituales de tropiezo en todo el dormitorio.', 'Keep the route between the bed and the door clearer and easier to use.', 'Mantiene más despejada y fácil de usar la ruta entre la cama y la puerta.', 'essential', ['bedroom', 'living-room'], 140, { legacyId: 'bedroom-night-route', grantEligible: true }),
    outcome('bedroom-slip-resistance', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Slip-Resistance Improvements', 'Mejoras antideslizantes', 'Floor safety', 'Reducing the likelihood of slips within the bedroom.', 'Reduce la probabilidad de resbalones dentro del dormitorio.', 'Improve floor grip and secure floor coverings where needed.', 'Mejora el agarre del suelo y asegura revestimientos cuando sea necesario.', 'essential', ['bedroom'], 150, { grantEligible: true }),
    outcome('bedroom-fire-safety', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Fire Safety', 'Seguridad contra incendios', 'Fire safety', 'Helping protect the bedroom through early fire detection.', 'Ayuda a proteger el dormitorio mediante detección temprana de incendios.', 'Support faster awareness if smoke is detected.', 'Favorece una alerta más rápida si se detecta humo.', 'essential', ['bedroom', 'smart-safety'], 160),
    outcome('bedroom-voice-assistance', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Voice Assistance', 'Asistencia por voz', 'Connected bedroom', 'Voice support for lights, calls, reminders and simple help requests.', 'Apoyo por voz para luces, llamadas, recordatorios y peticiones sencillas.', 'Make daily routines easier without needing a complex interface.', 'Facilita rutinas sin interfaces complicadas.', 'recommended', ['bedroom', 'smart-safety'], 190, { technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-smart-lighting', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Smart Lighting', 'Iluminación inteligente', 'Connected bedroom', 'Configured lighting scenes, voice control and automatic night guidance.', 'Escenas de luz, control por voz y guía nocturna automática configuradas.', 'Let the room adapt to night-time movement and simple spoken requests.', 'Permite que la estancia se adapte al movimiento nocturno y a peticiones por voz.', 'recommended', ['bedroom', 'lighting', 'smart-safety'], 200, { technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-family-reassurance', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Family Reassurance', 'Tranquilidad familiar', 'Connected bedroom', 'Carefully configured family or carer notifications where appropriate and consented.', 'Avisos para familiares o cuidadores configurados cuidadosamente cuando proceda y haya consentimiento.', 'Help family understand routines without intrusive monitoring.', 'Ayuda a la familia a entender rutinas sin vigilancia invasiva.', 'recommended', ['bedroom', 'smart-safety'], 210, { legacyId: 'bedroom-bed-exit-sensor', technologyEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-daily-living-support', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Daily Living Support', 'Apoyo a rutinas diarias', 'Connected bedroom', 'Medication, appointment and morning/evening routine prompts.', 'Recordatorios de medicación, citas y rutinas de mañana/noche.', 'Support independence with gentle prompts.', 'Apoya la independencia con avisos amables.', 'recommended', ['bedroom', 'smart-safety'], 220, { technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-connected-safety', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Night-time Safety Alerts', 'Alertas nocturnas de seguridad', 'Connected bedroom', 'Compatible connected alerts selected for the resident and home.', 'Alertas conectadas compatibles seleccionadas para la persona y la vivienda.', 'Keep safety technology simple and coordinated.', 'Mantiene la tecnología de seguridad sencilla y coordinada.', 'recommended', ['bedroom', 'smart-safety'], 230, { technologyEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-emergency-support', 'bedroom', 'optional-adaptations', 'bedroom-optional-adaptations', 'Emergency Support', 'Apoyo de emergencia', 'Emergency access', 'A reviewed emergency support route for the bedroom.', 'Una vía de apoyo de emergencia revisada para el dormitorio.', 'Give the resident and family a clearer way to call for help from the bedroom.', 'Da al residente y la familia una vía más clara para pedir ayuda desde el dormitorio.', 'optional', ['bedroom', 'smart-safety'], 235, { grantEligible: true, quoteOnly: true, requiresCompatibilityCheck: true, technologyEnabled: true }),
    ...[
      ['bedroom-accessible-wardrobe', 'Accessible Wardrobe Adaptation', 'Armario más accesible'],
      ['bedroom-advanced-bed-transfer', 'Advanced Bed Transfer Solution', 'Solución avanzada de transferencia de cama'],
      ['bedroom-electric-adjustable-bed', 'Electric Adjustable Bed', 'Cama eléctrica ajustable'],
      ['bedroom-bed-exit-safety-system', 'Bed Exit Safety System', 'Sistema de seguridad al salir de la cama'],
      ['bedroom-automated-curtains', 'Automated Curtains or Blinds', 'Cortinas o persianas automatizadas'],
      ['bedroom-bathroom-safety-route', 'Bedroom-to-Bathroom Safety Route', 'Ruta segura del dormitorio al baño'],
      ['bedroom-specialist-layout', 'Specialist Bedroom Layout Adaptation', 'Adaptación especializada del dormitorio'],
      ['bedroom-door-accessibility', 'Bedroom Door Accessibility Adaptation', 'Adaptación de accesibilidad de puerta'],
      ['bedroom-dementia-support', 'Dementia-Support Bedroom Adaptation', 'Dormitorio adaptado para apoyo cognitivo'],
    ].map(([id, en, es], index) =>
      outcome(id, 'bedroom', 'optional-adaptations', 'bedroom-optional-adaptations', en, es, 'Optional bedroom adaptation', 'A bespoke bedroom adaptation reviewed after assessment.', 'Adaptación de dormitorio a medida revisada tras evaluación.', 'Tailor the bedroom around a specific need.', 'Adapta el dormitorio a una necesidad concreta.', 'optional', ['bedroom'], 240 + index, {
        legacyId: id === 'bedroom-electric-adjustable-bed' ? 'bedroom-adjustable-bed' : undefined,
        quoteOnly: true,
        grantEligible: true,
        requiresCompatibilityCheck: id.includes('automated') || id.includes('system'),
        technologyEnabled: id.includes('automated') || id.includes('system'),
      }),
    ),
    outcome('kitchen-safer-food-preparation', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Safer Food Preparation', 'Preparación de alimentos más segura', 'Food preparation', 'Making everyday food preparation easier and reducing strain on the hands and joints.', 'Hace que la preparación diaria de comidas sea más sencilla y reduce el esfuerzo en manos y articulaciones.', 'Support safer chopping, pouring, opening and standing at the main preparation area.', 'Apoya tareas más seguras al cortar, servir, abrir envases y permanecer de pie en la zona principal de preparación.', 'essential', ['kitchen'], 300, { legacyId: 'kitchen-easy-grip-tools', grantEligible: true }),
    outcome('kitchen-safer-cooking', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Safer Cooking', 'Cocina más segura', 'Cooking safety', 'Reducing everyday cooking risks while maintaining independence.', 'Reduce riesgos cotidianos al cocinar manteniendo la independencia.', 'Add selected safeguards around heat, gas and forgotten cooking routines where suitable.', 'Añade protecciones seleccionadas frente al calor, gas y rutinas olvidadas cuando sea adecuado.', 'essential', ['kitchen', 'smart-safety'], 310, { legacyId: 'kitchen-stove-shutoff', grantEligible: true, technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('kitchen-improved-lighting', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Improved Kitchen Lighting', 'Mejor iluminación en la cocina', 'Kitchen lighting', 'Improving visibility across the kitchen.', 'Mejora la visibilidad en toda la cocina.', 'Make preparation, cooking, spills and edges easier to see.', 'Hace más visibles la preparación, la cocción, los derrames y los bordes.', 'essential', ['kitchen', 'lighting'], 320, { legacyId: 'kitchen-worktop-lighting', grantEligible: true, technologyEnabled: true }),
    outcome('kitchen-safer-movement', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Safer Kitchen Movement', 'Movimiento más seguro en la cocina', 'Kitchen movement', 'Reducing trip hazards and making movement around the kitchen easier.', 'Reduce riesgos de tropiezo y facilita moverse por la cocina.', 'Create clearer walking routes and safer standing zones around daily routines.', 'Crea recorridos más despejados y zonas de apoyo más seguras alrededor de las rutinas diarias.', 'essential', ['kitchen', 'living-room'], 330, { legacyId: 'kitchen-anti-fatigue-mat', grantEligible: true }),
    outcome('kitchen-easier-storage', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Easier Kitchen Storage', 'Almacenamiento de cocina más fácil', 'Reach and storage', 'Making frequently used kitchen items easier to reach.', 'Hace que los utensilios y alimentos de uso frecuente sean más fáciles de alcanzar.', 'Reduce climbing, stretching and carrying by moving everyday items to safer heights.', 'Reduce subirse, estirarse y cargar peso colocando los objetos diarios a alturas más seguras.', 'essential', ['kitchen'], 340, { grantEligible: true }),
    outcome('kitchen-safety-monitoring', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Kitchen Safety Monitoring', 'Avisos de seguridad en la cocina', 'Kitchen alerts', 'Providing early warning of selected kitchen risks.', 'Proporciona aviso temprano de determinados riesgos en la cocina.', 'Use selected compatible alerts for smoke, water leakage and movement where appropriate.', 'Utiliza avisos compatibles para humo, fuga de agua y movimiento cuando proceda.', 'recommended', ['kitchen', 'smart-safety'], 350, { legacyId: 'kitchen-water-leak-sensor', technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('kitchen-connected-experience', 'kitchen', 'connected-room', 'kitchen-connected-room', 'Connected Kitchen', 'Cocina conectada', 'Connected kitchen', 'A smart kitchen setup centred around a configured smart speaker.', 'Una cocina inteligente centrada en un altavoz configurado.', 'Make cooking routines easier with voice, reminders, lists, calls and selected family notifications.', 'Facilita las rutinas de cocina con voz, recordatorios, listas, llamadas y avisos familiares seleccionados.', 'recommended', ['kitchen', 'smart-safety'], 360, { legacyId: 'kitchen-voice-lighting-timers', technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('kitchen-pull-out-pantry-storage', 'kitchen', 'optional-adaptations', 'kitchen-optional-adaptations', 'Pull-Out Pantry Storage', 'Almacenamiento extraíble de despensa', 'Optional kitchen adaptation', 'A measured storage adaptation that brings cupboard contents into easier reach.', 'Adaptación medida de almacenamiento que acerca el contenido de los armarios.', 'Reduce reaching and unsafe stool use where the existing cabinetry allows it.', 'Reduce estirarse y usar taburetes inseguros cuando los muebles existentes lo permiten.', 'optional', ['kitchen'], 370, { legacyId: 'kitchen-pull-down-shelf', quoteOnly: true, grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('kitchen-wider-doorway', 'kitchen', 'optional-adaptations', 'kitchen-optional-adaptations', 'Wider Kitchen Doorway', 'Puerta de cocina más ancha', 'Optional kitchen adaptation', 'A measured doorway adaptation where mobility aids need more clearance.', 'Adaptación medida de puerta cuando las ayudas de movilidad necesitan más espacio.', 'Improve kitchen access when the current doorway restricts safe movement.', 'Mejora el acceso a la cocina cuando la puerta actual limita el movimiento seguro.', 'optional', ['kitchen', 'entrance'], 380, { quoteOnly: true, grantEligible: true }),
  ],
  capabilities: [
    capability('bedside-lighting', 'Bedside lighting', true),
    capability('low-level-night-lighting', 'Low-level night lighting', true),
    capability('motion-activated-lighting', 'Motion-activated lighting', true, true),
    capability('easy-reach-light-controls', 'Easy-reach lighting controls', true),
    capability('bed-height-optimisation', 'Bed height optimisation'),
    capability('transfer-clearance', 'Transfer clearance'),
    capability('discreet-transfer-support', 'Discreet transfer support'),
    capability('furniture-repositioning', 'Furniture repositioning'),
    capability('loose-rug-securing', 'Loose rug removal or securing'),
    capability('cable-management', 'Cable management'),
    capability('accessible-storage-arrangement', 'Accessible storage arrangement'),
    capability('emergency-call-access', 'Emergency call access', true, true),
    capability('wearable-emergency-support', 'Wearable emergency support', true, true),
    capability('bedside-emergency-assistance', 'Bedside emergency assistance', true, true),
    capability('smoke-alerting', 'Smoke detection and alerting', true, true),
    capability('smart-speaker-setup', 'Smart speaker setup', true, true),
    capability('voice-controlled-lighting', 'Voice-controlled lighting', true, true),
    capability('hands-free-calling', 'Hands-free phone calls', true, true),
    capability('routine-reminders', 'Medication and routine reminders', true, true),
    capability('appointment-reminders', 'Appointment reminders', true, true),
    capability('family-carer-notifications', 'Family or carer notifications', true, true),
    capability('night-time-safety-alerts', 'Night-time safety alerts', true, true),
    capability('movement-reassurance', 'Movement reassurance', true, true),
    capability('automatic-jar-opening', 'Automatic jar opening support'),
    capability('easy-grip-kitchen-tools', 'Easy-grip kitchen utensils'),
    capability('non-slip-chopping-support', 'Non-slip chopping support'),
    capability('easy-pour-kettle-support', 'Easy-pour kettle support'),
    capability('anti-fatigue-standing-zone', 'Anti-fatigue standing zone'),
    capability('safer-hob-control', 'Safer hob control', true, true),
    capability('automatic-gas-shutoff', 'Automatic gas shut-off', true, true),
    capability('kitchen-task-lighting', 'Kitchen task lighting', true, true),
    capability('kitchen-circulation-space', 'Improved kitchen circulation space'),
    capability('kitchen-storage-organisation', 'Frequently used items organised within easy reach'),
    capability('waist-height-storage', 'Frequently used items relocated to waist height'),
    capability('kitchen-motion-alerting', 'Kitchen motion detection alerts', true, true),
    capability('voice-cooking-assistance', 'Voice cooking assistance', true, true),
    capability('shopping-list-management', 'Shopping list management', true, true),
    capability('pull-out-pantry-storage', 'Pull-out pantry storage'),
    capability('wider-kitchen-doorway', 'Wider kitchen doorway'),
    capability('bath-transfer-support', 'Bath and shower transfer support'),
    capability('toilet-transfer-support', 'Toilet transfer support'),
    capability('wet-floor-grip', 'Wet-floor grip'),
    capability('bathroom-task-lighting', 'Bathroom task lighting'),
    capability('easy-see-switches', 'Easier-to-see switches and controls'),
    capability('lever-water-control', 'Lever water control'),
    capability('lever-shower-control', 'Lever shower control'),
    capability('anti-scald-control', 'Anti-scald control'),
    capability('hot-water-temperature-setting', 'Safer hot-water temperature setting'),
    capability('threshold-reduction', 'Threshold reduction'),
    capability('bathroom-door-control', 'Bathroom door hardware and adjustment'),
    capability('lower-entry-bath-access', 'Lower-entry bath access'),
    capability('water-leak-alerting', 'Water leak alerting', true, true),
    capability('resident-phone-alerting', 'Resident phone alerting', true, true),
    capability('nominated-carer-alerting', 'Nominated family or carer alerting', true, true),
    capability('automatic-water-shutoff', 'Automatic water shut-off', true, true),
    capability('specialist-measurement', 'Specialist measurement'),
  ],
  products: [
    product('grab-bar', 'Grab bar', 'hardware', 0.1, true),
    product('folding-shower-seat', 'Folding shower seat', 'hardware', 0.1, true),
    product('raised-toilet-seat', 'Raised toilet seat', 'hardware', 0.1, true),
    product('toilet-support-rail', 'Toilet support rail', 'hardware', 0.1, true),
    product('anti-slip-treatment', 'Anti-slip floor treatment', 'material', 0.21, true),
    product('anti-slip-mat', 'Secure anti-slip bath mat', 'hardware', 0.21, false),
    product('bathroom-led-light', 'Bathroom LED light', 'hardware', 0.21, false),
    product('high-contrast-switch-control', 'Easier-to-see switch or control marking', 'material', 0.21, false),
    product('motion-sensor', 'Motion sensor', 'device', 0.21, false, true),
    product('lever-mixer-tap', 'Lever mixer tap', 'hardware', 0.21, false),
    product('lever-operated-shower-control', 'Lever-operated shower control', 'hardware', 0.21, false),
    product('thermostatic-valve', 'Thermostatic anti-scald valve', 'hardware', 0.21, false),
    product('hot-water-setting-service', 'Safer hot-water temperature setting', 'service', 0.21, false),
    product('low-threshold-transition', 'Low-threshold transition strip', 'material', 0.21, true),
    product('bath-step-through-conversion', 'Bathtub step-through conversion', 'service', 0.21, true),
    product('lever-door-handle', 'Lever door handle', 'hardware', 0.21, false),
    product('easy-release-privacy-lock', 'Easy-release privacy lock', 'hardware', 0.21, false),
    product('door-adjustment-service', 'Bathroom door adjustment', 'service', 0.21, false),
    product('water-leak-sensor', 'Water leak sensor', 'device', 0.21, false, true),
    product('resident-alert-setup', 'Resident phone alert setup', 'service', 0.21, false, true),
    product('carer-alert-setup', 'Family or carer alert setup', 'service', 0.21, false, true),
    product('automatic-water-shutoff-valve', 'Automatic water shut-off valve', 'device', 0.21, false, true),
    product('smart-speaker', 'Smart speaker', 'device', 0.21, false, true),
    product('bedside-light', 'Bedside light', 'hardware', 0.21, false),
    product('low-level-floor-light', 'Low-level floor light', 'hardware', 0.21, false),
    product('bed-support-handle', 'Bed support handle', 'hardware', 0.1, true),
    product('cable-management-kit', 'Cable management kit', 'material', 0.21, false),
    product('storage-reach-kit', 'Storage reach and labelling kit', 'material', 0.21, false),
    product('emergency-call-button', 'Emergency call button', 'device', 0.21, false, true),
    product('wearable-emergency-pendant', 'Wearable emergency pendant', 'device', 0.21, false, true),
    product('bedside-emergency-button', 'Bedside emergency assistance button', 'device', 0.21, false, true),
    product('smoke-detector', 'Smoke detector', 'device', 0.21, false, true),
    product('automatic-jar-opener', 'Automatic jar opener', 'hardware', 0.21, false),
    product('easy-grip-kitchen-utensils', 'Easy-grip kitchen utensils', 'hardware', 0.21, false),
    product('non-slip-chopping-board', 'Non-slip chopping board', 'hardware', 0.21, false),
    product('easy-pour-kettle-tipper', 'Easy-pour kettle or kettle tipper', 'hardware', 0.21, false),
    product('anti-fatigue-kitchen-mat', 'Anti-fatigue kitchen mat', 'hardware', 0.21, false),
    product('induction-hob-automatic-shutoff', 'Induction hob with automatic shut-off', 'device', 0.21, true, true),
    product('automatic-gas-shutoff-system', 'Automatic gas shut-off system', 'device', 0.21, true, true),
    product('kitchen-task-light', 'Kitchen task light', 'hardware', 0.21, false, true),
    product('kitchen-storage-reorganisation-service', 'Kitchen storage reorganisation service', 'service', 0.21, false),
    product('pull-out-pantry-hardware', 'Pull-out pantry hardware', 'hardware', 0.21, true, true),
    product('wider-kitchen-doorway-service', 'Wider kitchen doorway service', 'service', 0.21, true),
  ],
  installationTasks: [
    task('inspect-fixing-surface', 'Inspect fixing surface', 25, 'assessment', true, false),
    task('install-support-rail', 'Install support rail', 45, 'general', true, true),
    task('fit-shower-seat', 'Fit shower seat', 50, 'general', true, true),
    task('apply-anti-slip-treatment', 'Apply anti-slip treatment', 60, 'general', true, false),
    task('fit-water-control', 'Fit safer water control', 55, 'plumbing', true, true),
    task('set-hot-water-temperature', 'Set safer hot-water temperature', 30, 'plumbing', true, false),
    task('reduce-threshold', 'Reduce or mark threshold', 45, 'general', true, true),
    task('fit-door-hardware', 'Fit bathroom door hardware', 45, 'general', true, false),
    task('adjust-bathroom-door', 'Adjust bathroom door resistance', 35, 'general', true, false),
    task('fit-water-leak-sensor', 'Fit and test water leak sensor', 30, 'smart_home', false, false),
    task('configure-bathroom-alerting', 'Configure bathroom alerting', 40, 'smart_home', false, false),
    task('fit-water-shutoff-valve', 'Fit compatible water shut-off valve', 75, 'plumbing', true, true),
    task('configure-motion-lighting', 'Configure motion lighting', 35, 'smart_home', false, false),
    task('pair-smart-speaker', 'Pair and configure smart speaker', 45, 'smart_home', false, false),
    task('test-emergency-contact', 'Test emergency contact flow', 20, 'smart_home', false, false),
    task('configure-bedroom-emergency-support', 'Configure bedroom emergency support', 40, 'smart_home', true, false),
    task('reposition-furniture', 'Reposition furniture', 30, 'general', false, false),
    task('measure-specialist-adaptation', 'Measure specialist adaptation', 45, 'assessment', true, true),
    task('set-up-kitchen-prep-support', 'Set up safer food preparation support', 30, 'general', false, false),
    task('assess-kitchen-cooking-safety', 'Assess kitchen cooking safety', 35, 'assessment', true, false),
    task('configure-kitchen-cooking-safeguard', 'Configure kitchen cooking safeguard', 50, 'smart_home', true, false),
    task('install-kitchen-task-lighting', 'Install kitchen task lighting', 60, 'electrical', true, true),
    task('improve-kitchen-standing-route', 'Improve kitchen standing and walking route', 45, 'general', false, false),
    task('organise-kitchen-storage', 'Organise safer kitchen storage', 35, 'general', false, false),
    task('configure-kitchen-alerting', 'Configure kitchen safety alerting', 45, 'smart_home', false, false),
    task('configure-connected-kitchen', 'Configure connected kitchen routines', 55, 'smart_home', false, false),
    task('fit-pull-out-pantry', 'Fit pull-out pantry storage', 90, 'carpentry', true, true),
    task('measure-kitchen-doorway', 'Measure kitchen doorway adaptation', 45, 'assessment', true, true),
  ],
  relations: [
    ...packageOutcomeRelations(),
    ...outcomeCapabilityRelations(),
    ...capabilityProductRelations(),
    ...capabilityTaskRelations(),
  ],
}

function packageRecord(
  id: string,
  roomId: string,
  section: MasterServiceCatalogue['sections'][number]['id'],
  customerName: { en: string; es: string },
  internalName: string,
  sortOrder: number,
  quote = false,
  copy: {
    shortDescription?: { en: string; es: string }
    customerBenefit?: { en: string; es: string }
  } = {},
): MasterServiceCatalogue['packages'][number] {
  return {
    id,
    slug: id,
    roomId,
    section,
    customerName,
    internalName,
    shortDescription: copy.shortDescription ?? { en: 'A coordinated package of customer outcomes.', es: 'Un paquete coordinado de resultados para el cliente.' },
    customerBenefit: copy.customerBenefit ?? { en: 'One clear plan instead of disconnected products.', es: 'Un plan claro en lugar de productos sueltos.' },
    active: true,
    sortOrder,
    pricingType: quote ? 'quote' : 'from',
    fromPrice: quote ? undefined : 0,
    vatRate: 0.21,
    requiresAssessment: true,
    requiresSiteVisit: quote,
    requiresQuote: quote,
    wizardVisible: true,
    websiteVisible: true,
    proposalVisible: true,
    inspectorVisible: true,
    adminVisible: true,
    version: '1.0.0',
    createdAt: now,
    updatedAt: now,
  }
}

function outcome(
  id: string,
  roomId: MasterServiceCatalogue['rooms'][number]['id'],
  section: MasterServiceCatalogue['sections'][number]['id'],
  packageId: string,
  en: string,
  es: string,
  category: string,
  descEn: string,
  descEs: string,
  benefitEn: string,
  benefitEs: string,
  priority: 'essential' | 'recommended' | 'optional',
  wizardAreas: MasterServiceCatalogue['outcomes'][number]['wizardAreas'],
  sortOrder: number,
  options: {
    grantEligible?: boolean
    legacyId?: string
    quoteOnly?: boolean
    requiresCompatibilityCheck?: boolean
    requiresSmartSpeaker?: boolean
    technologyEnabled?: boolean
    voiceEnabled?: boolean
  } = {},
): MasterServiceCatalogue['outcomes'][number] {
  return {
    id,
    legacyId: options.legacyId,
    slug: id,
    roomId,
    section,
    packageId,
    customerName: { en, es },
    internalName: en,
    category,
    shortDescription: { en: descEn, es: descEs },
    detailedDescription: { en: descEn, es: descEs },
    customerBenefit: { en: benefitEn, es: benefitEs },
    active: true,
    sortOrder,
    priority,
    pricingType: options.quoteOnly ? 'quote' : 'included-in-package',
    vatRate: 0.21,
    requiresAssessment: true,
    requiresMeasurement: options.quoteOnly ?? false,
    requiresSiteVisit: options.quoteOnly ?? false,
    requiresCompatibilityCheck: options.requiresCompatibilityCheck ?? options.requiresSmartSpeaker ?? false,
    requiresQuote: options.quoteOnly ?? false,
    grantEligible: options.grantEligible ?? false,
    technologyEnabled: options.technologyEnabled ?? false,
    voiceEnabled: options.voiceEnabled ?? false,
    requiresSmartSpeaker: options.requiresSmartSpeaker ?? false,
    wizardAreas,
    wizardTags: [roomId, section, priority],
    websiteVisible: true,
    wizardVisible: true,
    proposalVisible: true,
    inspectorVisible: true,
    adminVisible: true,
    version: '1.0.0',
    createdAt: now,
    updatedAt: now,
  }
}

function capability(
  id: string,
  name: string,
  technologyEnabled = false,
  requiresCompatibilityCheck = false,
): MasterServiceCatalogue['capabilities'][number] {
  return {
    id,
    slug: id,
    name,
    description: name,
    active: true,
    technologyEnabled,
    requiresCompatibilityCheck,
    implementationNotes: technologyEnabled ? 'Configure only with compatible devices and consent.' : undefined,
  }
}

function product(
  id: string,
  name: string,
  productType: MasterServiceCatalogue['products'][number]['productType'],
  vatRate: number,
  grantEligible: boolean,
  requiresCompatibilityCheck = false,
): MasterServiceCatalogue['products'][number] {
  return {
    id,
    slug: id,
    name,
    productType,
    internalDescription: name,
    active: true,
    vatRate,
    currency: 'EUR',
    quantityType: 'per_unit',
    stockTracked: productType !== 'service',
    grantEligible,
    installationRequired: true,
    requiresCompatibilityCheck,
    version: '1.0.0',
  }
}

function task(
  id: string,
  name: string,
  estimatedMinutes: number,
  skillType: MasterServiceCatalogue['installationTasks'][number]['skillType'],
  requiresSiteVisit: boolean,
  requiresMeasurement: boolean,
): MasterServiceCatalogue['installationTasks'][number] {
  return {
    id,
    slug: id,
    name,
    description: name,
    active: true,
    estimatedMinutes,
    skillType,
    installerType: skillType === 'assessment' ? 'casamia' : 'partner',
    labourRate: 50,
    requiresSiteVisit,
    requiresMeasurement,
    safetyChecklist: ['Confirm resident needs', 'Check surface and route safety'],
    completionChecklist: ['Test installation', 'Explain use to customer'],
    version: '1.0.0',
  }
}

function relation(type: MasterServiceCatalogue['relations'][number]['type'], fromId: string, toId: string, sortOrder: number, required = true) {
  return {
    id: `${type}-${fromId}-${toId}`,
    type,
    fromId,
    toId,
    required,
    defaultIncluded: required,
    optionalUpgrade: !required,
    minimumQuantity: required ? 1 : 0,
    sortOrder,
  }
}

function packageOutcomeRelations() {
  return getMasterServiceCatalogueSeedOutcomeIds().map(([packageId, outcomeId], index) =>
    relation('packageOutcome', packageId, outcomeId, index + 1),
  )
}

function getMasterServiceCatalogueSeedOutcomeIds() {
  return [
  ['bathroom-home-safety-package', 'bathroom-safer-bathing'],
  ['bathroom-home-safety-package', 'bathroom-safer-toilet-transfers'],
  ['bathroom-home-safety-package', 'bathroom-slip-prevention'],
  ['bathroom-home-safety-package', 'bathroom-improved-visibility'],
  ['bathroom-home-safety-package', 'bathroom-easier-tap-control'],
  ['bathroom-home-safety-package', 'bathroom-temperature-safety'],
  ['bathroom-home-safety-package', 'bathroom-safer-access'],
  ['bathroom-home-safety-package', 'bathroom-safety-monitoring'],
  ['bathroom-connected-room', 'bathroom-connected-guidance'],
  ['bathroom-optional-adaptations', 'bathroom-bathtub-step-through'],
  ['bathroom-optional-adaptations', 'bathroom-wider-doorway'],
  ['bathroom-optional-adaptations', 'bathroom-vertical-support'],
  ['bedroom-home-safety-package', 'bedroom-safer-lighting'],
  ['bedroom-home-safety-package', 'bedroom-easier-bed-transfers'],
  ['bedroom-home-safety-package', 'bedroom-safer-walking-routes'],
  ['bedroom-home-safety-package', 'bedroom-slip-resistance'],
  ['bedroom-home-safety-package', 'bedroom-fire-safety'],
  ['bedroom-connected-room', 'bedroom-voice-assistance'],
  ['bedroom-connected-room', 'bedroom-smart-lighting'],
  ['bedroom-connected-room', 'bedroom-family-reassurance'],
  ['bedroom-connected-room', 'bedroom-daily-living-support'],
  ['bedroom-connected-room', 'bedroom-connected-safety'],
  ['bedroom-optional-adaptations', 'bedroom-emergency-support'],
  ['bedroom-optional-adaptations', 'bedroom-accessible-wardrobe'],
  ['bedroom-optional-adaptations', 'bedroom-advanced-bed-transfer'],
  ['bedroom-optional-adaptations', 'bedroom-electric-adjustable-bed'],
  ['bedroom-optional-adaptations', 'bedroom-bed-exit-safety-system'],
  ['bedroom-optional-adaptations', 'bedroom-automated-curtains'],
  ['bedroom-optional-adaptations', 'bedroom-bathroom-safety-route'],
  ['bedroom-optional-adaptations', 'bedroom-specialist-layout'],
  ['bedroom-optional-adaptations', 'bedroom-door-accessibility'],
  ['bedroom-optional-adaptations', 'bedroom-dementia-support'],
  ['kitchen-home-safety-package', 'kitchen-safer-food-preparation'],
  ['kitchen-home-safety-package', 'kitchen-safer-cooking'],
  ['kitchen-home-safety-package', 'kitchen-improved-lighting'],
  ['kitchen-home-safety-package', 'kitchen-safer-movement'],
  ['kitchen-home-safety-package', 'kitchen-easier-storage'],
  ['kitchen-home-safety-package', 'kitchen-safety-monitoring'],
  ['kitchen-connected-room', 'kitchen-connected-experience'],
  ['kitchen-optional-adaptations', 'kitchen-pull-out-pantry-storage'],
  ['kitchen-optional-adaptations', 'kitchen-wider-doorway'],
  ]
}

function outcomeCapabilityRelations() {
  const map: Record<string, string[]> = {
    'bathroom-safer-bathing': ['bath-transfer-support', 'wet-floor-grip', 'lower-entry-bath-access'],
    'bathroom-safer-toilet-transfers': ['toilet-transfer-support'],
    'bathroom-slip-prevention': ['wet-floor-grip', 'threshold-reduction'],
    'bathroom-improved-visibility': ['motion-activated-lighting', 'bathroom-task-lighting', 'easy-see-switches'],
    'bathroom-easier-tap-control': ['lever-water-control', 'lever-shower-control'],
    'bathroom-temperature-safety': ['anti-scald-control', 'hot-water-temperature-setting'],
    'bathroom-safer-access': ['bathroom-door-control', 'threshold-reduction'],
    'bathroom-safety-monitoring': ['water-leak-alerting', 'resident-phone-alerting', 'nominated-carer-alerting', 'automatic-water-shutoff'],
    'bathroom-connected-guidance': ['motion-activated-lighting', 'bathroom-task-lighting'],
    'bathroom-bathtub-step-through': ['specialist-measurement', 'bath-transfer-support'],
    'bathroom-wider-doorway': ['specialist-measurement'],
    'bathroom-vertical-support': ['specialist-measurement', 'toilet-transfer-support'],
    'bedroom-safer-lighting': ['bedside-lighting', 'low-level-night-lighting', 'motion-activated-lighting', 'easy-reach-light-controls'],
    'bedroom-easier-bed-transfers': ['bed-height-optimisation', 'transfer-clearance', 'discreet-transfer-support', 'furniture-repositioning'],
    'bedroom-safer-walking-routes': ['loose-rug-securing', 'cable-management', 'furniture-repositioning'],
    'bedroom-slip-resistance': ['loose-rug-securing'],
    'bedroom-emergency-support': ['emergency-call-access', 'wearable-emergency-support', 'bedside-emergency-assistance'],
    'bedroom-fire-safety': ['smoke-alerting'],
    'bedroom-voice-assistance': ['smart-speaker-setup', 'hands-free-calling', 'routine-reminders'],
    'bedroom-smart-lighting': ['smart-speaker-setup', 'voice-controlled-lighting', 'motion-activated-lighting'],
    'bedroom-family-reassurance': ['movement-reassurance', 'family-carer-notifications'],
    'bedroom-daily-living-support': ['routine-reminders', 'appointment-reminders', 'smart-speaker-setup'],
    'bedroom-connected-safety': ['smoke-alerting', 'emergency-call-access', 'night-time-safety-alerts'],
    'kitchen-safer-food-preparation': ['lever-water-control', 'automatic-jar-opening', 'easy-grip-kitchen-tools', 'non-slip-chopping-support', 'easy-pour-kettle-support', 'anti-fatigue-standing-zone'],
    'kitchen-safer-cooking': ['safer-hob-control', 'automatic-gas-shutoff'],
    'kitchen-improved-lighting': ['motion-activated-lighting', 'kitchen-task-lighting'],
    'kitchen-safer-movement': ['wet-floor-grip', 'loose-rug-securing', 'kitchen-circulation-space', 'anti-fatigue-standing-zone'],
    'kitchen-easier-storage': ['kitchen-storage-organisation', 'waist-height-storage'],
    'kitchen-safety-monitoring': ['smoke-alerting', 'water-leak-alerting', 'kitchen-motion-alerting'],
    'kitchen-connected-experience': ['smart-speaker-setup', 'voice-controlled-lighting', 'voice-cooking-assistance', 'shopping-list-management', 'routine-reminders', 'appointment-reminders', 'hands-free-calling', 'family-carer-notifications'],
    'kitchen-pull-out-pantry-storage': ['specialist-measurement', 'pull-out-pantry-storage'],
    'kitchen-wider-doorway': ['specialist-measurement', 'wider-kitchen-doorway'],
  }

  const optionalBedroomOutcomeIds = [
    'bedroom-accessible-wardrobe',
    'bedroom-advanced-bed-transfer',
    'bedroom-electric-adjustable-bed',
    'bedroom-bed-exit-safety-system',
    'bedroom-automated-curtains',
    'bedroom-bathroom-safety-route',
    'bedroom-specialist-layout',
    'bedroom-door-accessibility',
    'bedroom-dementia-support',
  ]

  optionalBedroomOutcomeIds.forEach((outcomeId) => {
    map[outcomeId] = ['specialist-measurement']
  })

  return Object.entries(map).flatMap(([outcomeId, capabilityIds]) =>
    capabilityIds.map((capabilityId, index) => relation('outcomeCapability', outcomeId, capabilityId, index + 1)),
  )
}

function capabilityProductRelations() {
  const map: Record<string, string[]> = {
    'bath-transfer-support': ['grab-bar', 'folding-shower-seat'],
    'toilet-transfer-support': ['raised-toilet-seat', 'toilet-support-rail'],
    'wet-floor-grip': ['anti-slip-treatment', 'anti-slip-mat'],
    'bathroom-task-lighting': ['bathroom-led-light'],
    'easy-see-switches': ['high-contrast-switch-control'],
    'motion-activated-lighting': ['motion-sensor', 'low-level-floor-light'],
    'lever-water-control': ['lever-mixer-tap'],
    'lever-shower-control': ['lever-operated-shower-control'],
    'anti-scald-control': ['thermostatic-valve'],
    'hot-water-temperature-setting': ['hot-water-setting-service'],
    'threshold-reduction': ['low-threshold-transition'],
    'bathroom-door-control': ['lever-door-handle', 'easy-release-privacy-lock', 'door-adjustment-service'],
    'lower-entry-bath-access': ['bath-step-through-conversion'],
    'water-leak-alerting': ['water-leak-sensor'],
    'resident-phone-alerting': ['resident-alert-setup'],
    'nominated-carer-alerting': ['carer-alert-setup'],
    'automatic-water-shutoff': ['automatic-water-shutoff-valve'],
    'bedside-lighting': ['bedside-light'],
    'low-level-night-lighting': ['low-level-floor-light'],
    'loose-rug-securing': ['anti-slip-mat'],
    'cable-management': ['cable-management-kit'],
    'accessible-storage-arrangement': ['storage-reach-kit'],
    'discreet-transfer-support': ['bed-support-handle'],
    'wearable-emergency-support': ['wearable-emergency-pendant'],
    'bedside-emergency-assistance': ['bedside-emergency-button'],
    'smart-speaker-setup': ['smart-speaker'],
    'voice-controlled-lighting': ['smart-speaker', 'low-level-floor-light'],
    'hands-free-calling': ['smart-speaker'],
    'routine-reminders': ['smart-speaker'],
    'appointment-reminders': ['smart-speaker'],
    'family-carer-notifications': ['smart-speaker'],
    'night-time-safety-alerts': ['smart-speaker', 'motion-sensor'],
    'movement-reassurance': ['motion-sensor'],
    'emergency-call-access': ['emergency-call-button', 'smart-speaker'],
    'smoke-alerting': ['smoke-detector'],
    'automatic-jar-opening': ['automatic-jar-opener'],
    'easy-grip-kitchen-tools': ['easy-grip-kitchen-utensils'],
    'non-slip-chopping-support': ['non-slip-chopping-board'],
    'easy-pour-kettle-support': ['easy-pour-kettle-tipper'],
    'anti-fatigue-standing-zone': ['anti-fatigue-kitchen-mat'],
    'safer-hob-control': ['induction-hob-automatic-shutoff'],
    'automatic-gas-shutoff': ['automatic-gas-shutoff-system'],
    'kitchen-task-lighting': ['kitchen-task-light'],
    'kitchen-circulation-space': ['kitchen-storage-reorganisation-service'],
    'kitchen-storage-organisation': ['kitchen-storage-reorganisation-service'],
    'waist-height-storage': ['kitchen-storage-reorganisation-service'],
    'kitchen-motion-alerting': ['motion-sensor'],
    'voice-cooking-assistance': ['smart-speaker'],
    'shopping-list-management': ['smart-speaker'],
    'pull-out-pantry-storage': ['pull-out-pantry-hardware'],
    'wider-kitchen-doorway': ['wider-kitchen-doorway-service'],
  }

  return Object.entries(map).flatMap(([capabilityId, productIds]) =>
    productIds.map((productId, index) => relation('capabilityProduct', capabilityId, productId, index + 1)),
  )
}

function capabilityTaskRelations() {
  const map: Record<string, string[]> = {
    'bath-transfer-support': ['inspect-fixing-surface', 'install-support-rail', 'fit-shower-seat'],
    'toilet-transfer-support': ['inspect-fixing-surface', 'install-support-rail'],
    'wet-floor-grip': ['apply-anti-slip-treatment'],
    'lever-water-control': ['fit-water-control'],
    'lever-shower-control': ['fit-water-control'],
    'anti-scald-control': ['fit-water-control'],
    'hot-water-temperature-setting': ['set-hot-water-temperature'],
    'threshold-reduction': ['reduce-threshold'],
    'bathroom-door-control': ['fit-door-hardware', 'adjust-bathroom-door'],
    'lower-entry-bath-access': ['measure-specialist-adaptation'],
    'water-leak-alerting': ['fit-water-leak-sensor', 'configure-bathroom-alerting'],
    'resident-phone-alerting': ['configure-bathroom-alerting'],
    'nominated-carer-alerting': ['configure-bathroom-alerting'],
    'automatic-water-shutoff': ['fit-water-shutoff-valve', 'configure-bathroom-alerting'],
    'bathroom-task-lighting': ['inspect-fixing-surface'],
    'motion-activated-lighting': ['configure-motion-lighting'],
    'smart-speaker-setup': ['pair-smart-speaker'],
    'emergency-call-access': ['test-emergency-contact', 'configure-bedroom-emergency-support'],
    'wearable-emergency-support': ['configure-bedroom-emergency-support', 'test-emergency-contact'],
    'bedside-emergency-assistance': ['configure-bedroom-emergency-support', 'test-emergency-contact'],
    'smoke-alerting': ['test-emergency-contact'],
    'loose-rug-securing': ['reposition-furniture'],
    'cable-management': ['reposition-furniture'],
    'accessible-storage-arrangement': ['reposition-furniture'],
    'movement-reassurance': ['configure-motion-lighting'],
    'hands-free-calling': ['pair-smart-speaker', 'test-emergency-contact'],
    'appointment-reminders': ['pair-smart-speaker'],
    'family-carer-notifications': ['pair-smart-speaker', 'test-emergency-contact'],
    'night-time-safety-alerts': ['configure-motion-lighting', 'test-emergency-contact'],
    'furniture-repositioning': ['reposition-furniture'],
    'specialist-measurement': ['measure-specialist-adaptation'],
    'automatic-jar-opening': ['set-up-kitchen-prep-support'],
    'easy-grip-kitchen-tools': ['set-up-kitchen-prep-support'],
    'non-slip-chopping-support': ['set-up-kitchen-prep-support'],
    'easy-pour-kettle-support': ['set-up-kitchen-prep-support'],
    'anti-fatigue-standing-zone': ['improve-kitchen-standing-route'],
    'safer-hob-control': ['assess-kitchen-cooking-safety', 'configure-kitchen-cooking-safeguard'],
    'automatic-gas-shutoff': ['assess-kitchen-cooking-safety', 'configure-kitchen-cooking-safeguard'],
    'kitchen-task-lighting': ['install-kitchen-task-lighting'],
    'kitchen-circulation-space': ['improve-kitchen-standing-route'],
    'kitchen-storage-organisation': ['organise-kitchen-storage'],
    'waist-height-storage': ['organise-kitchen-storage'],
    'kitchen-motion-alerting': ['configure-kitchen-alerting'],
    'voice-cooking-assistance': ['configure-connected-kitchen'],
    'shopping-list-management': ['configure-connected-kitchen'],
    'pull-out-pantry-storage': ['fit-pull-out-pantry'],
    'wider-kitchen-doorway': ['measure-kitchen-doorway'],
  }

  return Object.entries(map).flatMap(([capabilityId, taskIds]) =>
    taskIds.map((taskId, index) => relation('capabilityInstallationTask', capabilityId, taskId, index + 1)),
  )
}
