import type { MasterServiceCatalogue } from '../types/serviceCatalogue.ts'

const now = '2026-07-23T00:00:00.000Z'

export const masterServiceCatalogue: MasterServiceCatalogue = {
  version: '1.0.0',
  updatedAt: now,
  rooms: [
    { id: 'bathroom', slug: 'bathroom', name: { en: 'Bathroom', es: 'Baño' }, active: true, sortOrder: 10 },
    { id: 'bedroom', slug: 'bedroom', name: { en: 'Bedroom', es: 'Dormitorio' }, active: true, sortOrder: 20 },
    { id: 'kitchen', slug: 'kitchen', name: { en: 'Kitchen', es: 'Cocina' }, active: true, sortOrder: 30 },
    { id: 'living-room', slug: 'living-room', name: { en: 'Living Room', es: 'Salón' }, active: true, sortOrder: 40 },
    { id: 'entrance', slug: 'entrance', name: { en: 'Entrance', es: 'Entrada' }, active: true, sortOrder: 50 },
  ],
  sections: [
    {
      id: 'home-safety-package',
      slug: 'home-safety-package',
      name: { en: 'Home Safety Package', es: 'Paquete de seguridad del hogar' },
      description: {
        en: 'Physical improvements that make daily routines safer and easier.',
        es: 'Mejoras físicas para que las rutinas diarias sean más seguras y sencillas.',
      },
      active: true,
      sortOrder: 10,
    },
    {
      id: 'connected-room',
      slug: 'connected-room',
      name: { en: 'Connected Room', es: 'Estancia conectada' },
      description: {
        en: 'Configured technology experiences, not loose devices.',
        es: 'Experiencias tecnológicas configuradas, no dispositivos sueltos.',
      },
      active: true,
      sortOrder: 20,
    },
    {
      id: 'optional-adaptations',
      slug: 'optional-adaptations',
      name: { en: 'Optional Adaptations', es: 'Adaptaciones opcionales' },
      description: {
        en: 'Bespoke works requiring assessment, measurements, or quotation.',
        es: 'Trabajos a medida que requieren evaluación, medición o presupuesto.',
      },
      active: true,
      sortOrder: 30,
    },
  ],
  packages: [
    packageRecord('bathroom-home-safety-package', 'bathroom', 'home-safety-package', {
      en: 'Bathroom Home Safety Package',
      es: 'Paquete de seguridad para baño',
    }, 'Bathroom Home Safety Package', 10, false, {
      shortDescription: {
        en: 'Thoughtful improvements that make bathing, toilet use, and movement around the bathroom safer and easier, while preserving the look and feel of the home.',
        es: 'Mejoras cuidadas que hacen que bañarse, usar el inodoro y moverse por el baño sea más seguro y sencillo, conservando el aspecto y la sensación del hogar.',
      },
      customerBenefit: {
        en: 'A safer bathroom plan without making the home feel clinical.',
        es: 'Un plan de baño más seguro sin que la vivienda parezca clínica.',
      },
    }),
    packageRecord('bathroom-connected-room', 'bathroom', 'connected-room', {
      en: 'Casamia Connected Bathroom',
      es: 'Baño conectado Casamia',
    }, 'Casamia Connected Bathroom', 20),
    packageRecord('bathroom-optional-adaptations', 'bathroom', 'optional-adaptations', {
      en: 'Bathroom Optional Adaptations',
      es: 'Adaptaciones opcionales de baño',
    }, 'Bathroom Optional Adaptations', 30, true),
    packageRecord('bedroom-home-safety-package', 'bedroom', 'home-safety-package', {
      en: 'Bedroom Home Safety Package',
      es: 'Paquete de seguridad para dormitorio',
    }, 'Bedroom Home Safety Package', 40, false, {
      shortDescription: {
        en: 'Thoughtful improvements that make getting in and out of bed, moving around the bedroom, and maintaining independence safer and more comfortable.',
        es: 'Mejoras cuidadas que hacen que entrar y salir de la cama, moverse por el dormitorio y mantener la independencia sea más seguro y cómodo.',
      },
      customerBenefit: {
        en: 'A calmer, safer bedroom for night-time movement, transfers and daily independence.',
        es: 'Un dormitorio más tranquilo y seguro para moverse de noche, hacer transferencias y mantener la independencia diaria.',
      },
    }),
    packageRecord('bedroom-connected-room', 'bedroom', 'connected-room', {
      en: 'Casamia Connected Bedroom',
      es: 'Dormitorio conectado Casamia',
    }, 'Casamia Connected Bedroom', 50, false, {
      shortDescription: {
        en: 'A tailored smart-home setup centred around a configured smart speaker and compatible devices.',
        es: 'Una configuración smart-home a medida centrada en un altavoz inteligente configurado y dispositivos compatibles.',
      },
      customerBenefit: {
        en: 'Simple voice, reminder and reassurance experiences without turning the bedroom into a device showroom.',
        es: 'Experiencias sencillas de voz, recordatorios y tranquilidad sin convertir el dormitorio en un escaparate de dispositivos.',
      },
    }),
    packageRecord('bedroom-optional-adaptations', 'bedroom', 'optional-adaptations', {
      en: 'Bedroom Optional Adaptations',
      es: 'Adaptaciones opcionales de dormitorio',
    }, 'Bedroom Optional Adaptations', 60, true),
    packageRecord('kitchen-home-safety-package', 'kitchen', 'home-safety-package', {
      en: 'Kitchen Home Safety Package',
      es: 'Paquete de seguridad para cocina',
    }, 'Kitchen Home Safety Package', 70, false, {
      shortDescription: {
        en: 'Thoughtful improvements that make cooking, preparing meals, and moving around the kitchen safer and easier.',
        es: 'Mejoras cuidadas que hacen que cocinar, preparar comidas y moverse por la cocina sea más seguro y sencillo.',
      },
      customerBenefit: {
        en: 'A safer, easier kitchen plan that supports independence without turning the room into a product showroom.',
        es: 'Un plan de cocina más seguro y sencillo que apoya la independencia sin convertir la estancia en un escaparate de productos.',
      },
    }),
    packageRecord('kitchen-connected-room', 'kitchen', 'connected-room', {
      en: 'Casamia Connected Kitchen',
      es: 'Cocina conectada Casamia',
    }, 'Casamia Connected Kitchen', 80, false, {
      shortDescription: {
        en: 'A smart kitchen setup centred around a configured smart speaker and compatible devices.',
        es: 'Una cocina inteligente centrada en un altavoz configurado y dispositivos compatibles.',
      },
      customerBenefit: {
        en: 'Voice, reminders and family reassurance configured around real kitchen routines.',
        es: 'Voz, recordatorios y tranquilidad familiar configurados alrededor de rutinas reales de cocina.',
      },
    }),
    packageRecord('kitchen-optional-adaptations', 'kitchen', 'optional-adaptations', {
      en: 'Kitchen Optional Adaptations',
      es: 'Adaptaciones opcionales de cocina',
    }, 'Kitchen Optional Adaptations', 90, true),
    packageRecord('living-room-home-safety-package', 'living-room', 'home-safety-package', {
      en: 'Living Room Home Safety Package',
      es: 'Paquete de seguridad para salón',
    }, 'Living Room Home Safety Package', 100, false, {
      shortDescription: {
        en: 'Thoughtful improvements that make relaxing, moving around and enjoying everyday life safer, more comfortable and more independent.',
        es: 'Mejoras cuidadas que hacen que descansar, moverse y disfrutar del día a día sea más seguro, cómodo e independiente.',
      },
      customerBenefit: {
        en: 'A safer living room for sitting, standing, moving around and staying comfortable every day.',
        es: 'Un salón más seguro para sentarse, levantarse, moverse y estar cómodo cada día.',
      },
    }),
    packageRecord('living-room-connected-room', 'living-room', 'connected-room', {
      en: 'Casamia Connected Living Room',
      es: 'Salón conectado Casamia',
    }, 'Casamia Connected Living Room', 110, false, {
      shortDescription: {
        en: 'A smart living room experience centred around a configured smart speaker and compatible devices.',
        es: 'Una experiencia de salón conectado centrada en un altavoz inteligente configurado y dispositivos compatibles.',
      },
      customerBenefit: {
        en: 'Simple voice, reminder, call and reassurance features configured around everyday living-room routines.',
        es: 'Funciones sencillas de voz, recordatorios, llamadas y tranquilidad configuradas alrededor de las rutinas del salón.',
      },
    }),
    packageRecord('living-room-optional-adaptations', 'living-room', 'optional-adaptations', {
      en: 'Living Room Optional Adaptations',
      es: 'Adaptaciones opcionales de salón',
    }, 'Living Room Optional Adaptations', 120, true),
    packageRecord('entrance-home-safety-package', 'entrance', 'home-safety-package', {
      en: 'Entrance Home Safety Package',
      es: 'Paquete de seguridad para entrada',
    }, 'Entrance Home Safety Package', 130, false, {
      shortDescription: {
        en: 'Thoughtful improvements that make entering and leaving your home safer, easier and more comfortable.',
        es: 'Mejoras cuidadas que hacen que entrar y salir de casa sea más seguro, fácil y cómodo.',
      },
      customerBenefit: {
        en: 'A safer entrance for steps, thresholds, door use and visibility.',
        es: 'Una entrada más segura para escalones, umbrales, uso de la puerta y visibilidad.',
      },
    }),
    packageRecord('entrance-connected-room', 'entrance', 'connected-room', {
      en: 'Casamia Connected Entrance',
      es: 'Entrada conectada Casamia',
    }, 'Casamia Connected Entrance', 140, false, {
      shortDescription: {
        en: 'A connected entrance setup for visitor visibility, two-way communication and useful alerts.',
        es: 'Una configuración conectada para ver visitantes, comunicarse a distancia y recibir avisos útiles.',
      },
      customerBenefit: {
        en: 'Know who is at the door and share selected alerts with family or carers when useful.',
        es: 'Permite saber quién está en la puerta y compartir avisos seleccionados con familia o cuidadores cuando ayude.',
      },
    }),
    packageRecord('entrance-optional-adaptations', 'entrance', 'optional-adaptations', {
      en: 'Entrance Optional Adaptations',
      es: 'Adaptaciones opcionales de entrada',
    }, 'Entrance Optional Adaptations', 150, true),
  ],
  outcomes: [
    outcome('bathroom-safer-bathing', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Safer Bathing', 'Baño y ducha más seguros', 'Bathing safety', 'Making bathing easier, safer, and more comfortable.', 'Hace que bañarse sea más fácil, seguro y cómodo.', 'Includes wall-mounted grab bars, a folding shower seat and a secure bath or shower mat where suitable.', 'Incluye barras de apoyo en pared, asiento abatible de ducha y alfombrilla segura para bañera o ducha cuando encaje.', 'essential', ['bathroom'], 10, { legacyId: 'bathroom-folding-shower-seat', grantEligible: true }),
    outcome('bathroom-safer-toilet-transfers', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Safer Toilet Transfers', 'Transferencias al inodoro más seguras', 'Toilet transfers', 'Helping residents sit down and stand up with greater stability.', 'Ayuda a sentarse y levantarse del inodoro con mayor estabilidad.', 'Includes toilet support rails and a raised toilet seat when the person needs steadier sit-to-stand movement.', 'Incluye barras de apoyo para inodoro y elevador de inodoro cuando la persona necesita más estabilidad al sentarse y levantarse.', 'essential', ['bathroom'], 20, { legacyId: 'bathroom-raised-toilet-seat', grantEligible: true }),
    outcome('bathroom-slip-prevention', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Slip Prevention', 'Prevención de resbalones', 'Wet-floor safety', 'Reducing common slipping and tripping hazards.', 'Reduce riesgos habituales de resbalones y tropiezos.', 'Improves wet-floor grip and awkward thresholds with anti-slip treatment and a low-profile transition strip.', 'Mejora el agarre del suelo mojado y umbrales difíciles con tratamiento antideslizante y perfil de transición bajo.', 'essential', ['bathroom'], 30, { legacyId: 'bathroom-anti-slip-floor-treatment', grantEligible: true }),
    outcome('bathroom-improved-visibility', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Improved Bathroom Visibility', 'Mejor visibilidad en el baño', 'Bathroom lighting', 'Making the bathroom easier to navigate during the day and at night.', 'Hace que el baño sea más fácil de recorrer durante el día y por la noche.', 'Adds motion-activated night lighting and high-contrast switch markers where visibility is poor.', 'Añade luz nocturna con sensor de movimiento y marcadores de alto contraste en interruptores cuando hay poca visibilidad.', 'essential', ['bathroom', 'lighting'], 40, { legacyId: 'bathroom-improved-lighting', grantEligible: true }),
    outcome('bathroom-easier-tap-control', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Easier Water Controls', 'Controles de agua más fáciles', 'Water control', 'Making taps and shower controls easier to use with reduced grip strength or dexterity.', 'Hace que grifos y controles de ducha sean más fáciles de usar con menos fuerza o destreza.', 'Replaces difficult twist controls with lever taps and lever-operated shower controls where suitable.', 'Sustituye controles giratorios difíciles por grifos y mandos de ducha de palanca cuando sea adecuado.', 'essential', ['bathroom'], 50, { legacyId: 'bathroom-lever-mixer-tap' }),
    outcome('bathroom-temperature-safety', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Temperature Safety', 'Seguridad de temperatura', 'Water safety', 'Helping reduce the risk of accidental scalding.', 'Ayuda a reducir el riesgo de quemaduras accidentales.', 'Adds a thermostatic anti-scald valve and sets hot-water temperature to a safer range where suitable.', 'Añade una válvula termostática antiquemaduras y ajusta el agua caliente a un rango más seguro cuando sea adecuado.', 'essential', ['bathroom'], 60, { legacyId: 'bathroom-thermostatic-valve' }),
    outcome('bathroom-safer-access', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Safer Bathroom Access', 'Acceso al baño más seguro', 'Access', 'Making it easier and safer to enter, exit, and use the bathroom door.', 'Hace que sea más fácil y seguro entrar, salir y usar la puerta del baño.', 'Makes the bathroom door easier to open, close and release in an emergency.', 'Hace que la puerta del baño sea más fácil de abrir, cerrar y desbloquear en caso de emergencia.', 'essential', ['bathroom', 'entrance'], 70, { legacyId: 'bathroom-threshold-removal', grantEligible: true }),
    outcome('bathroom-safety-monitoring', 'bathroom', 'home-safety-package', 'bathroom-home-safety-package', 'Bathroom Safety Monitoring', 'Monitorización de seguridad del baño', 'Bathroom risk alerts', 'Providing early warning of selected bathroom risks.', 'Proporciona aviso temprano de determinados riesgos del baño.', 'Adds a water leak sensor, phone alerts and an automatic shut-off valve where the plumbing is compatible.', 'Añade sensor de fuga de agua, avisos al teléfono y válvula automática de corte cuando la fontanería sea compatible.', 'recommended', ['bathroom', 'smart-safety'], 80, { legacyId: 'bathroom-safety-monitoring', technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('bathroom-connected-guidance', 'bathroom', 'connected-room', 'bathroom-connected-room', 'Automatic Bathroom Guidance', 'Guía automática en el baño', 'Connected bathroom', 'Motion-triggered guidance for safer low-light bathroom routines.', 'Guía activada por movimiento para rutinas de baño con poca luz.', 'Help the bathroom respond quietly when someone enters at night.', 'Ayuda a que el baño responda discretamente por la noche.', 'recommended', ['bathroom', 'lighting', 'smart-safety'], 85, { legacyId: 'bathroom-motion-lighting', technologyEnabled: true }),
    outcome('bathroom-bathtub-step-through', 'bathroom', 'optional-adaptations', 'bathroom-optional-adaptations', 'Bathtub Step-through Conversion', 'Conversión de bañera con acceso bajo', 'Bath adaptation', 'A specialist conversion to reduce the step over the bath edge.', 'Conversión especializada para reducir el paso sobre el borde de la bañera.', 'Make bath access easier without replacing the whole room.', 'Facilita el acceso a la bañera sin sustituir todo el baño.', 'optional', ['bathroom'], 90, { legacyId: 'bathroom-tub-cutout', quoteOnly: true, grantEligible: true }),
    outcome('bathroom-wider-doorway', 'bathroom', 'optional-adaptations', 'bathroom-optional-adaptations', 'Wider Bathroom Doorway', 'Puerta de baño más ancha', 'Door access', 'A measured doorway adaptation where walking aids or wheelchairs need more clearance.', 'Adaptación medida de puerta cuando ayudas de movilidad o sillas necesitan más espacio.', 'Improve access when the current doorway is too tight.', 'Mejora el acceso cuando la puerta actual resulta estrecha.', 'optional', ['bathroom', 'entrance'], 100, { legacyId: 'bathroom-wider-doorway', quoteOnly: true, grantEligible: true }),
    outcome('bathroom-vertical-support', 'bathroom', 'optional-adaptations', 'bathroom-optional-adaptations', 'Vertical Support Rail', 'Barra de apoyo vertical', 'Transfer support', 'Additional vertical support where transfers need a stronger plan.', 'Apoyo vertical adicional cuando las transferencias requieren una solución más robusta.', 'Add support where standard rails are not enough.', 'Añade apoyo donde las barras estándar no bastan.', 'optional', ['bathroom'], 110, { legacyId: 'bathroom-vertical-support-rail', quoteOnly: true, grantEligible: true }),
    outcome('bedroom-safer-lighting', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Safer Bedroom Lighting', 'Iluminación de dormitorio más segura', 'Bedroom lighting', 'Improving visibility throughout the bedroom, particularly during the night.', 'Mejora la visibilidad en todo el dormitorio, especialmente durante la noche.', 'Make it easier to see before getting out of bed and moving around at night.', 'Facilita ver antes de levantarse y moverse por la noche.', 'essential', ['bedroom', 'lighting'], 120, { legacyId: 'bedroom-underbed-lighting', grantEligible: true }),
    outcome('bedroom-easier-bed-transfers', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Easier Bed Transfers', 'Transferencias de cama más fáciles', 'Bed transfers', 'Making it easier and safer to get into and out of bed.', 'Hace que entrar y salir de la cama sea más fácil y seguro.', 'Improve support, bed height and positioning around one of the most important daily transfer points.', 'Mejora el apoyo, la altura y la posición de la cama en una transferencia diaria clave.', 'essential', ['bedroom'], 130, { legacyId: 'bedroom-bed-support', grantEligible: true }),
    outcome('bedroom-safer-walking-routes', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Safer Walking Routes', 'Rutas de paso más seguras', 'Bedroom routes', 'Reducing common trip hazards throughout the bedroom.', 'Reduce riesgos habituales de tropiezo en todo el dormitorio.', 'Keep the route between the bed and the door clearer and easier to use.', 'Mantiene más despejada y fácil de usar la ruta entre la cama y la puerta.', 'essential', ['bedroom', 'living-room'], 140, { legacyId: 'bedroom-night-route', grantEligible: true }),
    outcome('bedroom-slip-resistance', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Slip-Resistance Improvements', 'Mejoras antideslizantes', 'Floor safety', 'Reducing the likelihood of slips within the bedroom.', 'Reduce la probabilidad de resbalones dentro del dormitorio.', 'Improve floor grip and secure floor coverings where needed.', 'Mejora el agarre del suelo y asegura revestimientos cuando sea necesario.', 'essential', ['bedroom'], 150, { grantEligible: true }),
    outcome('bedroom-fire-safety', 'bedroom', 'home-safety-package', 'bedroom-home-safety-package', 'Fire Safety', 'Seguridad contra incendios', 'Fire safety', 'Helping protect the bedroom through early fire detection.', 'Ayuda a proteger el dormitorio mediante detección temprana de incendios.', 'Support faster awareness if smoke is detected.', 'Favorece una alerta más rápida si se detecta humo.', 'essential', ['bedroom', 'smart-safety'], 160),
    outcome('bedroom-voice-assistance', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Voice Assistance', 'Asistencia por voz', 'Connected bedroom', 'Voice support for lights, calls, reminders and simple help requests.', 'Apoyo por voz para luces, llamadas, recordatorios y peticiones sencillas.', 'Make daily routines easier without needing a complex interface.', 'Facilita rutinas sin interfaces complicadas.', 'recommended', ['bedroom', 'smart-safety'], 190, { technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-smart-lighting', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Smart Lighting', 'Iluminación inteligente', 'Connected bedroom', 'Configured lighting scenes, voice control and automatic night guidance.', 'Escenas de luz, control por voz y guía nocturna automática configuradas.', 'Let the room adapt to night-time movement and simple spoken requests.', 'Permite que la estancia se adapte al movimiento nocturno y a peticiones por voz.', 'recommended', ['bedroom', 'lighting', 'smart-safety'], 200, { technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-family-reassurance', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Family Reassurance', 'Tranquilidad familiar', 'Connected bedroom', 'Carefully configured family or carer notifications where appropriate and consented.', 'Avisos para familiares o cuidadores configurados cuidadosamente cuando proceda y haya consentimiento.', 'Help family understand routines without intrusive monitoring.', 'Ayuda a la familia a entender rutinas sin vigilancia invasiva.', 'recommended', ['bedroom', 'smart-safety'], 210, { legacyId: 'bedroom-bed-exit-sensor', technologyEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-daily-living-support', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Daily Living Support', 'Apoyo a rutinas diarias', 'Connected bedroom', 'Medication, appointment and morning/evening routine prompts.', 'Recordatorios de medicación, citas y rutinas de mañana/noche.', 'Support independence with gentle prompts.', 'Apoya la independencia con avisos amables.', 'recommended', ['bedroom', 'smart-safety'], 220, { technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-connected-safety', 'bedroom', 'connected-room', 'bedroom-connected-room', 'Night-time Safety Alerts', 'Alertas nocturnas de seguridad', 'Connected bedroom', 'Compatible connected alerts selected for the resident and home.', 'Alertas conectadas compatibles seleccionadas para la persona y la vivienda.', 'Keep safety technology simple and coordinated.', 'Mantiene la tecnología de seguridad sencilla y coordinada.', 'recommended', ['bedroom', 'smart-safety'], 230, { technologyEnabled: true, requiresSmartSpeaker: true }),
    outcome('bedroom-emergency-support', 'bedroom', 'optional-adaptations', 'bedroom-optional-adaptations', 'Emergency Support', 'Apoyo de emergencia', 'Emergency access', 'A reviewed emergency support route for the bedroom.', 'Una vía de apoyo de emergencia revisada para el dormitorio.', 'Give the resident and family a clearer way to call for help from the bedroom.', 'Da al residente y la familia una vía más clara para pedir ayuda desde el dormitorio.', 'optional', ['bedroom', 'smart-safety'], 235, { grantEligible: true, quoteOnly: true, requiresCompatibilityCheck: true, technologyEnabled: true }),
    ...[
      ['bedroom-accessible-wardrobe', 'Accessible Wardrobe Adaptation', 'Armario más accesible'],
      ['bedroom-advanced-bed-transfer', 'Advanced Bed Transfer Solution', 'Solución avanzada de transferencia de cama'],
      ['bedroom-electric-adjustable-bed', 'Electric Adjustable Bed', 'Cama eléctrica ajustable'],
      ['bedroom-bed-exit-safety-system', 'Bed Exit Safety System', 'Sistema de seguridad al salir de la cama'],
      ['bedroom-automated-curtains', 'Automated Curtains or Blinds', 'Cortinas o persianas automatizadas'],
      ['bedroom-bathroom-safety-route', 'Bedroom-to-Bathroom Safety Route', 'Ruta segura del dormitorio al baño'],
      ['bedroom-specialist-layout', 'Specialist Bedroom Layout Adaptation', 'Adaptación especializada del dormitorio'],
      ['bedroom-door-accessibility', 'Bedroom Door Accessibility Adaptation', 'Adaptación de accesibilidad de puerta'],
      ['bedroom-dementia-support', 'Dementia-Support Bedroom Adaptation', 'Dormitorio adaptado para apoyo cognitivo'],
    ].map(([id, en, es], index) =>
      outcome(id, 'bedroom', 'optional-adaptations', 'bedroom-optional-adaptations', en, es, 'Optional bedroom adaptation', 'A bespoke bedroom adaptation reviewed after assessment.', 'Adaptación de dormitorio a medida revisada tras evaluación.', 'Tailor the bedroom around a specific need.', 'Adapta el dormitorio a una necesidad concreta.', 'optional', ['bedroom'], 240 + index, {
        legacyId: id === 'bedroom-electric-adjustable-bed' ? 'bedroom-adjustable-bed' : undefined,
        quoteOnly: true,
        grantEligible: true,
        requiresCompatibilityCheck: id.includes('automated') || id.includes('system'),
        technologyEnabled: id.includes('automated') || id.includes('system'),
      }),
    ),
    outcome('kitchen-safer-food-preparation', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Safer Food Preparation', 'Preparación de alimentos más segura', 'Food preparation', 'Making everyday food preparation easier and reducing strain on the hands and joints.', 'Hace que la preparación diaria de comidas sea más sencilla y reduce el esfuerzo en manos y articulaciones.', 'Support safer chopping, pouring, opening and standing at the main preparation area.', 'Apoya tareas más seguras al cortar, servir, abrir envases y permanecer de pie en la zona principal de preparación.', 'essential', ['kitchen'], 300, { legacyId: 'kitchen-easy-grip-tools', grantEligible: true }),
    outcome('kitchen-safer-cooking', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Safer Cooking', 'Cocina más segura', 'Cooking safety', 'Reducing everyday cooking risks while maintaining independence.', 'Reduce riesgos cotidianos al cocinar manteniendo la independencia.', 'Add selected safeguards around heat, gas and forgotten cooking routines where suitable.', 'Añade protecciones seleccionadas frente al calor, gas y rutinas olvidadas cuando sea adecuado.', 'essential', ['kitchen', 'smart-safety'], 310, { legacyId: 'kitchen-stove-shutoff', grantEligible: true, technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('kitchen-improved-lighting', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Improved Kitchen Lighting', 'Mejor iluminación en la cocina', 'Kitchen lighting', 'Improving visibility across the kitchen.', 'Mejora la visibilidad en toda la cocina.', 'Make preparation, cooking, spills and edges easier to see.', 'Hace más visibles la preparación, la cocción, los derrames y los bordes.', 'essential', ['kitchen', 'lighting'], 320, { legacyId: 'kitchen-worktop-lighting', grantEligible: true, technologyEnabled: true }),
    outcome('kitchen-safer-movement', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Safer Kitchen Movement', 'Movimiento más seguro en la cocina', 'Kitchen movement', 'Reducing trip hazards and making movement around the kitchen easier.', 'Reduce riesgos de tropiezo y facilita moverse por la cocina.', 'Create clearer walking routes and safer standing zones around daily routines.', 'Crea recorridos más despejados y zonas de apoyo más seguras alrededor de las rutinas diarias.', 'essential', ['kitchen', 'living-room'], 330, { legacyId: 'kitchen-anti-fatigue-mat', grantEligible: true }),
    outcome('kitchen-easier-storage', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Easier Kitchen Storage', 'Almacenamiento de cocina más fácil', 'Reach and storage', 'Making frequently used kitchen items easier to reach.', 'Hace que los utensilios y alimentos de uso frecuente sean más fáciles de alcanzar.', 'Reduce climbing, stretching and carrying by moving everyday items to safer heights.', 'Reduce subirse, estirarse y cargar peso colocando los objetos diarios a alturas más seguras.', 'essential', ['kitchen'], 340, { grantEligible: true }),
    outcome('kitchen-safety-monitoring', 'kitchen', 'home-safety-package', 'kitchen-home-safety-package', 'Kitchen Safety Monitoring', 'Avisos de seguridad en la cocina', 'Kitchen alerts', 'Providing early warning of selected kitchen risks.', 'Proporciona aviso temprano de determinados riesgos en la cocina.', 'Use selected compatible alerts for smoke, water leakage and movement where appropriate.', 'Utiliza avisos compatibles para humo, fuga de agua y movimiento cuando proceda.', 'recommended', ['kitchen', 'smart-safety'], 350, { legacyId: 'kitchen-water-leak-sensor', technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('kitchen-connected-experience', 'kitchen', 'connected-room', 'kitchen-connected-room', 'Connected Kitchen', 'Cocina conectada', 'Connected kitchen', 'A smart kitchen setup centred around a configured smart speaker.', 'Una cocina inteligente centrada en un altavoz configurado.', 'Make cooking routines easier with voice, reminders, lists, calls and selected family notifications.', 'Facilita las rutinas de cocina con voz, recordatorios, listas, llamadas y avisos familiares seleccionados.', 'recommended', ['kitchen', 'smart-safety'], 360, { legacyId: 'kitchen-voice-lighting-timers', technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('kitchen-pull-out-pantry-storage', 'kitchen', 'optional-adaptations', 'kitchen-optional-adaptations', 'Pull-Out Pantry Storage', 'Almacenamiento extraíble de despensa', 'Optional kitchen adaptation', 'A measured storage adaptation that brings cupboard contents into easier reach.', 'Adaptación medida de almacenamiento que acerca el contenido de los armarios.', 'Reduce reaching and unsafe stool use where the existing cabinetry allows it.', 'Reduce estirarse y usar taburetes inseguros cuando los muebles existentes lo permiten.', 'optional', ['kitchen'], 370, { legacyId: 'kitchen-pull-down-shelf', quoteOnly: true, grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('kitchen-wider-doorway', 'kitchen', 'optional-adaptations', 'kitchen-optional-adaptations', 'Wider Kitchen Doorway', 'Puerta de cocina más ancha', 'Optional kitchen adaptation', 'A measured doorway adaptation where mobility aids need more clearance.', 'Adaptación medida de puerta cuando las ayudas de movilidad necesitan más espacio.', 'Improve kitchen access when the current doorway restricts safe movement.', 'Mejora el acceso a la cocina cuando la puerta actual limita el movimiento seguro.', 'optional', ['kitchen', 'entrance'], 380, { quoteOnly: true, grantEligible: true }),
    outcome('living-room-easier-sitting-standing', 'living-room', 'home-safety-package', 'living-room-home-safety-package', 'Easier Sitting & Standing', 'Sentarse y levantarse con más facilidad', 'Sitting and standing', 'Making it easier and safer to sit down and stand up.', 'Hace que sentarse y levantarse sea más fácil y seguro.', 'Includes seating height adjustment, a sofa or chair support handle and improved furniture positioning where suitable.', 'Incluye ajuste de altura del asiento, asa de apoyo para sofá o silla y mejor colocación de muebles cuando encaje.', 'essential', ['living-room'], 400, { legacyId: 'movement-stand-assist', grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('living-room-safer-room', 'living-room', 'home-safety-package', 'living-room-home-safety-package', 'Safer Living Room', 'Salón más seguro', 'Living room hazards', 'Reducing everyday hazards throughout the living room.', 'Reduce riesgos cotidianos en todo el salón.', 'Reduce trip points with rug securing or removal, anti-slip rug tape, cable management and clearer circulation space.', 'Reduce puntos de tropiezo con retirada o fijación de alfombras, cinta antideslizante, organización de cables y más espacio de paso.', 'essential', ['living-room'], 410, { legacyId: 'movement-rug-securing', grantEligible: true }),
    outcome('living-room-improved-lighting', 'living-room', 'home-safety-package', 'living-room-home-safety-package', 'Improved Living Room Lighting', 'Mejor iluminación del salón', 'Living room lighting', 'Improving visibility throughout the living room.', 'Mejora la visibilidad en todo el salón.', 'Adds motion-activated lighting where visibility or switch access is difficult.', 'Añade iluminación con sensor de movimiento donde la visibilidad o el acceso a interruptores resulta difícil.', 'essential', ['living-room', 'lighting'], 420, { legacyId: 'movement-hallway-lighting', grantEligible: true, technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('living-room-slip-prevention', 'living-room', 'home-safety-package', 'living-room-home-safety-package', 'Slip Prevention', 'Prevención de resbalones', 'Floor safety', 'Reducing the likelihood of slips and falls.', 'Reduce la probabilidad de resbalones y caídas.', 'Improves floor grip with anti-slip treatment and secure floor coverings where needed.', 'Mejora el agarre del suelo con tratamiento antideslizante y revestimientos asegurados cuando sea necesario.', 'essential', ['living-room'], 430, { grantEligible: true }),
    outcome('living-room-safer-furniture', 'living-room', 'home-safety-package', 'living-room-home-safety-package', 'Safer Furniture', 'Muebles más seguros', 'Furniture safety', 'Reducing risks associated with unstable furniture.', 'Reduce riesgos asociados a muebles inestables.', 'Anchors furniture and TV units, and adds corner protection where appropriate.', 'Ancla muebles y muebles de televisión, y añade protección de esquinas cuando proceda.', 'essential', ['living-room'], 440, { grantEligible: true }),
    outcome('living-room-safety-monitoring', 'living-room', 'home-safety-package', 'living-room-home-safety-package', 'Home Safety Monitoring', 'Avisos de seguridad del hogar', 'Living room alerts', 'Providing early warning of selected living room risks.', 'Proporciona aviso temprano de determinados riesgos en el salón.', 'Adds a smoke detector and a motion detection sensor where appropriate and consented.', 'Añade detector de humo y sensor de movimiento cuando proceda y haya consentimiento.', 'recommended', ['living-room', 'smart-safety'], 450, { technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('living-room-connected-experience', 'living-room', 'connected-room', 'living-room-connected-room', 'Connected Living Room', 'Salón conectado', 'Connected living room', 'A smart living room experience centred around a configured smart speaker.', 'Una experiencia de salón conectado centrada en un altavoz inteligente configurado.', 'Make daily living easier with voice lighting, calls, reminders, family notifications and emergency voice assistance.', 'Facilita el día a día con luz por voz, llamadas, recordatorios, avisos familiares y ayuda de emergencia por voz.', 'recommended', ['living-room', 'smart-safety'], 460, { technologyEnabled: true, voiceEnabled: true, requiresSmartSpeaker: true }),
    outcome('living-room-advanced-seating', 'living-room', 'optional-adaptations', 'living-room-optional-adaptations', 'Advanced Seating Solutions', 'Soluciones avanzadas de asiento', 'Optional seating adaptation', 'Specialist seating support where standard furniture changes are not enough.', 'Apoyo especializado de asiento cuando los cambios básicos de mobiliario no bastan.', 'Add a more tailored seating solution for safer sitting and standing.', 'Añade una solución de asiento más adaptada para sentarse y levantarse con seguridad.', 'optional', ['living-room'], 470, { quoteOnly: true, grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('living-room-electric-recliner-chair', 'living-room', 'optional-adaptations', 'living-room-optional-adaptations', 'Electric Recliner Chair', 'Sillón relax eléctrico', 'Optional seating adaptation', 'A measured electric recliner option where it suits the person, room and budget.', 'Opción medida de sillón relax eléctrico cuando encaja con la persona, el salón y el presupuesto.', 'Support more comfortable rest and easier transitions to standing.', 'Apoya un descanso más cómodo y transiciones más fáciles al ponerse de pie.', 'optional', ['living-room'], 480, { quoteOnly: true, grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('living-room-wider-doorway', 'living-room', 'optional-adaptations', 'living-room-optional-adaptations', 'Wider Living Room Doorway', 'Puerta de salón más ancha', 'Optional access adaptation', 'A measured doorway adaptation where mobility aids need more clearance.', 'Adaptación medida de puerta cuando las ayudas de movilidad necesitan más espacio.', 'Improve access when the current living-room doorway restricts safe movement.', 'Mejora el acceso cuando la puerta actual del salón limita el movimiento seguro.', 'optional', ['living-room', 'entrance'], 490, { quoteOnly: true, grantEligible: true }),
    outcome('living-room-stair-safety', 'living-room', 'optional-adaptations', 'living-room-optional-adaptations', 'Stair Safety Support', 'Apoyo de seguridad en escaleras', 'Optional stair adaptation', 'A measured stair support plan for homes where stairs are part of the daily route.', 'Plan medido de apoyo en escaleras para viviendas donde las escaleras forman parte de la ruta diaria.', 'Add safer grip, clearer step edges and better visibility where level changes need specialist review.', 'Añade mejor agarre, bordes de escalón más visibles y mejor iluminación cuando los cambios de nivel necesitan revisión especializada.', 'optional', ['living-room', 'stairs'], 495, { quoteOnly: true, grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('entrance-safer-access', 'entrance', 'home-safety-package', 'entrance-home-safety-package', 'Safer Entrance Access', 'Acceso de entrada más seguro', 'Entrance access', 'Making it easier and safer to enter and leave your home.', 'Hace que entrar y salir de casa sea más fácil y seguro.', 'Includes an entrance handrail, low-profile threshold ramp, slip-resistant surface, high-visibility step edge markings and a secure entrance mat where suitable.', 'Incluye pasamanos de entrada, rampa de umbral de bajo perfil, superficie antideslizante, señalización visible del borde del escalón y felpudo seguro cuando encaje.', 'essential', ['entrance', 'outdoor'], 500, { grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('entrance-easier-door-access', 'entrance', 'home-safety-package', 'entrance-home-safety-package', 'Easier Door Access', 'Puerta de entrada más fácil de usar', 'Door access', 'Making the entrance door easier to use.', 'Hace que la puerta de entrada sea más fácil de usar.', 'Includes a lever door handle and easier-to-use lock where the existing door allows it.', 'Incluye manilla tipo palanca y cerradura más fácil de usar cuando la puerta existente lo permite.', 'essential', ['entrance'], 510, { grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('entrance-improved-lighting', 'entrance', 'home-safety-package', 'entrance-home-safety-package', 'Improved Entrance Lighting', 'Mejor iluminación de entrada', 'Entrance lighting', 'Improving visibility around the entrance.', 'Mejora la visibilidad alrededor de la entrada.', 'Adds motion-activated entrance lighting and porch lighting where needed.', 'Añade iluminación de entrada con sensor de movimiento e iluminación de porche cuando sea necesario.', 'essential', ['entrance', 'lighting', 'outdoor'], 520, { legacyId: 'entrance-motion-lighting', grantEligible: true, technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('entrance-connected-door-awareness', 'entrance', 'connected-room', 'entrance-connected-room', 'Connected Door Awareness', 'Control conectado de la puerta', 'Connected entrance', 'Helping residents answer the door safely and know who is outside.', 'Ayuda a responder a la puerta con más seguridad y saber quién está fuera.', 'Includes smart video doorbell setup with two-way communication, live visitor view, motion detection, package detection where supported, mobile notifications and selected family notifications.', 'Incluye configuración de videoportero inteligente con comunicación bidireccional, vista en directo, detección de movimiento, detección de paquetes cuando esté disponible, avisos móviles y avisos familiares seleccionados.', 'recommended', ['entrance', 'smart-safety'], 530, { technologyEnabled: true, requiresCompatibilityCheck: true }),
    outcome('entrance-wider-doorway', 'entrance', 'optional-adaptations', 'entrance-optional-adaptations', 'Wider Entrance Doorway', 'Puerta de entrada más ancha', 'Optional entrance adaptation', 'A measured entrance doorway adaptation where mobility aids need more clearance.', 'Adaptación medida de la puerta de entrada cuando las ayudas de movilidad necesitan más espacio.', 'Improves access when the current entrance doorway limits safe movement.', 'Mejora el acceso cuando la puerta actual de entrada limita el movimiento seguro.', 'optional', ['entrance'], 540, { quoteOnly: true, grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('entrance-accessibility-ramp', 'entrance', 'optional-adaptations', 'entrance-optional-adaptations', 'Accessibility Ramp', 'Rampa de accesibilidad', 'Optional entrance adaptation', 'A measured ramp solution for entrances that need more than a small threshold ramp.', 'Solución medida de rampa para entradas que necesitan más que una pequeña rampa de umbral.', 'Creates a safer, easier entrance route when steps or height differences require a specialist ramp.', 'Crea una ruta de entrada más segura y fácil cuando los escalones o desniveles requieren una rampa especializada.', 'optional', ['entrance', 'outdoor'], 550, { quoteOnly: true, grantEligible: true, requiresCompatibilityCheck: true }),
    outcome('entrance-seating', 'entrance', 'optional-adaptations', 'entrance-optional-adaptations', 'Entrance Seating', 'Asiento de entrada', 'Optional entrance adaptation', 'A measured seating option near the entrance for safer pauses, shoes, bags or waiting.', 'Opción medida de asiento cerca de la entrada para pausas, calzado, bolsas o esperas más seguras.', 'Adds a stable place to pause without blocking the entrance route.', 'Añade un punto estable para hacer una pausa sin bloquear la ruta de entrada.', 'optional', ['entrance'], 560, { quoteOnly: true, grantEligible: true, requiresCompatibilityCheck: true }),
  ],
  capabilities: [
    capability('bedside-lighting', 'Bedside lighting', true),
    capability('bedroom-motion-night-lighting', 'Motion-activated night lighting', true, true),
    capability('low-level-night-lighting', 'Low-level floor lighting', true),
    capability('motion-activated-lighting', 'Motion-activated lighting', true, true),
    capability('easy-reach-light-controls', 'Easy-reach lighting controls', true),
    capability('bed-height-optimisation', 'Bed height adjustment'),
    capability('bed-positioning-adjustment', 'Improved bed positioning'),
    capability('transfer-clearance', 'Clear transfer space beside the bed'),
    capability('discreet-transfer-support', 'Bed assist handle'),
    capability('furniture-repositioning', 'Furniture repositioning'),
    capability('loose-rug-securing', 'Loose rug removal or securing'),
    capability('cable-management', 'Cable management'),
    capability('bed-to-door-clear-route', 'Clear route between the bed and the door'),
    capability('bedroom-anti-slip-floor-treatment', 'Anti-slip floor treatment'),
    capability('bedroom-secure-floor-coverings', 'Secure floor coverings'),
    capability('accessible-storage-arrangement', 'Accessible storage arrangement'),
    capability('emergency-call-access', 'Emergency call button', true, true),
    capability('wearable-emergency-support', 'Wearable emergency pendant', true, true),
    capability('bedside-emergency-assistance', 'Bedside emergency assistance', true, true),
    capability('smoke-alerting', 'Smoke detector', true, true),
    capability('smart-speaker-setup', 'Smart speaker setup', true, true),
    capability('voice-controlled-lighting', 'Voice-controlled lighting', true, true),
    capability('hands-free-calling', 'Hands-free phone calls', true, true),
    capability('voice-help-requests', 'Simple voice help requests', true, true),
    capability('routine-reminders', 'Medication reminders', true, true),
    capability('appointment-reminders', 'Appointment reminders', true, true),
    capability('morning-evening-routines', 'Morning and evening routines', true, true),
    capability('family-carer-notifications', 'Family or carer notifications', true, true),
    capability('night-time-safety-alerts', 'Night-time movement alert setup', true, true),
    capability('movement-reassurance', 'Bedroom movement notifications', true, true),
    capability('accessible-wardrobe-adaptation', 'Accessible wardrobe adaptation'),
    capability('advanced-bed-transfer-solution', 'Advanced bed transfer solution'),
    capability('electric-adjustable-bed', 'Electric adjustable bed'),
    capability('bed-exit-safety-system', 'Bed exit safety system', true, true),
    capability('automated-curtains-blinds', 'Automated curtains or blinds', true, true),
    capability('bedroom-to-bathroom-route-improvement', 'Bedroom-to-bathroom safety route'),
    capability('specialist-bedroom-layout', 'Specialist bedroom layout'),
    capability('bedroom-door-accessibility-adaptation', 'Bedroom doorway adaptation'),
    capability('dementia-support-bedroom-adaptation', 'Dementia-support bedroom adaptation'),
    capability('automatic-jar-opening', 'Automatic jar opener'),
    capability('easy-grip-kitchen-tools', 'Easy-grip kitchen utensils'),
    capability('non-slip-chopping-support', 'Non-slip chopping board'),
    capability('easy-pour-kettle-support', 'Easy-pour kettle or kettle tipper'),
    capability('anti-fatigue-standing-zone', 'Anti-fatigue mat positioned safely at the preparation area'),
    capability('safer-hob-control', 'Induction hob with automatic shut-off', true, true),
    capability('automatic-gas-shutoff', 'Automatic gas shut-off system, where applicable', true, true),
    capability('kitchen-task-lighting', 'Kitchen task lighting', true, true),
    capability('kitchen-circulation-space', 'Improved kitchen circulation space'),
    capability('kitchen-storage-organisation', 'Frequently used items organised within easy reach'),
    capability('waist-height-storage', 'Frequently used items relocated to waist height'),
    capability('kitchen-motion-alerting', 'Motion detection sensor', true, true),
    capability('voice-cooking-assistance', 'Voice cooking assistance', true, true),
    capability('shopping-list-management', 'Shopping list management', true, true),
    capability('pull-out-pantry-storage', 'Pull-out pantry storage'),
    capability('wider-kitchen-doorway', 'Wider kitchen doorway'),
    capability('seating-height-adjustment', 'Seating height adjustment'),
    capability('sofa-chair-support-handle', 'Sofa or chair support handle'),
    capability('living-room-furniture-positioning', 'Improved furniture positioning'),
    capability('anti-slip-rug-tape', 'Anti-slip rug tape'),
    capability('living-room-circulation-space', 'Improved circulation space'),
    capability('living-room-anti-slip-floor-treatment', 'Anti-slip floor treatment'),
    capability('living-room-secure-floor-coverings', 'Secure floor coverings'),
    capability('furniture-anchoring', 'Furniture anchoring'),
    capability('tv-unit-anchoring', 'TV unit anchoring'),
    capability('corner-protection', 'Corner protection where appropriate'),
    capability('living-room-motion-alerting', 'Motion detection sensor', true, true),
    capability('emergency-voice-assistance', 'Emergency voice assistance', true, true),
    capability('specialist-seating-accessories', 'Specialist seating support accessories'),
    capability('riser-cushion-or-chair-base', 'Riser cushion or chair base adaptation'),
    capability('electric-recliner-chair', 'Electric recliner chair', true, true),
    capability('wider-living-room-doorway', 'Wider living room doorway'),
    capability('stair-handrail', 'Stair handrail'),
    capability('non-slip-stair-treads', 'Non-slip stair treads'),
    capability('high-visibility-stair-edge-markings', 'High-visibility stair edge markings'),
    capability('stair-route-lighting', 'Stair route lighting', true, true),
    capability('entrance-handrail', 'Entrance handrail'),
    capability('entrance-threshold-ramp', 'Low-profile threshold ramp'),
    capability('slip-resistant-entrance-surface', 'Slip-resistant entrance surface'),
    capability('high-visibility-step-edge-markings', 'High-visibility step edge markings'),
    capability('secure-entrance-mat', 'Secure entrance mat'),
    capability('entrance-lever-door-handle', 'Lever door handle'),
    capability('easy-to-use-entrance-lock', 'Easy-to-use lock'),
    capability('smart-video-doorbell', 'Smart video doorbell', true, true),
    capability('two-way-door-communication', 'Two-way communication', true, true),
    capability('live-visitor-view', 'Live visitor view', true, true),
    capability('doorbell-motion-detection', 'Doorbell motion detection', true, true),
    capability('package-detection', 'Package detection, where supported', true, true),
    capability('mobile-door-notifications', 'Mobile door notifications', true, true),
    capability('entrance-family-notifications', 'Family door notifications', true, true),
    capability('motion-activated-entrance-lighting', 'Motion-activated entrance lighting', true, true),
    capability('porch-lighting', 'Porch lighting'),
    capability('wider-entrance-doorway', 'Wider entrance doorway'),
    capability('accessibility-ramp', 'Accessibility ramp'),
    capability('entrance-seating-option', 'Entrance seating'),
    capability('bathroom-wall-mounted-grab-bars', 'Wall-mounted grab bars'),
    capability('bathroom-folding-shower-seat', 'Folding shower seat'),
    capability('bathroom-anti-slip-bath-shower-mat', 'Secure anti-slip bath or shower mat'),
    capability('bathroom-toilet-support-rails', 'Toilet support rails'),
    capability('bathroom-raised-toilet-seat', 'Raised toilet seat'),
    capability('bathroom-anti-slip-floor-treatment', 'Anti-slip floor treatment'),
    capability('bathroom-safer-floor-transition', 'Low-profile transition strip'),
    capability('wet-floor-grip', 'Anti-slip floor treatment'),
    capability('bathroom-task-lighting', 'Bathroom-rated task lighting'),
    capability('bathroom-motion-night-lighting', 'Motion-activated night lighting', true, true),
    capability('easy-see-switches', 'High-contrast switch markers'),
    capability('bathroom-lever-mixer-tap', 'Lever mixer tap'),
    capability('bathroom-lever-shower-controls', 'Lever-operated shower controls'),
    capability('lever-water-control', 'Lever mixer tap'),
    capability('lever-shower-control', 'Lever shower control'),
    capability('bathroom-thermostatic-anti-scald-valve', 'Thermostatic anti-scald valve'),
    capability('anti-scald-control', 'Anti-scald control'),
    capability('hot-water-temperature-setting', 'Hot-water temperature adjustment'),
    capability('threshold-reduction', 'Threshold reduction'),
    capability('bathroom-lever-door-handle', 'Lever door handle'),
    capability('bathroom-easy-release-privacy-lock', 'Easy-release privacy lock'),
    capability('bathroom-door-adjustment', 'Door adjustment to reduce opening resistance'),
    capability('water-leak-alerting', 'Water leak sensor', true, true),
    capability('resident-phone-alerting', 'Resident phone alert setup', true, true),
    capability('nominated-carer-alerting', 'Family or carer alert setup', true, true),
    capability('automatic-water-shutoff', 'Automatic water shut-off valve, where compatible', true, true),
    capability('bathroom-bathtub-step-through-conversion', 'Bathtub step-through conversion'),
    capability('bathroom-wider-doorway-adaptation', 'Wider bathroom doorway'),
    capability('bathroom-vertical-support-rail', 'Vertical support rail'),
    capability('specialist-measurement', 'Specialist measurement and fit check'),
  ],
  products: [
    product('grab-bar', 'Grab bar', 'hardware', 0.1, true),
    product('folding-shower-seat', 'Folding shower seat', 'hardware', 0.1, true),
    product('raised-toilet-seat', 'Raised toilet seat', 'hardware', 0.1, true),
    product('toilet-support-rail', 'Toilet support rail', 'hardware', 0.1, true),
    product('anti-slip-treatment', 'Anti-slip floor treatment', 'material', 0.21, true),
    product('anti-slip-mat', 'Secure anti-slip bath mat', 'hardware', 0.21, false),
    product('bathroom-led-light', 'Bathroom LED light', 'hardware', 0.21, false),
    product('high-contrast-switch-control', 'Easier-to-see switch or control marking', 'material', 0.21, false),
    product('motion-sensor', 'Motion sensor', 'device', 0.21, false, true),
    product('lever-mixer-tap', 'Lever mixer tap', 'hardware', 0.21, false),
    product('lever-operated-shower-control', 'Lever-operated shower control', 'hardware', 0.21, false),
    product('thermostatic-valve', 'Thermostatic anti-scald valve', 'hardware', 0.21, false),
    product('hot-water-setting-service', 'Safer hot-water temperature setting', 'service', 0.21, false),
    product('low-threshold-transition', 'Low-threshold transition strip', 'material', 0.21, true),
    product('bath-step-through-conversion', 'Bathtub step-through conversion', 'service', 0.21, true),
    product('bathroom-wider-doorway-service', 'Wider bathroom doorway service', 'service', 0.21, true),
    product('vertical-support-rail', 'Vertical support rail', 'hardware', 0.1, true),
    product('lever-door-handle', 'Lever door handle', 'hardware', 0.21, false),
    product('easy-release-privacy-lock', 'Easy-release privacy lock', 'hardware', 0.21, false),
    product('door-adjustment-service', 'Bathroom door adjustment', 'service', 0.21, false),
    product('water-leak-sensor', 'Water leak sensor', 'device', 0.21, false, true),
    product('resident-alert-setup', 'Resident phone alert setup', 'service', 0.21, false, true),
    product('carer-alert-setup', 'Family or carer alert setup', 'service', 0.21, false, true),
    product('automatic-water-shutoff-valve', 'Automatic water shut-off valve', 'device', 0.21, false, true),
    product('smart-speaker', 'Smart speaker', 'device', 0.21, false, true),
    product('bedside-light', 'Bedside light', 'hardware', 0.21, false),
    product('low-level-floor-light', 'Low-level floor light', 'hardware', 0.21, false),
    product('bed-support-handle', 'Bed support handle', 'hardware', 0.1, true),
    product('bed-height-adjustment-service', 'Bed height adjustment service', 'service', 0.21, true),
    product('bed-positioning-service', 'Improved bed positioning service', 'service', 0.21, true),
    product('bed-to-door-route-service', 'Bed-to-door route clearance service', 'service', 0.21, true),
    product('bedroom-floor-treatment', 'Bedroom anti-slip floor treatment', 'material', 0.21, true),
    product('secure-floor-coverings-service', 'Secure floor coverings service', 'service', 0.21, true),
    product('cable-management-kit', 'Cable management kit', 'material', 0.21, false),
    product('storage-reach-kit', 'Storage reach and labelling kit', 'material', 0.21, false),
    product('emergency-call-button', 'Emergency call button', 'device', 0.21, false, true),
    product('wearable-emergency-pendant', 'Wearable emergency pendant', 'device', 0.21, false, true),
    product('bedside-emergency-button', 'Bedside emergency assistance button', 'device', 0.21, false, true),
    product('smoke-detector', 'Smoke detector', 'device', 0.21, false, true),
    product('routine-setup-service', 'Routine setup service', 'software', 0.21, false, true),
    product('accessible-wardrobe-adaptation-service', 'Accessible wardrobe adaptation service', 'service', 0.21, true),
    product('advanced-bed-transfer-solution-service', 'Advanced bed transfer solution service', 'service', 0.1, true, true),
    product('electric-adjustable-bed-product', 'Electric adjustable bed', 'hardware', 0.1, true, true),
    product('bed-exit-safety-system-product', 'Bed exit safety system', 'device', 0.21, false, true),
    product('automated-curtain-blind-system', 'Automated curtain or blind system', 'device', 0.21, false, true),
    product('bedroom-bathroom-route-service', 'Bedroom-to-bathroom route safety service', 'service', 0.21, true),
    product('specialist-bedroom-layout-service', 'Specialist bedroom layout service', 'service', 0.21, true),
    product('bedroom-door-accessibility-service', 'Bedroom doorway adaptation service', 'service', 0.21, true),
    product('dementia-support-bedroom-service', 'Dementia-support bedroom adaptation service', 'service', 0.21, true),
    product('automatic-jar-opener', 'Automatic jar opener', 'hardware', 0.21, false),
    product('easy-grip-kitchen-utensils', 'Easy-grip kitchen utensils', 'hardware', 0.21, false),
    product('non-slip-chopping-board', 'Non-slip chopping board', 'hardware', 0.21, false),
    product('easy-pour-kettle-tipper', 'Easy-pour kettle or kettle tipper', 'hardware', 0.21, false),
    product('anti-fatigue-kitchen-mat', 'Anti-fatigue kitchen mat', 'hardware', 0.21, false),
    product('induction-hob-automatic-shutoff', 'Induction hob with automatic shut-off', 'device', 0.21, true, true),
    product('automatic-gas-shutoff-system', 'Automatic gas shut-off system', 'device', 0.21, true, true),
    product('kitchen-task-light', 'Kitchen task light', 'hardware', 0.21, false, true),
    product('kitchen-storage-reorganisation-service', 'Kitchen storage reorganisation service', 'service', 0.21, false),
    product('pull-out-pantry-hardware', 'Pull-out pantry hardware', 'hardware', 0.21, true, true),
    product('wider-kitchen-doorway-service', 'Wider kitchen doorway service', 'service', 0.21, true),
    product('seating-height-adjustment-service', 'Seating height adjustment service', 'service', 0.21, true),
    product('sofa-chair-support-handle-product', 'Sofa or chair support handle', 'hardware', 0.1, true, true),
    product('living-room-furniture-positioning-service', 'Living room furniture positioning service', 'service', 0.21, false),
    product('anti-slip-rug-tape-product', 'Anti-slip rug tape', 'material', 0.21, false),
    product('living-room-route-clearance-service', 'Living room circulation clearance service', 'service', 0.21, false),
    product('living-room-floor-treatment', 'Living room anti-slip floor treatment', 'material', 0.21, true),
    product('furniture-anchoring-kit', 'Furniture anchoring kit', 'hardware', 0.21, true),
    product('tv-unit-anchoring-kit', 'TV unit anchoring kit', 'hardware', 0.21, true),
    product('corner-protection-kit', 'Corner protection kit', 'hardware', 0.21, false),
    product('seating-support-accessories', 'Specialist seating support accessories', 'hardware', 0.1, true, true),
    product('riser-cushion-chair-base', 'Riser cushion or chair base adaptation', 'hardware', 0.1, true, true),
    product('electric-recliner-chair-product', 'Electric recliner chair', 'hardware', 0.1, true, true),
    product('wider-living-room-doorway-service', 'Wider living room doorway service', 'service', 0.21, true),
    product('stair-handrail-product', 'Stair handrail', 'hardware', 0.1, true),
    product('non-slip-stair-treads-product', 'Non-slip stair treads', 'material', 0.21, true),
    product('stair-edge-marking-strips', 'High-visibility stair edge marking strips', 'material', 0.21, false),
    product('stair-route-lighting-product', 'Stair route lighting', 'hardware', 0.21, true, true),
    product('entrance-handrail-product', 'Entrance handrail', 'hardware', 0.1, true),
    product('threshold-ramp-product', 'Low-profile threshold ramp', 'hardware', 0.1, true),
    product('entrance-surface-treatment', 'Slip-resistant entrance surface treatment', 'material', 0.21, true),
    product('step-edge-marking-strips', 'High-visibility step edge marking strips', 'material', 0.21, false),
    product('secure-entrance-mat-product', 'Secure entrance mat', 'hardware', 0.21, false),
    product('easy-use-entrance-lock', 'Easy-to-use entrance lock', 'hardware', 0.21, false),
    product('smart-video-doorbell-product', 'Smart video doorbell', 'device', 0.21, false, true),
    product('doorbell-communications-setup', 'Video doorbell communication setup', 'software', 0.21, false, true),
    product('doorbell-alert-setup', 'Video doorbell alert setup', 'software', 0.21, false, true),
    product('entrance-motion-light', 'Motion-activated entrance light', 'hardware', 0.21, true, true),
    product('porch-light-product', 'Porch light', 'hardware', 0.21, true),
    product('wider-entrance-doorway-service', 'Wider entrance doorway service', 'service', 0.21, true),
    product('accessibility-ramp-service', 'Accessibility ramp service', 'service', 0.1, true, true),
    product('entrance-seating-product', 'Entrance seating', 'hardware', 0.1, true, true),
  ],
  installationTasks: [
    task('inspect-fixing-surface', 'Inspect fixing surface', 25, 'assessment', true, false),
    task('install-support-rail', 'Install support rail', 45, 'general', true, true),
    task('fit-shower-seat', 'Fit shower seat', 50, 'general', true, true),
    task('apply-anti-slip-treatment', 'Apply anti-slip treatment', 60, 'general', true, false),
    task('fit-water-control', 'Fit safer water control', 55, 'plumbing', true, true),
    task('set-hot-water-temperature', 'Set safer hot-water temperature', 30, 'plumbing', true, false),
    task('reduce-threshold', 'Reduce or mark threshold', 45, 'general', true, true),
    task('fit-door-hardware', 'Fit bathroom door hardware', 45, 'general', true, false),
    task('adjust-bathroom-door', 'Adjust bathroom door resistance', 35, 'general', true, false),
    task('fit-water-leak-sensor', 'Fit and test water leak sensor', 30, 'smart_home', false, false),
    task('configure-bathroom-alerting', 'Configure bathroom alerting', 40, 'smart_home', false, false),
    task('fit-water-shutoff-valve', 'Fit compatible water shut-off valve', 75, 'plumbing', true, true),
    task('configure-motion-lighting', 'Configure motion lighting', 35, 'smart_home', false, false),
    task('pair-smart-speaker', 'Pair and configure smart speaker', 45, 'smart_home', false, false),
    task('test-emergency-contact', 'Test emergency contact flow', 20, 'smart_home', false, false),
    task('configure-bedroom-emergency-support', 'Configure bedroom emergency support', 40, 'smart_home', true, false),
    task('reposition-furniture', 'Reposition furniture', 30, 'general', false, false),
    task('measure-specialist-adaptation', 'Measure specialist adaptation', 45, 'assessment', true, true),
    task('set-up-kitchen-prep-support', 'Set up safer food preparation support', 30, 'general', false, false),
    task('assess-kitchen-cooking-safety', 'Assess kitchen cooking safety', 35, 'assessment', true, false),
    task('configure-kitchen-cooking-safeguard', 'Configure kitchen cooking safeguard', 50, 'smart_home', true, false),
    task('install-kitchen-task-lighting', 'Install kitchen task lighting', 60, 'electrical', true, true),
    task('improve-kitchen-standing-route', 'Improve kitchen standing and walking route', 45, 'general', false, false),
    task('organise-kitchen-storage', 'Organise safer kitchen storage', 35, 'general', false, false),
    task('configure-kitchen-alerting', 'Configure kitchen safety alerting', 45, 'smart_home', false, false),
    task('configure-connected-kitchen', 'Configure connected kitchen routines', 55, 'smart_home', false, false),
    task('fit-pull-out-pantry', 'Fit pull-out pantry storage', 90, 'carpentry', true, true),
    task('measure-kitchen-doorway', 'Measure kitchen doorway adaptation', 45, 'assessment', true, true),
    task('adjust-living-room-seating', 'Adjust living room seating height', 35, 'general', false, false),
    task('fit-chair-support-handle', 'Fit sofa or chair support handle', 45, 'general', true, true),
    task('improve-living-room-route', 'Clear and secure living room routes', 45, 'general', false, false),
    task('anchor-living-room-furniture', 'Anchor living room furniture or TV unit', 60, 'general', true, true),
    task('configure-living-room-alerting', 'Configure living room safety alerting', 45, 'smart_home', false, false),
    task('assess-advanced-seating', 'Assess advanced seating solution', 45, 'assessment', true, true),
    task('install-electric-recliner', 'Install and test electric recliner chair', 60, 'general', true, true),
    task('measure-living-room-doorway', 'Measure living room doorway adaptation', 45, 'assessment', true, true),
    task('measure-stair-route', 'Measure stair route', 45, 'assessment', true, true),
    task('install-stair-handrail', 'Install stair handrail', 75, 'general', true, true),
    task('fit-non-slip-stair-treads', 'Fit non-slip stair treads', 60, 'general', true, true),
    task('mark-stair-edge-contrast', 'Apply high-visibility stair edge markings', 45, 'general', false, true),
    task('install-stair-route-lighting', 'Install stair route lighting', 60, 'electrical', true, true),
    task('install-entrance-handrail', 'Install entrance handrail', 55, 'general', true, true),
    task('fit-threshold-ramp', 'Fit threshold ramp', 45, 'general', true, true),
    task('improve-entrance-surface', 'Improve entrance slip resistance', 60, 'general', true, false),
    task('mark-entrance-step-edges', 'Apply entrance step edge markings', 30, 'general', false, false),
    task('fit-secure-entrance-mat', 'Fit secure entrance mat', 20, 'general', false, false),
    task('fit-entrance-door-hardware', 'Fit entrance door handle or lock', 45, 'general', true, false),
    task('configure-video-doorbell', 'Configure smart video doorbell', 55, 'smart_home', false, false),
    task('install-entrance-lighting', 'Install entrance lighting', 60, 'electrical', true, true),
    task('measure-entrance-doorway', 'Measure entrance doorway adaptation', 45, 'assessment', true, true),
    task('assess-accessibility-ramp', 'Assess accessibility ramp route', 60, 'assessment', true, true),
    task('fit-entrance-seating', 'Fit entrance seating', 45, 'general', true, true),
  ],
  relations: [
    ...packageOutcomeRelations(),
    ...outcomeCapabilityRelations(),
    ...capabilityProductRelations(),
    ...capabilityTaskRelations(),
  ],
}

function packageRecord(
  id: string,
  roomId: string,
  section: MasterServiceCatalogue['sections'][number]['id'],
  customerName: { en: string; es: string },
  internalName: string,
  sortOrder: number,
  quote = false,
  copy: {
    shortDescription?: { en: string; es: string }
    customerBenefit?: { en: string; es: string }
  } = {},
): MasterServiceCatalogue['packages'][number] {
  return {
    id,
    slug: id,
    roomId,
    section,
    customerName,
    internalName,
    shortDescription: copy.shortDescription ?? { en: 'A coordinated package of customer outcomes.', es: 'Un paquete coordinado de resultados para el cliente.' },
    customerBenefit: copy.customerBenefit ?? { en: 'One clear plan instead of disconnected products.', es: 'Un plan claro en lugar de productos sueltos.' },
    active: true,
    sortOrder,
    pricingType: quote ? 'quote' : 'from',
    fromPrice: quote ? undefined : 0,
    vatRate: 0.21,
    requiresAssessment: true,
    requiresSiteVisit: quote,
    requiresQuote: quote,
    wizardVisible: true,
    websiteVisible: true,
    proposalVisible: true,
    inspectorVisible: true,
    adminVisible: true,
    version: '1.0.0',
    createdAt: now,
    updatedAt: now,
  }
}

function outcome(
  id: string,
  roomId: MasterServiceCatalogue['rooms'][number]['id'],
  section: MasterServiceCatalogue['sections'][number]['id'],
  packageId: string,
  en: string,
  es: string,
  category: string,
  descEn: string,
  descEs: string,
  benefitEn: string,
  benefitEs: string,
  priority: 'essential' | 'recommended' | 'optional',
  wizardAreas: MasterServiceCatalogue['outcomes'][number]['wizardAreas'],
  sortOrder: number,
  options: {
    grantEligible?: boolean
    legacyId?: string
    quoteOnly?: boolean
    requiresCompatibilityCheck?: boolean
    requiresSmartSpeaker?: boolean
    technologyEnabled?: boolean
    voiceEnabled?: boolean
  } = {},
): MasterServiceCatalogue['outcomes'][number] {
  return {
    id,
    legacyId: options.legacyId,
    slug: id,
    roomId,
    section,
    packageId,
    customerName: { en, es },
    internalName: en,
    category,
    shortDescription: { en: descEn, es: descEs },
    detailedDescription: { en: descEn, es: descEs },
    customerBenefit: { en: benefitEn, es: benefitEs },
    active: true,
    sortOrder,
    priority,
    pricingType: options.quoteOnly ? 'quote' : 'included-in-package',
    vatRate: 0.21,
    requiresAssessment: true,
    requiresMeasurement: options.quoteOnly ?? false,
    requiresSiteVisit: options.quoteOnly ?? false,
    requiresCompatibilityCheck: options.requiresCompatibilityCheck ?? options.requiresSmartSpeaker ?? false,
    requiresQuote: options.quoteOnly ?? false,
    grantEligible: options.grantEligible ?? false,
    technologyEnabled: options.technologyEnabled ?? false,
    voiceEnabled: options.voiceEnabled ?? false,
    requiresSmartSpeaker: options.requiresSmartSpeaker ?? false,
    wizardAreas,
    wizardTags: [roomId, section, priority],
    websiteVisible: true,
    wizardVisible: true,
    proposalVisible: true,
    inspectorVisible: true,
    adminVisible: true,
    version: '1.0.0',
    createdAt: now,
    updatedAt: now,
  }
}

function capability(
  id: string,
  name: string,
  technologyEnabled = false,
  requiresCompatibilityCheck = false,
): MasterServiceCatalogue['capabilities'][number] {
  return {
    id,
    slug: id,
    name,
    description: name,
    active: true,
    technologyEnabled,
    requiresCompatibilityCheck,
    implementationNotes: technologyEnabled ? 'Configure only with compatible devices and consent.' : undefined,
  }
}

function product(
  id: string,
  name: string,
  productType: MasterServiceCatalogue['products'][number]['productType'],
  vatRate: number,
  grantEligible: boolean,
  requiresCompatibilityCheck = false,
): MasterServiceCatalogue['products'][number] {
  return {
    id,
    slug: id,
    name,
    productType,
    internalDescription: name,
    active: true,
    vatRate,
    currency: 'EUR',
    quantityType: 'per_unit',
    stockTracked: productType !== 'service',
    grantEligible,
    installationRequired: true,
    requiresCompatibilityCheck,
    version: '1.0.0',
  }
}

function task(
  id: string,
  name: string,
  estimatedMinutes: number,
  skillType: MasterServiceCatalogue['installationTasks'][number]['skillType'],
  requiresSiteVisit: boolean,
  requiresMeasurement: boolean,
): MasterServiceCatalogue['installationTasks'][number] {
  return {
    id,
    slug: id,
    name,
    description: name,
    active: true,
    estimatedMinutes,
    skillType,
    installerType: skillType === 'assessment' ? 'casamia' : 'partner',
    labourRate: 50,
    requiresSiteVisit,
    requiresMeasurement,
    safetyChecklist: ['Confirm resident needs', 'Check surface and route safety'],
    completionChecklist: ['Test installation', 'Explain use to customer'],
    version: '1.0.0',
  }
}

function relation(type: MasterServiceCatalogue['relations'][number]['type'], fromId: string, toId: string, sortOrder: number, required = true) {
  return {
    id: `${type}-${fromId}-${toId}`,
    type,
    fromId,
    toId,
    required,
    defaultIncluded: required,
    optionalUpgrade: !required,
    minimumQuantity: required ? 1 : 0,
    sortOrder,
  }
}

function packageOutcomeRelations() {
  return getMasterServiceCatalogueSeedOutcomeIds().map(([packageId, outcomeId], index) =>
    relation('packageOutcome', packageId, outcomeId, index + 1),
  )
}

function getMasterServiceCatalogueSeedOutcomeIds() {
  return [
  ['bathroom-home-safety-package', 'bathroom-safer-bathing'],
  ['bathroom-home-safety-package', 'bathroom-safer-toilet-transfers'],
  ['bathroom-home-safety-package', 'bathroom-slip-prevention'],
  ['bathroom-home-safety-package', 'bathroom-improved-visibility'],
  ['bathroom-home-safety-package', 'bathroom-easier-tap-control'],
  ['bathroom-home-safety-package', 'bathroom-temperature-safety'],
  ['bathroom-home-safety-package', 'bathroom-safer-access'],
  ['bathroom-home-safety-package', 'bathroom-safety-monitoring'],
  ['bathroom-connected-room', 'bathroom-connected-guidance'],
  ['bathroom-optional-adaptations', 'bathroom-bathtub-step-through'],
  ['bathroom-optional-adaptations', 'bathroom-wider-doorway'],
  ['bathroom-optional-adaptations', 'bathroom-vertical-support'],
  ['bedroom-home-safety-package', 'bedroom-safer-lighting'],
  ['bedroom-home-safety-package', 'bedroom-easier-bed-transfers'],
  ['bedroom-home-safety-package', 'bedroom-safer-walking-routes'],
  ['bedroom-home-safety-package', 'bedroom-slip-resistance'],
  ['bedroom-home-safety-package', 'bedroom-fire-safety'],
  ['bedroom-connected-room', 'bedroom-voice-assistance'],
  ['bedroom-connected-room', 'bedroom-smart-lighting'],
  ['bedroom-connected-room', 'bedroom-family-reassurance'],
  ['bedroom-connected-room', 'bedroom-daily-living-support'],
  ['bedroom-connected-room', 'bedroom-connected-safety'],
  ['bedroom-optional-adaptations', 'bedroom-emergency-support'],
  ['bedroom-optional-adaptations', 'bedroom-accessible-wardrobe'],
  ['bedroom-optional-adaptations', 'bedroom-advanced-bed-transfer'],
  ['bedroom-optional-adaptations', 'bedroom-electric-adjustable-bed'],
  ['bedroom-optional-adaptations', 'bedroom-bed-exit-safety-system'],
  ['bedroom-optional-adaptations', 'bedroom-automated-curtains'],
  ['bedroom-optional-adaptations', 'bedroom-bathroom-safety-route'],
  ['bedroom-optional-adaptations', 'bedroom-specialist-layout'],
  ['bedroom-optional-adaptations', 'bedroom-door-accessibility'],
  ['bedroom-optional-adaptations', 'bedroom-dementia-support'],
  ['kitchen-home-safety-package', 'kitchen-safer-food-preparation'],
  ['kitchen-home-safety-package', 'kitchen-safer-cooking'],
  ['kitchen-home-safety-package', 'kitchen-improved-lighting'],
  ['kitchen-home-safety-package', 'kitchen-safer-movement'],
  ['kitchen-home-safety-package', 'kitchen-easier-storage'],
  ['kitchen-home-safety-package', 'kitchen-safety-monitoring'],
  ['kitchen-connected-room', 'kitchen-connected-experience'],
  ['kitchen-optional-adaptations', 'kitchen-pull-out-pantry-storage'],
  ['kitchen-optional-adaptations', 'kitchen-wider-doorway'],
  ['living-room-home-safety-package', 'living-room-easier-sitting-standing'],
  ['living-room-home-safety-package', 'living-room-safer-room'],
  ['living-room-home-safety-package', 'living-room-improved-lighting'],
  ['living-room-home-safety-package', 'living-room-slip-prevention'],
  ['living-room-home-safety-package', 'living-room-safer-furniture'],
  ['living-room-home-safety-package', 'living-room-safety-monitoring'],
  ['living-room-connected-room', 'living-room-connected-experience'],
  ['living-room-optional-adaptations', 'living-room-advanced-seating'],
  ['living-room-optional-adaptations', 'living-room-electric-recliner-chair'],
  ['living-room-optional-adaptations', 'living-room-wider-doorway'],
  ['living-room-optional-adaptations', 'living-room-stair-safety'],
  ['entrance-home-safety-package', 'entrance-safer-access'],
  ['entrance-home-safety-package', 'entrance-easier-door-access'],
  ['entrance-home-safety-package', 'entrance-improved-lighting'],
  ['entrance-connected-room', 'entrance-connected-door-awareness'],
  ['entrance-optional-adaptations', 'entrance-wider-doorway'],
  ['entrance-optional-adaptations', 'entrance-accessibility-ramp'],
  ['entrance-optional-adaptations', 'entrance-seating'],
  ]
}

function outcomeCapabilityRelations() {
  const map: Record<string, string[]> = {
    'bathroom-safer-bathing': ['bathroom-wall-mounted-grab-bars', 'bathroom-folding-shower-seat', 'bathroom-anti-slip-bath-shower-mat'],
    'bathroom-safer-toilet-transfers': ['bathroom-toilet-support-rails', 'bathroom-raised-toilet-seat'],
    'bathroom-slip-prevention': ['bathroom-anti-slip-floor-treatment', 'bathroom-safer-floor-transition'],
    'bathroom-improved-visibility': ['bathroom-motion-night-lighting', 'easy-see-switches'],
    'bathroom-easier-tap-control': ['bathroom-lever-mixer-tap', 'bathroom-lever-shower-controls'],
    'bathroom-temperature-safety': ['bathroom-thermostatic-anti-scald-valve', 'hot-water-temperature-setting'],
    'bathroom-safer-access': ['bathroom-lever-door-handle', 'bathroom-easy-release-privacy-lock', 'bathroom-door-adjustment'],
    'bathroom-safety-monitoring': ['water-leak-alerting', 'resident-phone-alerting', 'nominated-carer-alerting', 'automatic-water-shutoff'],
    'bathroom-connected-guidance': ['bathroom-motion-night-lighting', 'bathroom-task-lighting'],
    'bathroom-bathtub-step-through': ['specialist-measurement', 'bathroom-bathtub-step-through-conversion'],
    'bathroom-wider-doorway': ['specialist-measurement', 'bathroom-wider-doorway-adaptation'],
    'bathroom-vertical-support': ['specialist-measurement', 'bathroom-vertical-support-rail'],
    'bedroom-safer-lighting': ['bedroom-motion-night-lighting', 'bedside-lighting'],
    'bedroom-easier-bed-transfers': ['discreet-transfer-support', 'bed-height-optimisation', 'bed-positioning-adjustment'],
    'bedroom-safer-walking-routes': ['loose-rug-securing', 'cable-management', 'furniture-repositioning', 'bed-to-door-clear-route'],
    'bedroom-slip-resistance': ['bedroom-anti-slip-floor-treatment', 'bedroom-secure-floor-coverings'],
    'bedroom-emergency-support': ['emergency-call-access', 'wearable-emergency-support', 'bedside-emergency-assistance'],
    'bedroom-fire-safety': ['smoke-alerting'],
    'bedroom-voice-assistance': ['smart-speaker-setup', 'hands-free-calling', 'voice-help-requests'],
    'bedroom-smart-lighting': ['voice-controlled-lighting', 'bedroom-motion-night-lighting'],
    'bedroom-family-reassurance': ['family-carer-notifications'],
    'bedroom-daily-living-support': ['routine-reminders', 'appointment-reminders', 'morning-evening-routines'],
    'bedroom-connected-safety': ['movement-reassurance', 'night-time-safety-alerts'],
    'bedroom-accessible-wardrobe': ['accessible-wardrobe-adaptation'],
    'bedroom-advanced-bed-transfer': ['advanced-bed-transfer-solution'],
    'bedroom-electric-adjustable-bed': ['electric-adjustable-bed'],
    'bedroom-bed-exit-safety-system': ['bed-exit-safety-system'],
    'bedroom-automated-curtains': ['automated-curtains-blinds'],
    'bedroom-bathroom-safety-route': ['bedroom-to-bathroom-route-improvement'],
    'bedroom-specialist-layout': ['specialist-bedroom-layout'],
    'bedroom-door-accessibility': ['bedroom-door-accessibility-adaptation'],
    'bedroom-dementia-support': ['dementia-support-bedroom-adaptation'],
    'kitchen-safer-food-preparation': ['lever-water-control', 'automatic-jar-opening', 'easy-grip-kitchen-tools', 'non-slip-chopping-support', 'easy-pour-kettle-support'],
    'kitchen-safer-cooking': ['safer-hob-control', 'automatic-gas-shutoff'],
    'kitchen-improved-lighting': ['motion-activated-lighting'],
    'kitchen-safer-movement': ['wet-floor-grip', 'loose-rug-securing', 'kitchen-circulation-space', 'anti-fatigue-standing-zone'],
    'kitchen-easier-storage': ['kitchen-storage-organisation', 'waist-height-storage'],
    'kitchen-safety-monitoring': ['smoke-alerting', 'water-leak-alerting', 'kitchen-motion-alerting'],
    'kitchen-connected-experience': ['smart-speaker-setup', 'voice-controlled-lighting', 'voice-cooking-assistance', 'shopping-list-management', 'routine-reminders', 'hands-free-calling', 'family-carer-notifications'],
    'kitchen-pull-out-pantry-storage': ['pull-out-pantry-storage'],
    'kitchen-wider-doorway': ['wider-kitchen-doorway'],
    'living-room-easier-sitting-standing': ['seating-height-adjustment', 'sofa-chair-support-handle', 'living-room-furniture-positioning'],
    'living-room-safer-room': ['loose-rug-securing', 'anti-slip-rug-tape', 'cable-management', 'living-room-circulation-space'],
    'living-room-improved-lighting': ['motion-activated-lighting'],
    'living-room-slip-prevention': ['living-room-anti-slip-floor-treatment', 'living-room-secure-floor-coverings'],
    'living-room-safer-furniture': ['furniture-anchoring', 'tv-unit-anchoring', 'corner-protection'],
    'living-room-safety-monitoring': ['smoke-alerting', 'living-room-motion-alerting'],
    'living-room-connected-experience': ['smart-speaker-setup', 'voice-controlled-lighting', 'hands-free-calling', 'routine-reminders', 'family-carer-notifications', 'emergency-voice-assistance'],
    'living-room-advanced-seating': ['specialist-seating-accessories', 'riser-cushion-or-chair-base'],
    'living-room-electric-recliner-chair': ['electric-recliner-chair'],
    'living-room-wider-doorway': ['wider-living-room-doorway'],
    'living-room-stair-safety': ['stair-handrail', 'non-slip-stair-treads', 'high-visibility-stair-edge-markings', 'stair-route-lighting'],
    'entrance-safer-access': ['entrance-handrail', 'entrance-threshold-ramp', 'slip-resistant-entrance-surface', 'high-visibility-step-edge-markings', 'secure-entrance-mat'],
    'entrance-easier-door-access': ['entrance-lever-door-handle', 'easy-to-use-entrance-lock'],
    'entrance-improved-lighting': ['motion-activated-entrance-lighting', 'porch-lighting'],
    'entrance-connected-door-awareness': ['smart-video-doorbell', 'two-way-door-communication', 'live-visitor-view', 'doorbell-motion-detection', 'package-detection', 'mobile-door-notifications', 'entrance-family-notifications'],
    'entrance-wider-doorway': ['wider-entrance-doorway'],
    'entrance-accessibility-ramp': ['accessibility-ramp'],
    'entrance-seating': ['entrance-seating-option'],
  }

  return Object.entries(map).flatMap(([outcomeId, capabilityIds]) =>
    capabilityIds.map((capabilityId, index) => relation('outcomeCapability', outcomeId, capabilityId, index + 1)),
  )
}

function capabilityProductRelations() {
  const map: Record<string, string[]> = {
    'bathroom-wall-mounted-grab-bars': ['grab-bar'],
    'bathroom-folding-shower-seat': ['folding-shower-seat'],
    'bathroom-anti-slip-bath-shower-mat': ['anti-slip-mat'],
    'bathroom-toilet-support-rails': ['toilet-support-rail'],
    'bathroom-raised-toilet-seat': ['raised-toilet-seat'],
    'bathroom-anti-slip-floor-treatment': ['anti-slip-treatment'],
    'bathroom-safer-floor-transition': ['low-threshold-transition'],
    'wet-floor-grip': ['anti-slip-treatment', 'anti-slip-mat'],
    'bathroom-task-lighting': ['bathroom-led-light'],
    'bathroom-motion-night-lighting': ['motion-sensor', 'bathroom-led-light'],
    'easy-see-switches': ['high-contrast-switch-control'],
    'bathroom-lever-mixer-tap': ['lever-mixer-tap'],
    'bathroom-lever-shower-controls': ['lever-operated-shower-control'],
    'motion-activated-lighting': ['motion-sensor', 'low-level-floor-light'],
    'lever-water-control': ['lever-mixer-tap'],
    'lever-shower-control': ['lever-operated-shower-control'],
    'bathroom-thermostatic-anti-scald-valve': ['thermostatic-valve'],
    'anti-scald-control': ['thermostatic-valve'],
    'hot-water-temperature-setting': ['hot-water-setting-service'],
    'threshold-reduction': ['low-threshold-transition'],
    'bathroom-lever-door-handle': ['lever-door-handle'],
    'bathroom-easy-release-privacy-lock': ['easy-release-privacy-lock'],
    'bathroom-door-adjustment': ['door-adjustment-service'],
    'water-leak-alerting': ['water-leak-sensor'],
    'resident-phone-alerting': ['resident-alert-setup'],
    'nominated-carer-alerting': ['carer-alert-setup'],
    'automatic-water-shutoff': ['automatic-water-shutoff-valve'],
    'bathroom-bathtub-step-through-conversion': ['bath-step-through-conversion'],
    'bathroom-wider-doorway-adaptation': ['bathroom-wider-doorway-service'],
    'bathroom-vertical-support-rail': ['vertical-support-rail'],
    'bedside-lighting': ['bedside-light'],
    'bedroom-motion-night-lighting': ['motion-sensor', 'low-level-floor-light'],
    'low-level-night-lighting': ['low-level-floor-light'],
    'bed-height-optimisation': ['bed-height-adjustment-service'],
    'bed-positioning-adjustment': ['bed-positioning-service'],
    'bed-to-door-clear-route': ['bed-to-door-route-service'],
    'bedroom-anti-slip-floor-treatment': ['bedroom-floor-treatment'],
    'bedroom-secure-floor-coverings': ['secure-floor-coverings-service'],
    'loose-rug-securing': ['anti-slip-mat'],
    'cable-management': ['cable-management-kit'],
    'accessible-storage-arrangement': ['storage-reach-kit'],
    'discreet-transfer-support': ['bed-support-handle'],
    'wearable-emergency-support': ['wearable-emergency-pendant'],
    'bedside-emergency-assistance': ['bedside-emergency-button'],
    'smart-speaker-setup': ['smart-speaker'],
    'voice-controlled-lighting': ['smart-speaker', 'low-level-floor-light'],
    'hands-free-calling': ['smart-speaker'],
    'voice-help-requests': ['smart-speaker'],
    'routine-reminders': ['smart-speaker', 'routine-setup-service'],
    'appointment-reminders': ['smart-speaker', 'routine-setup-service'],
    'morning-evening-routines': ['smart-speaker', 'routine-setup-service'],
    'family-carer-notifications': ['smart-speaker'],
    'night-time-safety-alerts': ['smart-speaker', 'motion-sensor'],
    'movement-reassurance': ['motion-sensor'],
    'emergency-call-access': ['emergency-call-button', 'smart-speaker'],
    'smoke-alerting': ['smoke-detector'],
    'accessible-wardrobe-adaptation': ['accessible-wardrobe-adaptation-service'],
    'advanced-bed-transfer-solution': ['advanced-bed-transfer-solution-service'],
    'electric-adjustable-bed': ['electric-adjustable-bed-product'],
    'bed-exit-safety-system': ['bed-exit-safety-system-product'],
    'automated-curtains-blinds': ['automated-curtain-blind-system'],
    'bedroom-to-bathroom-route-improvement': ['bedroom-bathroom-route-service'],
    'specialist-bedroom-layout': ['specialist-bedroom-layout-service'],
    'bedroom-door-accessibility-adaptation': ['bedroom-door-accessibility-service'],
    'dementia-support-bedroom-adaptation': ['dementia-support-bedroom-service'],
    'automatic-jar-opening': ['automatic-jar-opener'],
    'easy-grip-kitchen-tools': ['easy-grip-kitchen-utensils'],
    'non-slip-chopping-support': ['non-slip-chopping-board'],
    'easy-pour-kettle-support': ['easy-pour-kettle-tipper'],
    'anti-fatigue-standing-zone': ['anti-fatigue-kitchen-mat'],
    'safer-hob-control': ['induction-hob-automatic-shutoff'],
    'automatic-gas-shutoff': ['automatic-gas-shutoff-system'],
    'kitchen-task-lighting': ['kitchen-task-light'],
    'kitchen-circulation-space': ['kitchen-storage-reorganisation-service'],
    'kitchen-storage-organisation': ['kitchen-storage-reorganisation-service'],
    'waist-height-storage': ['kitchen-storage-reorganisation-service'],
    'kitchen-motion-alerting': ['motion-sensor'],
    'voice-cooking-assistance': ['smart-speaker'],
    'shopping-list-management': ['smart-speaker'],
    'pull-out-pantry-storage': ['pull-out-pantry-hardware'],
    'wider-kitchen-doorway': ['wider-kitchen-doorway-service'],
    'seating-height-adjustment': ['seating-height-adjustment-service'],
    'sofa-chair-support-handle': ['sofa-chair-support-handle-product'],
    'living-room-furniture-positioning': ['living-room-furniture-positioning-service'],
    'anti-slip-rug-tape': ['anti-slip-rug-tape-product'],
    'living-room-circulation-space': ['living-room-route-clearance-service'],
    'living-room-anti-slip-floor-treatment': ['living-room-floor-treatment'],
    'living-room-secure-floor-coverings': ['secure-floor-coverings-service'],
    'furniture-anchoring': ['furniture-anchoring-kit'],
    'tv-unit-anchoring': ['tv-unit-anchoring-kit'],
    'corner-protection': ['corner-protection-kit'],
    'living-room-motion-alerting': ['motion-sensor'],
    'emergency-voice-assistance': ['smart-speaker'],
    'specialist-seating-accessories': ['seating-support-accessories'],
    'riser-cushion-or-chair-base': ['riser-cushion-chair-base'],
    'electric-recliner-chair': ['electric-recliner-chair-product'],
    'wider-living-room-doorway': ['wider-living-room-doorway-service'],
    'stair-handrail': ['stair-handrail-product'],
    'non-slip-stair-treads': ['non-slip-stair-treads-product'],
    'high-visibility-stair-edge-markings': ['stair-edge-marking-strips'],
    'stair-route-lighting': ['stair-route-lighting-product', 'motion-sensor'],
    'entrance-handrail': ['entrance-handrail-product'],
    'entrance-threshold-ramp': ['threshold-ramp-product'],
    'slip-resistant-entrance-surface': ['entrance-surface-treatment'],
    'high-visibility-step-edge-markings': ['step-edge-marking-strips'],
    'secure-entrance-mat': ['secure-entrance-mat-product'],
    'entrance-lever-door-handle': ['lever-door-handle'],
    'easy-to-use-entrance-lock': ['easy-use-entrance-lock'],
    'smart-video-doorbell': ['smart-video-doorbell-product'],
    'two-way-door-communication': ['doorbell-communications-setup'],
    'live-visitor-view': ['doorbell-communications-setup'],
    'doorbell-motion-detection': ['doorbell-alert-setup'],
    'package-detection': ['doorbell-alert-setup'],
    'mobile-door-notifications': ['doorbell-alert-setup'],
    'entrance-family-notifications': ['carer-alert-setup'],
    'motion-activated-entrance-lighting': ['entrance-motion-light', 'motion-sensor'],
    'porch-lighting': ['porch-light-product'],
    'wider-entrance-doorway': ['wider-entrance-doorway-service'],
    'accessibility-ramp': ['accessibility-ramp-service'],
    'entrance-seating-option': ['entrance-seating-product'],
  }

  return Object.entries(map).flatMap(([capabilityId, productIds]) =>
    productIds.map((productId, index) => relation('capabilityProduct', capabilityId, productId, index + 1)),
  )
}

function capabilityTaskRelations() {
  const map: Record<string, string[]> = {
    'bathroom-wall-mounted-grab-bars': ['inspect-fixing-surface', 'install-support-rail'],
    'bathroom-folding-shower-seat': ['inspect-fixing-surface', 'fit-shower-seat'],
    'bathroom-anti-slip-bath-shower-mat': ['inspect-fixing-surface'],
    'bathroom-toilet-support-rails': ['inspect-fixing-surface', 'install-support-rail'],
    'bathroom-raised-toilet-seat': ['inspect-fixing-surface'],
    'bathroom-anti-slip-floor-treatment': ['apply-anti-slip-treatment'],
    'bathroom-safer-floor-transition': ['reduce-threshold'],
    'wet-floor-grip': ['apply-anti-slip-treatment'],
    'bathroom-motion-night-lighting': ['configure-motion-lighting'],
    'bathroom-lever-mixer-tap': ['fit-water-control'],
    'bathroom-lever-shower-controls': ['fit-water-control'],
    'bathroom-thermostatic-anti-scald-valve': ['fit-water-control'],
    'lever-water-control': ['fit-water-control'],
    'lever-shower-control': ['fit-water-control'],
    'anti-scald-control': ['fit-water-control'],
    'hot-water-temperature-setting': ['set-hot-water-temperature'],
    'threshold-reduction': ['reduce-threshold'],
    'bathroom-lever-door-handle': ['fit-door-hardware'],
    'bathroom-easy-release-privacy-lock': ['fit-door-hardware'],
    'bathroom-door-adjustment': ['adjust-bathroom-door'],
    'water-leak-alerting': ['fit-water-leak-sensor', 'configure-bathroom-alerting'],
    'resident-phone-alerting': ['configure-bathroom-alerting'],
    'nominated-carer-alerting': ['configure-bathroom-alerting'],
    'automatic-water-shutoff': ['fit-water-shutoff-valve', 'configure-bathroom-alerting'],
    'bathroom-bathtub-step-through-conversion': ['measure-specialist-adaptation'],
    'bathroom-wider-doorway-adaptation': ['measure-specialist-adaptation'],
    'bathroom-vertical-support-rail': ['measure-specialist-adaptation', 'install-support-rail'],
    'bathroom-task-lighting': ['inspect-fixing-surface'],
    'motion-activated-lighting': ['configure-motion-lighting'],
    'bedroom-motion-night-lighting': ['configure-motion-lighting'],
    'bed-height-optimisation': ['reposition-furniture'],
    'bed-positioning-adjustment': ['reposition-furniture'],
    'bed-to-door-clear-route': ['reposition-furniture'],
    'bedroom-anti-slip-floor-treatment': ['apply-anti-slip-treatment'],
    'bedroom-secure-floor-coverings': ['reposition-furniture'],
    'smart-speaker-setup': ['pair-smart-speaker'],
    'emergency-call-access': ['test-emergency-contact', 'configure-bedroom-emergency-support'],
    'wearable-emergency-support': ['configure-bedroom-emergency-support', 'test-emergency-contact'],
    'bedside-emergency-assistance': ['configure-bedroom-emergency-support', 'test-emergency-contact'],
    'smoke-alerting': ['test-emergency-contact'],
    'loose-rug-securing': ['reposition-furniture'],
    'cable-management': ['reposition-furniture'],
    'accessible-storage-arrangement': ['reposition-furniture'],
    'movement-reassurance': ['configure-motion-lighting'],
    'hands-free-calling': ['pair-smart-speaker', 'test-emergency-contact'],
    'voice-help-requests': ['pair-smart-speaker'],
    'routine-reminders': ['pair-smart-speaker'],
    'appointment-reminders': ['pair-smart-speaker'],
    'morning-evening-routines': ['pair-smart-speaker'],
    'family-carer-notifications': ['pair-smart-speaker', 'test-emergency-contact'],
    'night-time-safety-alerts': ['configure-motion-lighting', 'test-emergency-contact'],
    'furniture-repositioning': ['reposition-furniture'],
    'specialist-measurement': ['measure-specialist-adaptation'],
    'accessible-wardrobe-adaptation': ['measure-specialist-adaptation'],
    'advanced-bed-transfer-solution': ['measure-specialist-adaptation'],
    'electric-adjustable-bed': ['measure-specialist-adaptation'],
    'bed-exit-safety-system': ['measure-specialist-adaptation', 'configure-bedroom-emergency-support'],
    'automated-curtains-blinds': ['measure-specialist-adaptation', 'pair-smart-speaker'],
    'bedroom-to-bathroom-route-improvement': ['measure-specialist-adaptation'],
    'specialist-bedroom-layout': ['measure-specialist-adaptation'],
    'bedroom-door-accessibility-adaptation': ['measure-specialist-adaptation'],
    'dementia-support-bedroom-adaptation': ['measure-specialist-adaptation'],
    'automatic-jar-opening': ['set-up-kitchen-prep-support'],
    'easy-grip-kitchen-tools': ['set-up-kitchen-prep-support'],
    'non-slip-chopping-support': ['set-up-kitchen-prep-support'],
    'easy-pour-kettle-support': ['set-up-kitchen-prep-support'],
    'anti-fatigue-standing-zone': ['improve-kitchen-standing-route'],
    'safer-hob-control': ['assess-kitchen-cooking-safety', 'configure-kitchen-cooking-safeguard'],
    'automatic-gas-shutoff': ['assess-kitchen-cooking-safety', 'configure-kitchen-cooking-safeguard'],
    'kitchen-task-lighting': ['install-kitchen-task-lighting'],
    'kitchen-circulation-space': ['improve-kitchen-standing-route'],
    'kitchen-storage-organisation': ['organise-kitchen-storage'],
    'waist-height-storage': ['organise-kitchen-storage'],
    'kitchen-motion-alerting': ['configure-kitchen-alerting'],
    'voice-cooking-assistance': ['configure-connected-kitchen'],
    'shopping-list-management': ['configure-connected-kitchen'],
    'pull-out-pantry-storage': ['fit-pull-out-pantry'],
    'wider-kitchen-doorway': ['measure-kitchen-doorway'],
    'seating-height-adjustment': ['adjust-living-room-seating'],
    'sofa-chair-support-handle': ['fit-chair-support-handle'],
    'living-room-furniture-positioning': ['improve-living-room-route'],
    'anti-slip-rug-tape': ['improve-living-room-route'],
    'living-room-circulation-space': ['improve-living-room-route'],
    'living-room-anti-slip-floor-treatment': ['apply-anti-slip-treatment'],
    'living-room-secure-floor-coverings': ['improve-living-room-route'],
    'furniture-anchoring': ['anchor-living-room-furniture'],
    'tv-unit-anchoring': ['anchor-living-room-furniture'],
    'corner-protection': ['anchor-living-room-furniture'],
    'living-room-motion-alerting': ['configure-living-room-alerting'],
    'emergency-voice-assistance': ['pair-smart-speaker', 'test-emergency-contact'],
    'specialist-seating-accessories': ['assess-advanced-seating'],
    'riser-cushion-or-chair-base': ['assess-advanced-seating'],
    'electric-recliner-chair': ['assess-advanced-seating', 'install-electric-recliner'],
    'wider-living-room-doorway': ['measure-living-room-doorway'],
    'stair-handrail': ['measure-stair-route', 'install-stair-handrail'],
    'non-slip-stair-treads': ['measure-stair-route', 'fit-non-slip-stair-treads'],
    'high-visibility-stair-edge-markings': ['measure-stair-route', 'mark-stair-edge-contrast'],
    'stair-route-lighting': ['measure-stair-route', 'install-stair-route-lighting', 'configure-motion-lighting'],
    'entrance-handrail': ['install-entrance-handrail'],
    'entrance-threshold-ramp': ['fit-threshold-ramp'],
    'slip-resistant-entrance-surface': ['improve-entrance-surface'],
    'high-visibility-step-edge-markings': ['mark-entrance-step-edges'],
    'secure-entrance-mat': ['fit-secure-entrance-mat'],
    'entrance-lever-door-handle': ['fit-entrance-door-hardware'],
    'easy-to-use-entrance-lock': ['fit-entrance-door-hardware'],
    'smart-video-doorbell': ['configure-video-doorbell'],
    'two-way-door-communication': ['configure-video-doorbell'],
    'live-visitor-view': ['configure-video-doorbell'],
    'doorbell-motion-detection': ['configure-video-doorbell'],
    'package-detection': ['configure-video-doorbell'],
    'mobile-door-notifications': ['configure-video-doorbell'],
    'entrance-family-notifications': ['configure-video-doorbell', 'test-emergency-contact'],
    'motion-activated-entrance-lighting': ['install-entrance-lighting', 'configure-motion-lighting'],
    'porch-lighting': ['install-entrance-lighting'],
    'wider-entrance-doorway': ['measure-entrance-doorway'],
    'accessibility-ramp': ['assess-accessibility-ramp'],
    'entrance-seating-option': ['fit-entrance-seating'],
  }

  return Object.entries(map).flatMap(([capabilityId, taskIds]) =>
    taskIds.map((taskId, index) => relation('capabilityInstallationTask', capabilityId, taskId, index + 1)),
  )
}
