import type { CasaMiaService } from '../types/serviceCatalogue.ts'

export const casaMiaServices: CasaMiaService[] = [
  {
    id: 'entrance-motion-lighting',
    slug: 'motion-entrance-lighting',
    name: 'Motion entrance lighting',
    shortDescription: 'Automatic light at the door, path or threshold.',
    customerBenefit: 'Makes arrivals safer when hands are full or visibility is poor.',
    room: 'entrance',
    category: 'Access and visibility',
    pricingType: 'fixed',
    productPrice: 180,
    installationPrice: 90,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Motion light fitting', 'Positioning check', 'Installer handover'],
    active: true,
  },
  {
    id: 'entrance-step-handrail',
    slug: 'entrance-step-handrail',
    name: 'Entrance handrail',
    shortDescription: 'Stable support beside steps or a raised entrance.',
    customerBenefit: 'Adds confidence when stepping in, out or turning at the door.',
    room: 'entrance',
    category: 'Access support',
    pricingType: 'from',
    fromPrice: 260,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: true,
    requiresCompatibilityCheck: true,
    includedItems: ['Support position review', 'Rail selection', 'Professional fixing'],
    active: true,
  },
  {
    id: 'entrance-threshold-treatment',
    slug: 'threshold-treatment',
    name: 'Threshold treatment',
    shortDescription: 'Reduce slip or trip risk at a door threshold.',
    customerBenefit: 'Makes the first step into the home smoother and more predictable.',
    room: 'entrance',
    category: 'Trip reduction',
    pricingType: 'fixed',
    productPrice: 150,
    installationPrice: 80,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Threshold review', 'Non-slip strip or low-profile support', 'Fitting and test'],
    active: true,
  },
  {
    id: 'entrance-secure-access',
    slug: 'secure-access-support',
    name: 'Secure access support',
    shortDescription: 'Smart lock, keypad or doorbell support where suitable.',
    customerBenefit: 'Helps family or carers access the home without unsafe rushing or hidden keys.',
    room: 'entrance',
    category: 'Access and visibility',
    pricingType: 'from',
    fromPrice: 390,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Device compatibility check', 'Access device setup', 'Family handover'],
    safetyNotice: 'Access permissions must be agreed with the resident or authorised family member.',
    active: true,
  },
  {
    id: 'entrance-modular-ramp',
    slug: 'modular-access-ramp',
    name: 'Modular access ramp',
    shortDescription: 'Measured ramp solution for larger level changes.',
    customerBenefit: 'Creates safer access where a small threshold support is not enough.',
    room: 'entrance',
    category: 'Access support',
    pricingType: 'quote_only',
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: true,
    requiresCompatibilityCheck: true,
    includedItems: ['Gradient measurement', 'Ramp specification', 'Installation coordination'],
    safetyNotice: 'Ramp length and gradient must be measured before final pricing.',
    active: true,
  },
  {
    id: 'movement-hallway-lighting',
    slug: 'hallway-motion-lighting',
    name: 'Hallway motion lighting',
    shortDescription: 'Automatic lighting along night routes and corridors.',
    customerBenefit: 'Reduces searching for switches and improves visibility during movement.',
    room: 'movement',
    category: 'Movement routes',
    pricingType: 'fixed',
    productPrice: 220,
    installationPrice: 120,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Route review', 'Motion lights', 'Switch or timer setup'],
    active: true,
  },
  {
    id: 'movement-rug-securing',
    slug: 'rug-securing',
    name: 'Rug securing or removal',
    shortDescription: 'Secure loose rugs or remove risky edges.',
    customerBenefit: 'Cuts down common trip points without changing the whole room.',
    room: 'movement',
    category: 'Trip reduction',
    pricingType: 'from',
    fromPrice: 95,
    vatRate: 0.21,
    quantityType: 'per_room',
    requiresInstallation: false,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Trip-edge check', 'Anti-slip underlay or fixing', 'Room route review'],
    active: true,
  },
  {
    id: 'movement-cable-management',
    slug: 'cable-management',
    name: 'Cable management',
    shortDescription: 'Move or secure visible cables across walking routes.',
    customerBenefit: 'Keeps daily paths clearer for feet, walkers and cleaning.',
    room: 'movement',
    category: 'Trip reduction',
    pricingType: 'from',
    fromPrice: 75,
    vatRate: 0.21,
    quantityType: 'per_room',
    requiresInstallation: false,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Cable route check', 'Clips or covers', 'Safer placement guidance'],
    active: true,
  },
  {
    id: 'movement-stair-handrails',
    slug: 'stair-handrails',
    name: 'Stair handrails',
    shortDescription: 'Stable support on one or both sides of a staircase.',
    customerBenefit: 'Improves confidence and control when moving between levels.',
    room: 'movement',
    category: 'Stair safety',
    pricingType: 'from',
    fromPrice: 520,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: true,
    requiresCompatibilityCheck: true,
    includedItems: ['Stair measurement', 'Rail selection', 'Professional fitting'],
    active: true,
  },
  {
    id: 'movement-stair-treads',
    slug: 'non-slip-stair-treads',
    name: 'Non-slip stair treads',
    shortDescription: 'Grip and contrast for stair edges.',
    customerBenefit: 'Makes step edges easier to see and less slippery.',
    room: 'movement',
    category: 'Stair safety',
    pricingType: 'from',
    fromPrice: 280,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Tread count', 'Contrast and grip treatment', 'Installation'],
    active: true,
  },
  {
    id: 'movement-stand-assist',
    slug: 'stand-assist-handle',
    name: 'Stand-assist handle',
    shortDescription: 'Support for getting up from a sofa or chair.',
    customerBenefit: 'Reduces effort and unsafe pulling on furniture.',
    room: 'movement',
    category: 'Daily support',
    pricingType: 'fixed',
    productPrice: 150,
    installationPrice: 45,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Chair compatibility check', 'Support handle', 'User positioning guidance'],
    active: true,
  },
  {
    id: 'bedroom-bed-support',
    slug: 'bed-support-handle',
    name: 'Bed support handle',
    shortDescription: 'Support for getting in and out of bed.',
    customerBenefit: 'Makes bed transfers steadier without making the room feel clinical.',
    room: 'bedroom',
    category: 'Bed transfer support',
    pricingType: 'fixed',
    productPrice: 180,
    installationPrice: 60,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Bed compatibility check', 'Support handle', 'Safe-use handover'],
    active: true,
  },
  {
    id: 'bedroom-underbed-lighting',
    slug: 'under-bed-motion-lighting',
    name: 'Under-bed motion lighting',
    shortDescription: 'Soft light triggered when someone gets up at night.',
    customerBenefit: 'Helps the resident see the route without harsh overhead light.',
    room: 'bedroom',
    category: 'Night route',
    pricingType: 'fixed',
    productPrice: 140,
    installationPrice: 80,
    vatRate: 0.21,
    quantityType: 'per_room',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Bedside route review', 'Motion lighting', 'Sensitivity setup'],
    active: true,
  },
  {
    id: 'bedroom-night-route',
    slug: 'night-route-lighting',
    name: 'Night-route lighting',
    shortDescription: 'Plug-in lights or motion lights to the door or bathroom.',
    customerBenefit: 'Reduces night-time hesitation, shadows and missed obstacles.',
    room: 'bedroom',
    category: 'Night route',
    pricingType: 'from',
    fromPrice: 95,
    vatRate: 0.21,
    quantityType: 'per_room',
    requiresInstallation: false,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Route placement', 'Night lights', 'Switch-free setup'],
    active: true,
  },
  {
    id: 'bedroom-bed-exit-sensor',
    slug: 'bed-exit-sensor',
    name: 'Bed-exit sensor',
    shortDescription: 'Optional family alert when night movement starts.',
    customerBenefit: 'Useful when relatives worry about falls during the night.',
    room: 'bedroom',
    category: 'Family reassurance',
    pricingType: 'from',
    fromPrice: 260,
    recurringMonthlyPrice: 9,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Sensor placement', 'Alert setup', 'Family handover'],
    safetyNotice: 'Requires consent and clear agreement on who receives alerts.',
    active: true,
  },
  {
    id: 'bedroom-adjustable-bed',
    slug: 'adjustable-bed',
    name: 'Adjustable bed review',
    shortDescription: 'Check whether an adjustable bed would meaningfully help.',
    customerBenefit: 'Avoids buying a major item unless it genuinely improves transfers or comfort.',
    room: 'bedroom',
    category: 'Bed transfer support',
    pricingType: 'quote_only',
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: true,
    requiresCompatibilityCheck: true,
    includedItems: ['Needs review', 'Sizing and access check', 'Supplier coordination if chosen'],
    active: true,
  },
  {
    id: 'bathroom-grab-bars',
    slug: 'wall-grab-bars',
    name: 'Wall grab bars',
    shortDescription: 'Support bars fixed where transfers actually happen.',
    customerBenefit: 'Adds reliable hand support for shower, toilet or sink movement.',
    room: 'bathroom',
    category: 'Transfer support',
    pricingType: 'from',
    fromPrice: 220,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: true,
    requiresCompatibilityCheck: true,
    includedItems: ['Wall structure check', 'Bar positioning', 'Professional fixing'],
    safetyNotice: 'Wall strength must be checked before grab bars are fixed.',
    active: true,
  },
  {
    id: 'bathroom-shower-chair',
    slug: 'height-adjustable-shower-chair',
    name: 'Shower chair',
    shortDescription: 'Stable seating for showering.',
    customerBenefit: 'Reduces fatigue and standing risk in the wet area.',
    room: 'bathroom',
    category: 'Shower safety',
    pricingType: 'fixed',
    productPrice: 160,
    installationPrice: 0,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: false,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Chair selection', 'Height adjustment', 'Placement guidance'],
    active: true,
  },
  {
    id: 'bathroom-raised-toilet',
    slug: 'raised-toilet-seat',
    name: 'Raised toilet support',
    shortDescription: 'Raised seat or support frame for toilet transfers.',
    customerBenefit: 'Makes sitting and standing easier with less strain.',
    room: 'bathroom',
    category: 'Transfer support',
    pricingType: 'from',
    fromPrice: 170,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: false,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Toilet fit check', 'Raised support option', 'Safe-use handover'],
    active: true,
  },
  {
    id: 'bathroom-anti-slip',
    slug: 'anti-slip-shower-treatment',
    name: 'Anti-slip shower treatment',
    shortDescription: 'Reduce slip risk in shower, bath or wet floor areas.',
    customerBenefit: 'Helps make the wettest part of the home feel less risky.',
    room: 'bathroom',
    category: 'Wet-floor safety',
    pricingType: 'from',
    fromPrice: 240,
    vatRate: 0.21,
    quantityType: 'per_square_metre',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Surface review', 'Anti-slip treatment', 'Aftercare guidance'],
    active: true,
  },
  {
    id: 'bathroom-nightlight',
    slug: 'bathroom-nightlight',
    name: 'Bathroom nightlight',
    shortDescription: 'Automatic low light for night bathroom trips.',
    customerBenefit: 'Makes night toilet visits calmer and easier to navigate.',
    room: 'bathroom',
    category: 'Night route',
    pricingType: 'fixed',
    productPrice: 75,
    installationPrice: 25,
    vatRate: 0.21,
    quantityType: 'per_room',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Nightlight', 'Positioning', 'Testing'],
    active: true,
  },
  {
    id: 'connected-emergency-button',
    slug: 'emergency-call-button',
    name: 'Emergency call button',
    shortDescription: 'A simple wearable or fixed button to call for help.',
    customerBenefit: 'Gives the resident and family a clearer way to respond quickly.',
    room: 'connected',
    category: 'Emergency support',
    pricingType: 'fixed',
    productPrice: 190,
    installationPrice: 80,
    recurringMonthlyPrice: 9,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Button setup', 'Contact routing', 'Test call handover'],
    safetyNotice: 'Requires agreed emergency contacts and resident consent.',
    active: true,
  },
  {
    id: 'connected-voice-hub',
    slug: 'voice-hub-setup',
    name: 'Voice hub setup',
    shortDescription: 'Simple voice control for lights, reminders or compatible devices.',
    customerBenefit: 'Reduces rushing, bending and searching for switches.',
    room: 'connected',
    category: 'Simple controls',
    pricingType: 'from',
    fromPrice: 180,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Voice hub', 'Basic routines', 'Resident handover'],
    active: true,
  },
  {
    id: 'connected-family-alerts',
    slug: 'family-alert-setup',
    name: 'Family alert setup',
    shortDescription: 'Agree who receives alerts and what each alert means.',
    customerBenefit: 'Keeps family informed without creating unnecessary noise.',
    room: 'connected',
    category: 'Family reassurance',
    pricingType: 'fixed',
    productPrice: 120,
    installationPrice: 90,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Alert preferences', 'Family contact setup', 'Privacy handover'],
    active: true,
  },
  {
    id: 'connected-fall-detection',
    slug: 'fall-detection-review',
    name: 'Fall detection review',
    shortDescription: 'Check whether wearable or room-based detection is appropriate.',
    customerBenefit: 'Adds reassurance only where the resident will actually use it.',
    room: 'connected',
    category: 'Emergency support',
    pricingType: 'from',
    fromPrice: 280,
    recurringMonthlyPrice: 12,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Use-case review', 'Device setup', 'Family test'],
    safetyNotice: 'No device replaces emergency services or direct care.',
    active: true,
  },
  {
    id: 'connected-monitoring',
    slug: 'professional-monitoring',
    name: 'Professional monitoring option',
    shortDescription: 'Optional response-centre monitoring if family-only alerts are not enough.',
    customerBenefit: 'Creates a clearer escalation path when relatives cannot always respond.',
    room: 'connected',
    category: 'Emergency support',
    pricingType: 'from',
    fromPrice: 0,
    recurringMonthlyPrice: 29,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: false,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Monitoring eligibility check', 'Escalation preferences', 'Monthly support setup'],
    active: true,
  },
  {
    id: 'kitchen-prep-mats',
    slug: 'non-slip-preparation-mats',
    name: 'Non-slip preparation mats',
    shortDescription: 'A steadier surface where food preparation usually happens.',
    customerBenefit: 'Reduces slipping and makes standing prep feel more secure.',
    room: 'kitchen',
    category: 'Standing and floor safety',
    pricingType: 'fixed',
    productPrice: 85,
    installationPrice: 35,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Low-profile non-slip mat', 'Placement check', 'Cleaning and care guidance'],
    recommendedWhen: [
      {
        answerKey: 'kitchen.floorRisk',
        matches: ['slippery', 'unsure'],
        reason: 'Useful where the resident prepares food on hard or slippery flooring.',
      },
    ],
    active: true,
  },
  {
    id: 'kitchen-easy-grip-tools',
    slug: 'easy-grip-kitchen-tools',
    name: 'Easy-grip tools',
    shortDescription: 'Utensils and openers that reduce twisting, force and hand strain.',
    customerBenefit: 'Makes everyday cooking tasks easier without changing the whole kitchen.',
    room: 'kitchen',
    category: 'Daily preparation',
    pricingType: 'fixed',
    productPrice: 120,
    installationPrice: 0,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: false,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Easy-grip utensils', 'Jar and bottle openers', 'Automatic can opener option'],
    recommendedWhen: [
      {
        answerKey: 'resident.gripStrength',
        matches: ['reduced', 'painful', 'unsure'],
        reason: 'Recommended when hand strength or wrist movement makes meal preparation tiring.',
      },
    ],
    active: true,
  },
  {
    id: 'kitchen-lightweight-cookware',
    slug: 'lightweight-cookware',
    name: 'Lightweight cookware',
    shortDescription: 'Lighter pans and safer handling for everyday meals.',
    customerBenefit: 'Reduces heavy lifting, awkward carrying and spill risk.',
    room: 'kitchen',
    category: 'Daily preparation',
    pricingType: 'from',
    fromPrice: 95,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: false,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Lightweight pan guidance', 'Handle and grip check', 'Storage placement recommendation'],
    active: true,
  },
  {
    id: 'kitchen-anti-fatigue-mat',
    slug: 'anti-fatigue-non-slip-mat',
    name: 'Anti-fatigue non-slip mat',
    shortDescription: 'A stable standing zone for sink, prep or cooking areas.',
    customerBenefit: 'Helps reduce tired legs and wet-floor slips during longer kitchen tasks.',
    room: 'kitchen',
    category: 'Standing and floor safety',
    pricingType: 'fixed',
    productPrice: 130,
    installationPrice: 35,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Anti-fatigue mat', 'Trip-edge check', 'Positioning around the daily route'],
    active: true,
  },
  {
    id: 'kitchen-worktop-lighting',
    slug: 'worktop-task-lighting',
    name: 'Worktop task lighting',
    shortDescription: 'Clearer light over prep, sink or cooking zones.',
    customerBenefit: 'Makes spills, edges and food preparation easier to see.',
    room: 'kitchen',
    category: 'Lighting and visibility',
    pricingType: 'fixed',
    productPrice: 165,
    installationPrice: 120,
    vatRate: 0.21,
    quantityType: 'per_room',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Task-light placement', 'Selected light fittings', 'Switch or control setup'],
    active: true,
  },
  {
    id: 'kitchen-voice-lighting-timers',
    slug: 'voice-lighting-and-timers',
    name: 'Voice lighting and timers',
    shortDescription: 'Simple voice support for light control and cooking reminders.',
    customerBenefit: 'Reduces rushing, bending and forgotten cooking routines.',
    room: 'kitchen',
    category: 'Smart reassurance',
    pricingType: 'from',
    fromPrice: 140,
    vatRate: 0.21,
    quantityType: 'per_room',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    dependencies: ['connected-voice-hub'],
    includedItems: ['Voice control setup', 'Timer routine setup', 'Resident and family handover'],
    active: true,
  },
  {
    id: 'kitchen-smart-plugs',
    slug: 'selected-smart-plugs',
    name: 'Selected smart plugs',
    shortDescription: 'Simple control for compatible small appliances.',
    customerBenefit: 'Gives the family reassurance that selected devices can be checked or controlled.',
    room: 'kitchen',
    category: 'Smart reassurance',
    pricingType: 'fixed',
    productPrice: 90,
    installationPrice: 60,
    vatRate: 0.21,
    quantityType: 'per_home',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Compatible plug selection', 'App or voice setup', 'Safe-use guidance'],
    safetyNotice: 'Only suitable for compatible low-risk appliances after review.',
    active: true,
  },
  {
    id: 'kitchen-water-leak-sensor',
    slug: 'water-leak-sensor',
    name: 'Water-leak sensor',
    shortDescription: 'Early warning if water appears where it should not.',
    customerBenefit: 'Helps prevent wet-floor risk and hidden damage under sinks or appliances.',
    room: 'kitchen',
    category: 'Water and appliance safety',
    pricingType: 'fixed',
    productPrice: 75,
    installationPrice: 45,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: false,
    includedItems: ['Leak sensor', 'Alert setup', 'Battery and testing guidance'],
    active: true,
  },
  {
    id: 'kitchen-gas-co-sensor',
    slug: 'gas-or-carbon-monoxide-sensor',
    name: 'Gas or CO sensor',
    shortDescription: 'Extra alerting where gas or carbon-monoxide risk exists.',
    customerBenefit: 'Protects against invisible hazards from gas appliances or poor ventilation.',
    room: 'kitchen',
    category: 'Water and appliance safety',
    pricingType: 'fixed',
    productPrice: 95,
    installationPrice: 45,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: false,
    requiresCompatibilityCheck: true,
    includedItems: ['Gas or CO detector', 'Placement guidance', 'Alert and test handover'],
    safetyNotice: 'Placement depends on appliance type and manufacturer guidance.',
    active: true,
  },
  {
    id: 'kitchen-pull-down-shelf',
    slug: 'pull-down-upper-cabinet-shelf',
    name: 'Pull-down upper-cabinet shelf',
    shortDescription: 'Brings high cupboard items down to a safer height.',
    customerBenefit: 'Reduces climbing, stretching and unsafe stool use.',
    room: 'kitchen',
    category: 'Reach and storage',
    pricingType: 'fixed',
    productPrice: 420,
    installationPrice: 160,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: true,
    requiresCompatibilityCheck: true,
    includedItems: ['Cabinet compatibility check', 'Pull-down shelf hardware', 'Professional fitting'],
    active: true,
  },
  {
    id: 'kitchen-stove-shutoff',
    slug: 'automatic-stove-shut-off',
    name: 'Automatic stove shut-off',
    shortDescription: 'A safety layer for higher-risk cooking routines.',
    customerBenefit: 'Reduces family worry about forgotten hobs or burnt pans.',
    room: 'kitchen',
    category: 'Water and appliance safety',
    pricingType: 'fixed',
    productPrice: 360,
    installationPrice: 180,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: false,
    requiresSiteVisit: true,
    requiresCompatibilityCheck: true,
    includedItems: ['Appliance compatibility review', 'Shut-off device', 'Testing and handover'],
    safetyNotice: 'Only recommended after appliance and routine checks.',
    active: true,
  },
  {
    id: 'kitchen-touchless-faucet',
    slug: 'touchless-faucet',
    name: 'Touchless faucet',
    shortDescription: 'Easier sink use with wet, weak or painful hands.',
    customerBenefit: 'Reduces twisting, reaching and water left running.',
    room: 'kitchen',
    category: 'Water and appliance safety',
    pricingType: 'fixed',
    productPrice: 260,
    installationPrice: 160,
    vatRate: 0.21,
    quantityType: 'per_unit',
    requiresInstallation: true,
    requiresMeasurement: true,
    requiresSiteVisit: true,
    requiresCompatibilityCheck: true,
    includedItems: ['Tap compatibility check', 'Touchless faucet', 'Plumbing coordination'],
    active: true,
  },
]
