import type { CasaMiaServiceTranslation } from '../types/serviceCatalogue'

export const defaultSpanishServiceCopy: Record<string, CasaMiaServiceTranslation> = {
  'entrance-motion-lighting': {
    name: 'Iluminación automática de entrada',
    shortDescription: 'Luz automática en la puerta, camino o umbral.',
    customerBenefit: 'Hace las llegadas más seguras cuando hay poca visibilidad o las manos están ocupadas.',
    category: 'Acceso y visibilidad',
    includedItems: ['Luminaria con sensor', 'Revisión de ubicación', 'Entrega por el instalador'],
  },
  'entrance-step-handrail': {
    name: 'Pasamanos de entrada',
    shortDescription: 'Apoyo estable junto a escalones o una entrada elevada.',
    customerBenefit: 'Aporta confianza al entrar, salir o girar junto a la puerta.',
    category: 'Apoyo de acceso',
    includedItems: ['Revisión de posición', 'Selección del pasamanos', 'Fijación profesional'],
  },
  'entrance-threshold-treatment': {
    name: 'Tratamiento de umbral',
    shortDescription: 'Reduce el riesgo de resbalón o tropiezo en el umbral de una puerta.',
    customerBenefit: 'Hace que el primer paso hacia la vivienda sea más suave y predecible.',
    category: 'Reducción de tropiezos',
    includedItems: ['Revisión del umbral', 'Tira antideslizante o apoyo de bajo perfil', 'Colocación y prueba'],
  },
  'entrance-secure-access': {
    name: 'Apoyo de acceso seguro',
    shortDescription: 'Cerradura inteligente, teclado o timbre cuando encaja.',
    customerBenefit: 'Ayuda a familiares o cuidadores a acceder sin prisas inseguras ni llaves escondidas.',
    category: 'Acceso y visibilidad',
    includedItems: ['Comprobación de compatibilidad', 'Configuración del dispositivo', 'Entrega a la familia'],
    safetyNotice: 'Los permisos de acceso deben acordarse con la persona residente o familiar autorizado.',
  },
  'entrance-modular-ramp': {
    name: 'Rampa modular de acceso',
    shortDescription: 'Solución de rampa medida para desniveles mayores.',
    customerBenefit: 'Crea un acceso más seguro cuando un pequeño apoyo de umbral no es suficiente.',
    category: 'Apoyo de acceso',
    includedItems: ['Medición de pendiente', 'Especificación de rampa', 'Coordinación de instalación'],
    safetyNotice: 'La longitud y pendiente de la rampa deben medirse antes del precio final.',
  },
  'movement-hallway-lighting': {
    name: 'Iluminación automática de pasillo',
    shortDescription: 'Luz automática en rutas nocturnas y pasillos.',
    customerBenefit: 'Reduce la búsqueda de interruptores y mejora la visibilidad al moverse.',
    category: 'Rutas de movimiento',
    includedItems: ['Revisión de ruta', 'Luces con sensor', 'Configuración de interruptor o temporizador'],
  },
  'movement-rug-securing': {
    name: 'Fijación o retirada de alfombras',
    shortDescription: 'Fijar alfombras sueltas o retirar bordes de riesgo.',
    customerBenefit: 'Reduce tropiezos habituales sin cambiar toda la estancia.',
    category: 'Reducción de tropiezos',
    includedItems: ['Revisión de bordes', 'Base antideslizante o fijación', 'Revisión de ruta'],
  },
  'movement-cable-management': {
    name: 'Gestión de cables',
    shortDescription: 'Mover o fijar cables visibles en zonas de paso.',
    customerBenefit: 'Mantiene las rutas diarias más despejadas para pies, andadores y limpieza.',
    category: 'Reducción de tropiezos',
    includedItems: ['Revisión de cables', 'Clips o cubiertas', 'Consejos de colocación segura'],
  },
  'movement-stair-handrails': {
    name: 'Pasamanos de escalera',
    shortDescription: 'Apoyo estable en uno o ambos lados de la escalera.',
    customerBenefit: 'Mejora la confianza y el control al moverse entre niveles.',
    category: 'Seguridad en escaleras',
    includedItems: ['Medición de escalera', 'Selección de pasamanos', 'Instalación profesional'],
  },
  'movement-stair-treads': {
    name: 'Peldaños antideslizantes',
    shortDescription: 'Agarre y contraste para bordes de escalón.',
    customerBenefit: 'Hace los bordes más visibles y menos resbaladizos.',
    category: 'Seguridad en escaleras',
    includedItems: ['Conteo de peldaños', 'Tratamiento de contraste y agarre', 'Instalación'],
  },
  'movement-stand-assist': {
    name: 'Asa de ayuda para levantarse',
    shortDescription: 'Apoyo para levantarse del sofá o silla.',
    customerBenefit: 'Reduce esfuerzo y evita tirar de muebles inseguros.',
    category: 'Apoyo diario',
    includedItems: ['Comprobación de silla', 'Asa de apoyo', 'Orientación de uso seguro'],
  },
  'bedroom-bed-support': {
    name: 'Asa de apoyo para cama',
    shortDescription: 'Apoyo para entrar y salir de la cama.',
    customerBenefit: 'Hace las transferencias más estables sin dar un aspecto clínico al dormitorio.',
    category: 'Transferencia de cama',
    includedItems: ['Comprobación de cama', 'Asa de apoyo', 'Entrega de uso seguro'],
  },
  'bedroom-underbed-lighting': {
    name: 'Iluminación bajo cama con sensor',
    shortDescription: 'Luz suave automática al levantarse.',
    customerBenefit: 'Mejora la orientación sin encender luces intensas por la noche.',
    category: 'Ruta nocturna',
    includedItems: ['Revisión de ubicación', 'Tira o luz con sensor', 'Prueba nocturna'],
  },
  'bedroom-night-route': {
    name: 'Iluminación de ruta nocturna',
    shortDescription: 'Luz guiada de la cama al baño o pasillo.',
    customerBenefit: 'Reduce tropiezos cuando la persona se mueve con sueño o prisa.',
    category: 'Ruta nocturna',
    includedItems: ['Revisión de ruta', 'Luces con sensor', 'Configuración y prueba'],
  },
  'bedroom-bed-exit-sensor': {
    name: 'Sensor de salida de cama',
    shortDescription: 'Aviso discreto cuando levantarse necesita atención.',
    customerBenefit: 'Ayuda a cuidadores o familiares a responder en rutinas nocturnas acordadas.',
    category: 'Tranquilidad familiar',
    includedItems: ['Comprobación de uso', 'Sensor compatible', 'Configuración de aviso'],
  },
  'bedroom-adjustable-bed': {
    name: 'Revisión de cama articulada',
    shortDescription: 'Valorar si una cama ajustable ayudaría en transferencias y descanso.',
    customerBenefit: 'Evita compras grandes sin confirmar necesidad, espacio y compatibilidad.',
    category: 'Transferencia de cama',
    includedItems: ['Revisión de medidas', 'Necesidades de transferencia', 'Recomendación de siguiente paso'],
  },
  'bathroom-grab-bars': {
    name: 'Barras de apoyo en pared',
    shortDescription: 'Apoyo fijo para ducha, inodoro o lavabo.',
    customerBenefit: 'Sustituye apoyos improvisados por puntos seguros donde realmente hacen falta.',
    category: 'Apoyo de transferencia',
    includedItems: ['Ubicación de barras', 'Selección de fijación', 'Instalación profesional'],
  },
  'bathroom-shower-chair': {
    name: 'Silla de ducha',
    shortDescription: 'Asiento seguro para ducharse con menos esfuerzo.',
    customerBenefit: 'Reduce cansancio y riesgo durante la ducha.',
    category: 'Seguridad en ducha',
    includedItems: ['Comprobación de espacio', 'Selección de silla', 'Orientación de uso'],
  },
  'bathroom-raised-toilet': {
    name: 'Apoyo para inodoro elevado',
    shortDescription: 'Mejora la altura o el apoyo para sentarse y levantarse.',
    customerBenefit: 'Facilita transferencias y reduce el esfuerzo en una rutina diaria clave.',
    category: 'Apoyo de transferencia',
    includedItems: ['Revisión de altura', 'Soporte o elevador', 'Ajuste y prueba'],
  },
  'bathroom-anti-slip': {
    name: 'Tratamiento antideslizante de ducha',
    shortDescription: 'Mejora agarre en una zona mojada de alto riesgo.',
    customerBenefit: 'Reduce el riesgo de resbalones sin rehacer todo el baño.',
    category: 'Seguridad en suelo mojado',
    includedItems: ['Revisión de superficie', 'Tratamiento antideslizante', 'Prueba de agarre'],
  },
  'bathroom-nightlight': {
    name: 'Luz nocturna de baño',
    shortDescription: 'Iluminación suave para entrar y usar el baño de noche.',
    customerBenefit: 'Mejora orientación sin deslumbrar ni despertar demasiado.',
    category: 'Ruta nocturna',
    includedItems: ['Revisión de enchufe o ubicación', 'Luz nocturna', 'Prueba de ruta'],
  },
  'legacy-bathroom-grab-bars': {
    name: 'Barras de apoyo',
    shortDescription: 'Barras fijas de pared para la zona de ducha, bañera o inodoro.',
    customerBenefit: 'Aportan apoyo estable y ayudan a reducir el riesgo de caída.',
    category: 'Seguridad en el baño',
    includedItems: ['Barra de apoyo', 'Fijaciones de montaje'],
    safetyNotice: 'Debe revisarse la ubicación y la estructura de la pared antes de instalar.',
  },
  'bathroom-folding-shower-seat': {
    name: 'Asiento abatible de ducha',
    shortDescription: 'Asiento abatible de pared para ducharse sentado.',
    customerBenefit: 'Permite una ducha más segura sentado y ahorra espacio cuando no se usa.',
    category: 'Seguridad en el baño',
    includedItems: ['Asiento abatible de ducha', 'Fijaciones de montaje'],
    safetyNotice: 'Debe confirmarse la idoneidad de la pared y las necesidades de la persona.',
  },
  'bathroom-anti-slip-floor-treatment': {
    name: 'Tratamiento antideslizante de suelo',
    shortDescription: 'Tratamiento antideslizante aplicado sobre pavimento de baño compatible.',
    customerBenefit: 'Mejora el agarre en superficies mojadas.',
    category: 'Seguridad en el baño',
    includedItems: ['Tratamiento de superficie antideslizante'],
    safetyNotice: 'Debe evaluarse el material y el estado del suelo antes de aplicarlo.',
  },
  'bathroom-anti-slip-bath-mat': {
    name: 'Alfombrilla antideslizante segura',
    shortDescription: 'Alfombrilla de alto agarre para bañera o ducha.',
    customerBenefit: 'Añade tracción en zonas mojadas.',
    category: 'Seguridad en el baño',
    includedItems: ['Alfombrilla antideslizante'],
    safetyNotice: 'Debe colocarse correctamente y revisarse con regularidad.',
  },
  'bathroom-raised-toilet-seat': {
    name: 'Elevador de inodoro',
    shortDescription: 'Asiento elevado compatible con el inodoro existente.',
    customerBenefit: 'Reduce el esfuerzo al sentarse y levantarse.',
    category: 'Seguridad en el baño',
    includedItems: ['Elevador de inodoro', 'Fijaciones necesarias'],
    safetyNotice: 'Debe confirmarse la compatibilidad del inodoro y la altura adecuada.',
  },
  'bathroom-toilet-support-rails': {
    name: 'Barras de apoyo para inodoro',
    shortDescription: 'Barras instaladas junto al inodoro.',
    customerBenefit: 'Aportan estabilidad durante las transferencias al inodoro.',
    category: 'Seguridad en el baño',
    includedItems: ['Barras de apoyo', 'Fijaciones de montaje'],
    safetyNotice: 'La fijación depende de la pared, el suelo y la configuración del inodoro.',
  },
  'bathroom-comfort-height-toilet': {
    name: 'Sustitución por inodoro de altura cómoda',
    shortDescription: 'Inodoro más alto diseñado para facilitar el acceso.',
    customerBenefit: 'Hace más cómodo y manejable sentarse y levantarse.',
    category: 'Adaptación del baño',
    includedItems: ['Inodoro de altura cómoda', 'Fijaciones estándar'],
    safetyNotice: 'Debe revisarse la posición de fontanería, medidas y necesidades de uso.',
  },
  'bathroom-improved-lighting': {
    name: 'Mejora de iluminación del baño',
    shortDescription: 'Mejora de la iluminación general y de uso diario en el baño.',
    customerBenefit: 'Aumenta la visibilidad y la confianza en el uso cotidiano.',
    category: 'Iluminación',
    includedItems: ['Luminarias', 'Fijaciones eléctricas estándar'],
    safetyNotice: 'La instalación eléctrica debe cumplir las zonas de seguridad del baño.',
  },
  'bathroom-motion-lighting': {
    name: 'Iluminación con sensor de movimiento',
    shortDescription: 'Luz que se activa automáticamente al detectar movimiento.',
    customerBenefit: 'Ayuda a acceder al baño con más seguridad, especialmente de noche.',
    category: 'Iluminación',
    includedItems: ['Sensor de movimiento', 'Controles de iluminación'],
    safetyNotice: 'Debe revisarse la ubicación del sensor y las zonas eléctricas.',
  },
  'bathroom-lever-mixer-tap': {
    name: 'Grifo monomando de palanca',
    shortDescription: 'Grifo fácil de manejar para lavabo, bañera o ducha.',
    customerBenefit: 'Requiere menos fuerza de agarre que los mandos tradicionales.',
    category: 'Accesibilidad',
    includedItems: ['Grifo monomando de palanca', 'Fijaciones estándar'],
    safetyNotice: 'Debe confirmarse la compatibilidad con la fontanería existente.',
  },
  'bathroom-thermostatic-valve': {
    name: 'Válvula termostática antiescaldaduras',
    shortDescription: 'Válvula con control de temperatura para regular el agua caliente.',
    customerBenefit: 'Ayuda a reducir el riesgo de quemaduras accidentales.',
    category: 'Seguridad de fontanería',
    includedItems: ['Válvula termostática', 'Fijaciones estándar'],
    safetyNotice: 'Requiere instalación profesional de fontanería.',
  },
  'bathroom-threshold-removal': {
    name: 'Reducción o retirada de umbral',
    shortDescription: 'Reducción o retirada de un umbral elevado en la puerta del baño.',
    customerBenefit: 'Reduce un riesgo habitual de tropiezo y mejora el acceso.',
    category: 'Accesibilidad',
    includedItems: ['Modificación del umbral', 'Materiales de acabado'],
    safetyNotice: 'Depende de niveles de suelo, impermeabilización y construcción de la puerta.',
  },
  'bathroom-tub-cutout': {
    name: 'Conversión de bañera con acceso bajo',
    shortDescription: 'Modificación de una bañera existente compatible para crear una entrada más baja.',
    customerBenefit: 'Facilita el acceso manteniendo la bañera existente.',
    category: 'Adaptación del baño',
    includedItems: ['Sistema de corte de bañera', 'Inserto impermeable', 'Instalación'],
    safetyNotice: 'Sujeto a evaluación y compatibilidad del fabricante.',
  },
  'bathroom-wider-doorway': {
    name: 'Ensanche de puerta de baño',
    shortDescription: 'Ampliación de la puerta del baño para mejorar el acceso.',
    customerBenefit: 'Aporta más espacio para ayudas de movilidad o asistencia.',
    category: 'Accesibilidad',
    includedItems: ['Adaptación de puerta', 'Trabajos de acabado'],
    safetyNotice: 'Requiere evaluación estructural antes de presupuestar.',
  },
  'bathroom-vertical-support-rail': {
    name: 'Barra vertical de apoyo',
    shortDescription: 'Barra vertical colocada para ayudar a ponerse de pie y transferirse.',
    customerBenefit: 'Añade un punto de apoyo estable cuando corresponde.',
    category: 'Seguridad en el baño',
    includedItems: ['Barra vertical de apoyo', 'Fijaciones de montaje'],
    safetyNotice: 'Debe evaluarse la pared y la posición adecuada.',
  },
  'connected-emergency-button': {
    name: 'Botón de llamada de emergencia',
    shortDescription: 'Botón simple para pedir ayuda rápidamente.',
    customerBenefit: 'Pone ayuda al alcance en momentos de caída, bloqueo o preocupación.',
    category: 'Apoyo de emergencia',
    includedItems: ['Comprobación de ubicación', 'Botón compatible', 'Prueba de aviso'],
  },
  'connected-voice-hub': {
    name: 'Configuración de hub de voz',
    shortDescription: 'Control por voz para rutinas sencillas cuando ayuda.',
    customerBenefit: 'Reduce movimientos innecesarios para luces, llamadas o recordatorios básicos.',
    category: 'Controles sencillos',
    includedItems: ['Compatibilidad', 'Configuración inicial', 'Entrega a usuario y familia'],
  },
  'connected-family-alerts': {
    name: 'Configuración de avisos familiares',
    shortDescription: 'Avisos acordados para familiares o cuidadores.',
    customerBenefit: 'Aporta visibilidad sin complicar la vida diaria de la persona residente.',
    category: 'Tranquilidad familiar',
    includedItems: ['Preferencias de aviso', 'Configuración familiar', 'Prueba de notificación'],
  },
  'connected-fall-detection': {
    name: 'Revisión de detección de caídas',
    shortDescription: 'Valorar opciones compatibles de detección o aviso.',
    customerBenefit: 'Ayuda a elegir una solución útil sin vigilancia innecesaria.',
    category: 'Apoyo de emergencia',
    includedItems: ['Revisión del perfil', 'Opciones compatibles', 'Prueba o recomendación'],
  },
  'connected-monitoring': {
    name: 'Opción de respuesta profesional',
    shortDescription: 'Revisión de opción de respuesta profesional cuando procede.',
    customerBenefit: 'Aclara si la familia necesita apoyo externo además de avisos familiares.',
    category: 'Apoyo de emergencia',
    includedItems: ['Revisión de necesidad', 'Opciones disponibles', 'Explicación de funcionamiento'],
  },
  'kitchen-prep-mats': {
    name: 'Alfombrillas antideslizantes de preparación',
    shortDescription: 'Superficies estables para zonas de preparación.',
    customerBenefit: 'Reduce deslizamientos y movimientos inseguros durante tareas diarias.',
    category: 'Seguridad de suelo y bipedestación',
    includedItems: ['Revisión de zona', 'Alfombrilla antideslizante', 'Prueba de uso'],
  },
  'kitchen-easy-grip-tools': {
    name: 'Utensilios de agarre fácil',
    shortDescription: 'Herramientas que reducen esfuerzo de manos y muñecas.',
    customerBenefit: 'Facilita preparar comida sin forzar ni usar agarres inseguros.',
    category: 'Preparación diaria',
    includedItems: ['Selección de herramientas', 'Prueba de agarre', 'Consejos de uso'],
  },
  'kitchen-lightweight-cookware': {
    name: 'Menaje ligero',
    shortDescription: 'Sartenes y recipientes más fáciles de levantar y mover.',
    customerBenefit: 'Reduce esfuerzo y riesgo al cocinar o transportar comida.',
    category: 'Preparación diaria',
    includedItems: ['Revisión de rutina', 'Selección de menaje', 'Entrega de uso'],
  },
  'kitchen-anti-fatigue-mat': {
    name: 'Alfombra antideslizante antifatiga',
    shortDescription: 'Zona más estable y cómoda para estar de pie.',
    customerBenefit: 'Reduce cansancio y mejora agarre en tareas de cocina.',
    category: 'Seguridad de suelo y bipedestación',
    includedItems: ['Ubicación recomendada', 'Alfombra compatible', 'Prueba de estabilidad'],
  },
  'kitchen-worktop-lighting': {
    name: 'Iluminación de encimera',
    shortDescription: 'Luz directa para preparar, cortar y cocinar.',
    customerBenefit: 'Mejora visibilidad donde se usan cuchillos, calor y agua.',
    category: 'Iluminación y visibilidad',
    includedItems: ['Revisión de zonas', 'Luz de trabajo', 'Configuración'],
  },
  'kitchen-voice-lighting-timers': {
    name: 'Luces y temporizadores por voz',
    shortDescription: 'Control sencillo de luz y avisos de cocina.',
    customerBenefit: 'Reduce olvidos y movimientos innecesarios mientras se cocina.',
    category: 'Tranquilidad inteligente',
    includedItems: ['Configuración de voz', 'Temporizadores', 'Entrega de uso'],
  },
  'kitchen-smart-plugs': {
    name: 'Enchufes inteligentes seleccionados',
    shortDescription: 'Control sencillo para aparatos compatibles.',
    customerBenefit: 'Ayuda a apagar o programar dispositivos sin agacharse ni desplazarse.',
    category: 'Tranquilidad inteligente',
    includedItems: ['Comprobación de aparato', 'Enchufe inteligente', 'Configuración y prueba'],
  },
  'kitchen-water-leak-sensor': {
    name: 'Sensor de fuga de agua',
    shortDescription: 'Aviso temprano cerca de fregadero, lavadora o lavavajillas.',
    customerBenefit: 'Detecta fugas antes de que generen caídas o daños mayores.',
    category: 'Seguridad de agua y electrodomésticos',
    includedItems: ['Ubicación del sensor', 'Sensor compatible', 'Prueba de aviso'],
  },
  'kitchen-gas-co-sensor': {
    name: 'Sensor de gas o CO',
    shortDescription: 'Aviso compatible para gas o monóxido de carbono.',
    customerBenefit: 'Añade una capa de aviso en cocinas o zonas con aparatos compatibles.',
    category: 'Seguridad de agua y electrodomésticos',
    includedItems: ['Revisión de ubicación', 'Sensor compatible', 'Prueba de alarma'],
  },
  'kitchen-pull-down-shelf': {
    name: 'Estante abatible de armario alto',
    shortDescription: 'Baja objetos de armarios altos a una zona más accesible.',
    customerBenefit: 'Reduce estiramientos, taburetes y movimientos por encima del hombro.',
    category: 'Alcance y almacenamiento',
    includedItems: ['Medición de armario', 'Selección de herraje', 'Instalación profesional'],
  },
  'kitchen-stove-shutoff': {
    name: 'Apagado automático de cocina',
    shortDescription: 'Medida de seguridad para determinados fogones o placas.',
    customerBenefit: 'Reduce riesgo cuando hay olvidos o dificultad para confirmar apagado.',
    category: 'Seguridad de agua y electrodomésticos',
    includedItems: ['Revisión de compatibilidad', 'Dispositivo de seguridad', 'Prueba y entrega'],
  },
  'kitchen-touchless-faucet': {
    name: 'Grifo sin contacto',
    shortDescription: 'Control de agua sin girar mandos.',
    customerBenefit: 'Reduce esfuerzo, mejora higiene y puede ayudar a evitar agua abierta.',
    category: 'Seguridad de agua y electrodomésticos',
    includedItems: ['Revisión de grifo', 'Selección compatible', 'Instalación y prueba'],
  },
}
